### DISCUSSION TITLE
Collect aggregate efficiency data for ONTAP 9.8 and below through Harvest Rest Collector

### DISCUSSION THREAD

**Discussion by rahulguptajss** [NetApp/harvest#1057] [Show and tell]
ONTAP 9.8 and below does not expose [efficiency fields](https://github.com/NetApp/harvest/blob/main/conf/zapi/cdot/9.8.0/aggr_efficiency.yaml#L13-L16) through Zapi. There is a way to collect the same through Rest collector. Harvest Rest collector is officially supported from ONTAP 9.12 so sugestion here is just a workaround. Below are the required template changes.

1. Add Rest Collector for such clusters [9.8 or below] in harvest config. (Zapi collector is still required)
2. Comment out all objects listed under **rest** [default.yaml](https://github.com/NetApp/harvest/blob/main/conf/rest/default.yaml#L8-L30)
3. Create a new file custom.yaml [here](https://github.com/NetApp/harvest/tree/main/conf/rest) with below contents

```yaml
objects:
  AggregateEfficiency:         custom_aggr_efficiency.yaml
```

4: Create a new file custom_aggr_efficiency [here](https://github.com/NetApp/harvest/tree/main/conf/rest/9.12.0) with below contents

updated custom_agg_efficiency template as below.

```yaml

name:               Aggregate
query:              api/storage/aggregates
object:             aggr

counters:
  - ^name                                                          => aggr
  - ^^uuid                                                         => uuid
  - ^home_node.name                                                => node
  - ^state                                                         => state
  - ^block_storage.primary.disk_type                               => type
  - ^block_storage.primary.raid_type                               => raid_type
  - space.efficiency_without_snapshots.logical_used                => logical_used_wo_snapshots
  - space.efficiency_without_snapshots.savings                     => efficiency_savings_wo_snapshots
  - hidden_fields:
      - space


plugins:
  - LabelAgent:
      compute_metric:
        - physical_used_wo_snapshots SUBTRACT space.efficiency_without_snapshots.logical_used space.efficiency_without_snapshots.savings
```

5: Restart harvest/relevant pollers.

**Note:** During upgrade, rollback above changes and redo post upgrade.

**Comment by rahulguptajss** [comment]
updated custom_agg_efficiency template as below and in above post also.

```yaml

name:               Aggregate
query:              api/storage/aggregates
object:             aggr

counters:
  - ^name                                                          => aggr
  - ^^uuid                                                         => uuid
  - ^home_node.name                                                => node
  - ^state                                                         => state
  - ^block_storage.primary.disk_type                               => type
  - ^block_storage.primary.raid_type                               => raid_type
  - space.efficiency_without_snapshots.logical_used                => logical_used_wo_snapshots
  - space.efficiency_without_snapshots.savings                     => efficiency_savings_wo_snapshots
  - hidden_fields:
      - space


plugins:
  - LabelAgent:
      compute_metric:
        - physical_used_wo_snapshots SUBTRACT space.efficiency_without_snapshots.logical_used space.efficiency_without_snapshots.savings
```
