### DISCUSSION TITLE
Collect client lock details template

### DISCUSSION THREAD

**Discussion by rahulguptajss** [NetApp/harvest#1070] [Show and tell]
1. Create a new file `custom.yaml` [here](https://github.com/NetApp/harvest/tree/main/conf/zapi) with below contents

```yaml
objects:
  Lock:                   custom_lock.yaml
```

2. Create a new file `custom_lock.yaml` [here](https://github.com/NetApp/harvest/tree/main/conf/zapi/9.8.0)

3. update `custom_lock.yaml` template as below.

```yaml
name:             Lock
query:            lock-get-iter
object:           lock

schedule:
  - instance: 180s
  - data: 180s

counters:
  lock-info:
    - ^^lockid                => lock_id
    - ^volume                 => volume
    - ^vserver                => svm
    - ^client-address         => client_address
    - ^is-constituent         => is_constituent
    - ^is-sharelock-soft      => is_share_lock_soft
    - ^lif                    => lif
    - ^lock-state             => lock_state
    - ^lock-type              => lock_type
    - ^node                   => node
    - ^path                   => path
    - ^protocol               => protocol
    - ^sharelock-mode         => share_lock_mode


collect_only_labels: true

export_options:
  instance_keys:
    - lock_id
  instance_labels:
    - volume
    - svm
    - client_address
    - is_constituent
    - is_share_lock_soft
    - lif
    - lock_state
    - lock_type
    - path
    - protocol
    - share_lock_mode
```

4. Restart harvest.

5. Below metrics should be available in promeheus.

![image](https://user-images.githubusercontent.com/25551691/172173878-957ad856-0282-49a4-b54d-690f508f027e.png)
