### DISCUSSION TITLE
Curious - Is there a plan to add "qtree show" metrics?

### DISCUSSION THREAD

**Discussion by jmg011** [NetApp/harvest#1179] [Ideas]
Hi!  Currently we see tree quotas from "qtree report" in qtree* metrics. I'm curious if there is a plan to add other qtree metrics from "qtree show" command output. 

Is it something I can build with templates without having to update any plugins for qtree?

**Comment by cgrinds** [comment]
hi @jmg011 it will probably require plugin changes because these objects often require correlating multiple ZAPI/REST calls since a single API doesn't exist with all the information.

But first, let's talk details. When I run `qtree show` I see
```
umeng-aff300-05-06::> qtree show
Vserver    Volume        Qtree        Style        Oplocks   Status
---------- ------------- ------------ ------------ --------- --------
astra_devops_vs1
           astra_devops_vs1_root
                         ""           mixed        enable    normal
astra_devops_vs1
           temp1         ""           mixed        enable    normal
astra_devops_vs1
           trident_pvc_05941e9a_4b6c_430e_9f16_a322f9c8dc54
                         ""           unix         enable    normal
```

Can you outline which metrics from this output you want included?

**Comment by jmg011** [comment]
@cgrinds Thanks for a super quick response on this. 

Below metadata, all fields as labels and status as a metric would be helpful if included in the plugin. That way, we have all the metrics for qtrees. 
 
vserver
volume
qtree
qtree-path    
security-style 
user 
group 
unix-permissions 
status 
export-policy 
is-export-policy-inherited 
qos-policy-group

**Reply by cgrinds** [reply]
makes sense, we'll take a look

**Comment by Hardikl** [comment]
@jmg011 

I have evaluated the above given field list (from `qtree show` cli).

Out of the given field list, 
**ZAPI** don't have **group**, **user**, **qtree-path** fields in qtree-list-iter response, whereas 
**REST** have all the fields via public(/api/storage/qtrees) and private(/api/private/cli/qtree) apis.

-----------------
### Collection via REST way

Steps to monitor all the mentioned fields via REST are as below.  
Please note, you'll need to enable Rest Collector for the poller in harvest configuration and disable(commented) qtree object in ZAPI [here](https://github.com/NetApp/harvest/blob/main/conf/zapi/default.yaml#L17).

1. Create a new file `custom.yaml` [here](https://github.com/NetApp/harvest/tree/main/conf/rest) with below contents

```yaml
objects:
  Qtree:                       custom_qtree.yaml
  
```

2. Create a new file `custom_qtree.yaml` [here](https://github.com/NetApp/harvest/tree/main/conf/rest/9.12.0)

3. update `custom_qtree.yaml` template as below.


```yaml
name:                       Qtree
query:                      api/storage/qtrees
object:                     qtree

counters:
  - ^^svm.name            => svm
  - ^^volume.name         => volume
  - ^^name                => qtree
  - ^export_policy.name   => export_policy
  - ^security_style       => security_style
  - ^unix_permissions     => unix_permissions
  - ^qos_policy.name      => qos_policy_group
  - id                    => id
  - filter:
      - name=!""


endpoints:
  - query: api/private/cli/qtree
    counters:
      - ^^vserver         => svm
      - ^^volume          => volume
      - ^^qtree           => qtree
      - ^status           => status
      - ^oplock_mode      => oplocks
      - ^qtree_path       => qtree_path
      - ^user             => user_name
      - ^group            => group_name
      - ^is_export_policy_inherited => is_export_policy_inherited
      - filter:
          - qtree=!""
plugins:
  - Qtree
  - LabelAgent:
      replace:
        - oplocks oplocks `enable` `enabled`

export_options:
  instance_keys:
    - qtree
    - volume
    - svm
  instance_labels:
    - export_policy
    - security_style
    - status
    - oplocks
    - qtree_path
    - user_id
    - user_name
    - group_id
    - group_name
    - unix_permissions
    - qos_policy_group
    - is_export_policy_inherited
```

4. Restart harvest.

5. Below qtree metrics should be available in Prometheus.

![image](https://user-images.githubusercontent.com/83282894/182821576-06b052bc-8587-4f4b-a2a3-104714010ce7.png)

6. Regarding status as metric, This can be doable by this way [example](https://github.com/NetApp/harvest/blob/main/conf/rest/9.12.0/node.yaml#L31)

```  
- LabelAgent:
      value_to_num:
        - new_status status normal normal `0`
 ```

Just for reference, status value could be only "**normal**" or "**readonly**".
![image](https://user-images.githubusercontent.com/83282894/182616380-fd864349-72a5-47e9-9ebc-172f8b593ca8.png)



**Note**: In Harvest upgrade, REST collector would be disabled by default. You would need to enable again after upgrade to collect the qtree metrics via REST.


------------------------------------
### Collection via ZAPI way

Steps to monitor available fields via ZAPI are as below.  

1. Create a new file `custom.yaml` [here](https://github.com/NetApp/harvest/tree/main/conf/zapi) with below contents

```yaml
objects:
  Qtree:                       custom_qtree.yaml
  
```

2. Create a new file `custom_qtree.yaml` [here](https://github.com/NetApp/harvest/tree/main/conf/zapi/cdot/9.8.0)

3. update `custom_qtree.yaml` template as below.


```yaml

counters:
  qtree-info:
    - ^mode                        => unix_permissions
    - ^is-export-policy-inherited  => is_export_policy_inherited
    - ^qos-policy-group            => qos_policy_group

export_options:
  instance_labels:
    - unix_permissions
    - is_export_policy_inherited
    - qos_policy_group
   
```

4. Restart harvest.

5. Below qtree metrics should be available in prometheus.

![image](https://user-images.githubusercontent.com/83282894/182819812-dc1e9b2a-10dc-4008-b020-7dfba37f552a.png)

6. Regarding status as metric, This can be doable by this way [example](https://github.com/NetApp/harvest/blob/main/conf/zapi/cdot/9.8.0/status.yaml#L14)

```  
- LabelAgent:
      value_to_num:
        - new_status status normal normal `0`
 ```

Just for reference, status value could be only "**normal**" or "**readonly**".
![image](https://user-images.githubusercontent.com/83282894/182616380-fd864349-72a5-47e9-9ebc-172f8b593ca8.png)
