### DISCUSSION TITLE
Monitor memory DIMM status in Harvest

### DISCUSSION THREAD

**Discussion by rahulguptajss** [NetApp/harvest#1187] [Show and tell]
related to issue #1024, Private Rest CLI monitoring for DIMM is as below. Please note, you'll need to enable Rest Collector for the poller in harvest configuration.

1. Create a new file `custom.yaml` [here](https://github.com/NetApp/harvest/tree/main/conf/rest) with below contents

```yaml
objects:
  DIMM:                         custom_dimm.yaml
```

2. Create a new file `custom_dimm.yaml` [here](https://github.com/NetApp/harvest/tree/main/conf/rest/9.12.0)

3. update `custom_dimm.yaml` template as below.

```yaml
name:                         DIMM
query:                        api/private/cli/system/controller/fru
object:                       dimm

counters:
  - ^^serial_number               => serial_number
  - ^node                         => node
  - ^subsystem                    => subsystem
  - ^fru_name                     => fru_name
  - ^status                       => status
  - filter:
    - subsystem=Memory

plugins:
  - LabelAgent:
      value_to_num: # metric label zapi_value rest_value `default_value`
        - status status ok ok `0`

export_options:
  include_all_labels: true

```

4. Restart harvest.

5. Below metrics should be available in promeheus.

![image](https://user-images.githubusercontent.com/25551691/182409654-2d4a9d83-64f5-45ab-96a5-35e5e8071e6e.png)

6: Based on this status information, relevant dashboard panels can be developed in Harvest.
