### DISCUSSION TITLE
Enable netConnections in NAbox

### DISCUSSION THREAD

**Discussion by rahulguptajss** [NetApp/harvest#1284] [Show and tell]
At the time of writing this discussion, `netConnections` template is only available in [nightly](https://github.com/NetApp/harvest/releases/tag/nightly) builds.

**Pre-Requisite:** Make sure , you have a build installed in NAbox which has [netConnections](https://github.com/NetApp/harvest/blob/main/conf/rest/9.12.0/netConnections.yaml) template.

This template is only available via Rest Collector, Below steps are required to collect this data.

1. SSH to NAbox machine via root as mentioned [here](https://nabox.org/documentation/configuration/).
2. Go to directory `/opt/harvest2-conf/conf/rest` and create a file `custom.yaml` if not exists.
3. Add below content in this file

```yaml
objects:
  NetConnections:              netConnections.yaml
```
4: Enable Rest collector in harvest configuration in `/opt/harvest2-conf/harvest.yml`. Example below
```yaml
Defaults:
  collectors:
    - Zapi
    - ZapiPerf
    - Rest
  exporters:
    - nabox-prometheus
Exporters:
  nabox-prometheus:
    addr: 0.0.0.0
    exporter: Prometheus
    master: true
Pollers:
  xxxxxxx:
    addr: xxxxx
    autostart: '1'
    datacenter: dc-1
    password: xxxxxx
    prometheus_port: 12990
    use_insecure_tls: true
    username: xxxx
```

5: Restart NAbox through command `dc down`
6: Wait for few minutes and you should see below metrics in prometheus. (https://nabox/prometheus)

![image](https://user-images.githubusercontent.com/25551691/190441169-985d711c-a38d-4d9b-b333-97e765f2d55e.png)
