### DISCUSSION TITLE
Harvest Template & Schedule Related Questions

### DISCUSSION THREAD

**Discussion by Tech113** [NetApp/harvest#1327] [General]
Hello, 

What is the best way to retrieve comma separated values of the field with multiple values?

i.e. : If a field has three possible values x, y, z on the filer, the template only retrieves one value. Is there a way to parse them separately so it shows field=x   field=y   field=z  as three different timeseries instead of just one field=z ?

Schedule:
1 - In custom.yaml file, is it possible to add two different data collection schedules for different objects? 
2 - What is the correct format to add multiple schedules for various different objects in the same custom.yaml file? 
3 - What is the difference between instance field and data field of below schedule?
4 - Is it possible to schedule a collection at certain time of the day instead of frequency?
5 - Is it possible to cache data only during certain time of the day?

schedule:
  - instance: 120s
  - data: 60s

**Comment by cgrinds** [comment]
hi @Tech113 for the comma separated values, can you share an example of the ZAPI or REST request you're using?

**Reply by Tech113** [reply]
network interface show command on the cluster has a field called data-protocol with comma separated values like this:
nfs,cifs,fcache

sample template: this collects only one out of each comma separated values

name:                      networkinterface
query:                     net-interface-get-iter
object:                    netint

collect_only_labels:       true

counters:
  net-interface-info:
    - ^address
    - ^^interface-name        => interface
    - data-protocols:
        - ^^data-protocol     => data_protocol

plugins:
  LabelAgent:
    value_to_num:
      - test_status status ok ok `1`

export_options:
  include_all_labels: true

**Reply by rahulguptajss** [reply]
@Tech113 Currently Zapi Collector do not support handling of multiple values for same label. I have opened a bug #1360 for this. This can be done through Rest collector. Template below. There are steps highlighted in #1187 on how to enable Rest templates in Harvest

```yaml
name:               networkinterface
query:              api/private/cli/network/interface
object:             netint

counters:
  - ^^data_protocol => data_protocol
  - ^address        => address
  - ^^lif           => interface

plugins:
  LabelAgent:
    value_to_num:
      - test_status status ok ok 1

export_options:
  include_all_labels: true
```
