### DISCUSSION TITLE
Why it's so complicated? I'm not sure I've understand the solution

### DISCUSSION THREAD

**Discussion by XDavidT** [NetApp/harvest#1702] [Q&A] [answered]
For a few days, I've been looking for a way to get logs from NetApp storage to show up on our Grafana.
This is the closest solution I've found, but also that, the command that generates docker-compose.yaml create a complete solution that includes grafana and Prometheus together, the wizard does not provide you any details to add for the progress and links it to your NetApp server.

Why there is no basic image I can use to export logs from the NetApp dashboard, using 3 parameters only: Host, User, and Password?

**Comment by rahulguptajss** [comment, marked as answer]
@XDavidT Harvest collects its counters via EMS, ZAPI, REST, and the private CLI that REST exposes from ONTAP.  
Are you trying to collect event logs `event log show` from ONTAP using Harvest? 

Could you provide more details on which wizard are you refrerring to? Harvest Host,user,password needs to be configured in `harvest.yml` as mentioned [here](https://netapp.github.io/harvest/23.02/install/containers/#setup-harvestyml) before `docker-compose` steps.

**Reply by XDavidT** [reply]
I want general metrics for non-expert NetApp users. for such storage capacity at all, or per volume, how much data is read currently, how much data is written current time, average read, and more generic data. Server temperature, server health, and more
Is Harvest not the right solution for this?

**Reply by rahulguptajss** [reply]
Yes, Harvest collects all of these metrics and much more. Perhaps, you are facing issue in setting up Harvest using docker? 
 There are setup steps mentioned [here](https://netapp.github.io/harvest/23.02/install/containers/#setup-harvestyml). Could you let us know the problems faced in more detail?

**Reply by cgrinds** [reply]
hi @XDavidT yes, as Rahul mentioned, Harvest collects those metrics, stores them in Prometheus, and provides Grafana dashboards to display them. We're happy to help if you share which step you're having problems with.

**Reply by XDavidT** [reply]
> hi @XDavidT yes, as Rahul mentioned, Harvest collects those metrics, stores them in Prometheus, and provides Grafana dashboards to display them. We're happy to help if you share which step you're having problems with.

I saw that and you're right, after running:
`bin/harvest generates docker full --output harvest-compose.yml`
I got 2 docker compose files (by the way in your example you showed `docker-compose` instead `docker compose` which is the new plugin)
And after "up" them, I get the harvest with Grafana & Prometheus.
I don't look for any Grafana and Prometheus, I already have an instance running on our company, and I only need to have `/metrics` to scrape using our Prometheus. 
So my questions are:

1. How to start Harvest without an instance of Prom&Grafana?
2. Where do I need to put the NetApp instance details such as host/user/pass?
3. Why do I need  harvest binary file to generate docker compose? Why you don't have an image on Docker Hub that I can pull and use on a simple docker compose?

**Reply by rahulguptajss** [reply]
@XDavidT 

**1. How to start Harvest without an instance of Prom&Grafana?**
     
You can expose `/metrics` endpoint by adding `--port` to generate command as mentioned in docs shared earliar. This `/metrics` endpoint can then be scraped by your own prometheus instance.
![image](https://user-images.githubusercontent.com/25551691/217826280-6ab8a52c-67d5-402e-900c-9be764c3945f.png)
If you don't wish to start new prometheus and grafana instances, then you can omit `prom-stack.yml` from docker compose up command which will only start harvest containers.

`docker-compose -f harvest-compose.yml up -d --remove-orphans`

**2. Where do I need to put the NetApp instance details such as host/user/pass?**

Once you download the binary, There is a `havest.yml` in its root dir. You can add your ontap cluster in that file as mentioned [here](https://netapp.github.io/harvest/23.02/install/containers/#setup-harvestyml). This needs to be done before you generate docker compose file.

**Reply by XDavidT** [reply]
OK, omit `prom-stack.yml` not work as is.
```
$ docker compose -f harvest-compose.yml up -d --remove-orphans
service "cluster-01" refers to undefined network backend: invalid compose project
```

**Edit1:**
This is what the yaml looks like:
```
version: "3.7"

services:

  cluster-01:
    image: cr.netapp.io/harvest:latest
    container_name: poller-cluster-01
    restart: unless-stopped
    
    command: '--poller cluster-01 --config /opt/harvest.yml'
    volumes:
      - /tmp/harvest-22.08.0-1_linux_amd64/conf:/opt/harvest/conf
      - /tmp/harvest-22.08.0-1_linux_amd64/cert:/opt/harvest/cert
      - /tmp/harvest-22.08.0-1_linux_amd64/harvest.yml:/opt/harvest.yml
    networks:
      - backend
```
I've tried to delete the `backend` network, but still, I don't see any ports that were added to my compose

**Edit2:**
I've exec into the container and found there is only one port it's listening to, which is replaced on any restart. Seem the metric service didn't start well

**Reply by rahulguptajss** [reply]
Okay. Let's try below steps. 

1. `bin/harvest generate docker full --port --output harvest-compose.yml`
2. // remove networks manually for now from `harvest-compose.yml` We'll fix it in harvest code so that we can start just harvest containers.
3. `docker-compose -f harvest-compose.yml up -d --remove-orphans`

<img width="535" alt="image" src="https://user-images.githubusercontent.com/25551691/217849916-053ffbd3-2113-466d-801e-7b20546cfb49.png">

**Reply by XDavidT** [reply]
Here is my `harvest.yml`:
```
Admin:
  # Listen address for Prometheus HTTP service discovery end-point
  # The endpoint is reachable at SCHEMA://<listen>/api/v1/sd
  # Should be one of: localhost:port, :port, or ip:port
  # httpsd:
    # listen: :8887
    # listen: localhost:8887

    # Basic auth for - /api/v1/sd
    # auth_basic: 
    #   username: admin
    #   password: admin

    # create self-signed certs with 'bin/harvest admin tls create server'
    # tls:
    #   cert_file: cert/admin-cert.pem
    #   key_file: cert/admin-key.pem

Tools:
#  grafana_api_token: 'aaa-bbb-ccc-ddd'
#  autosupport_disabled: true

Exporters:
  prometheus:
    exporter: Prometheus
    local_http_addr: 0.0.0.0
    port: 12990
  prometheus1:
    exporter: Prometheus
    port_range: 13000-14000

Defaults:
  collectors:
    - Zapi
    - ZapiPerf
    - Ems
  use_insecure_tls: false

Pollers:
  # add your cDOT / 7Mode pollers below, example:
 cluster-01:
   datacenter: OURCLUSTERNAME
   addr: 192.168.1.2
   auth_style: basic_auth
  #   credentials_file: path/to/credentials.yml # read credentials from the file
   username: user-admin
   password: --------   
   use_insecure_tls: true
```

and here the `harvest-compose.yml`:
```
version: "3.7"

services:

  cluster-01:
    image: cr.netapp.io/harvest:latest
    container_name: poller-cluster-01
    restart: unless-stopped
    ports:
      - 12991:12991
    command: '--poller cluster-01 --promPort 12991 --config /opt/harvest.yml'
    volumes:
      - /tmp/harvest-22.08.0-1_linux_amd64/conf:/opt/harvest/conf
      - /tmp/harvest-22.08.0-1_linux_amd64/cert:/opt/harvest/cert
      - /tmp/harvest-22.08.0-1_linux_amd64/harvest.yml:/opt/harvest.yml
```

But still no metrics on http://localhost:12991/metrics
Does it right? I made it all good?

**Reply by rahulguptajss** [reply]
It takes few minutes for poller to start (2-3 minutes). I have edited your `harvest.yml` as it was missing exporter mapping.

```
Exporters:
  prometheus:
    exporter: Prometheus
    local_http_addr: 0.0.0.0
    port: 12990
  prometheus1:
    exporter: Prometheus
    port_range: 13000-14000

Defaults:
  collectors:
    - Zapi
    - ZapiPerf
    - Ems
  use_insecure_tls: false
  exporters:
    - prometheus1

Pollers:
  # add your cDOT / 7Mode pollers below, example:
 cluster-01:
   datacenter: OURCLUSTERNAME
   addr: 192.168.1.2
   auth_style: basic_auth
   username: user-admin
   password: --------   
   use_insecure_tls: true
```


It may be possible that your container is failing. Could you share logs for the poller containerr?
`docker logs poller-cluster-01`
