### DISCUSSION TITLE
Enable qos templates in Harvest

### DISCUSSION THREAD

**Discussion by rahulguptajss** [NetApp/harvest#1800] [Show and tell]
1. We are going to create a `custom.yaml` file in the appropriate directory. In below commands, Harvest is installed in `/opt/harvest`
- For ZapiPerf `vi /opt/harvest/conf/zapiperf/custom.yaml`
- For RestPerf (9.12+ onwards) `vi /opt/harvest/conf/restperf/custom.yaml`

2. Add below content in this file. If `custom.yaml` already exists then just add the template under `Objects:`

```yaml
objects:
  Workload:               workload.yaml
  WorkloadDetail:         workload_detail.yaml
  WorkloadVolume:         workload_volume.yaml
  WorkloadDetailVolume:   workload_detail_volume.yaml
```

3. Restart Harvest
4. Wait for few minutes(at least 10 min) and you should see qos metrics in prometheus.
