### DISCUSSION TITLE
Harvest should collect export rules

### DISCUSSION THREAD

**Discussion by cgrinds** [NetApp/harvest#1821] [Show and tell]
This only works for the REST collector.

We are going to create a new template and add it to your `custom.yaml`. In the commands below, Harvest is installed in `/opt/harvest`. Adjust as needed.

1. Edit `vi /opt/harvest/conf/rest/custom.yaml` 

2. Add below content to this file. If `custom.yaml` already exists then add the `ExportRule` line under the `Objects:` section.

```yaml
objects:
    ExportRule:                  exports.yaml
```

3. Create the `exports.yaml` file `vi /opt/harvest/conf/rest/9.8.0/exports.yaml`
4. Copy paste the following into file and save.

```yaml
name:                     ExportRule
query:                    api/private/cli/export-policy/rule
object:                   export_rule

counters:
  - ^^vserver          => svm
  - ^^policyname       => policy
  - ^^ruleindex        => index
  - ^protocol          => protocol
  - ^clientmatch       => clientmatch
  - ^rorule            => rorule
  - ^rwrule            => rwrule
  - ^superuser         => superuser

export_options:
  instance_keys:
    - svm
    - policy
    - index
  instance_labels:
    - svm
    - policy
    - index
    - protocol
    - clientmatch
    - rorule
    - rwrule
    - superuser
```

5. Restart Harvest
6. After a few minutes you should see export rules in Prometheus. E.g. 
```bash
curl http://localhost:$promPort/metrics | grep -Ev "#|metadata_" | sort

export_rule_labels{clientmatch="0.0.0.0/0",cluster="AFF",datacenter="blg",index="1",policy="NSLM_OMSHIFT_1605851513826",protocol="nfs3,nfs4",rorule="any",rwrule="any",superuser="none",svm="OMSHIFT"} 1.0
export_rule_labels{clientmatch="0.0.0.0/0",cluster="AFF",datacenter="blg",index="1",policy="default",protocol="any",rorule="any",rwrule="any",superuser="any",svm="OMSHIFT"} 1.0
export_rule_labels{clientmatch="0.0.0.0/0",cluster="AFF",datacenter="blg",index="1",policy="default",protocol="nfs",rorule="any",rwrule="any",superuser="any",svm="svm_test"} 1.0
export_rule_labels{clientmatch="0.0.0.0/0",cluster="AFF",datacenter="blg",index="1",policy="ndvp_qtree_pool_export_policy",protocol="cifs,nfs",rorule="any",rwrule="any",superuser="any",svm="A_SVM_FOR_CONTAINERS"} 1.0
export_rule_labels{clientmatch="0.0.0.0/0",cluster="AFF",datacenter="blg",index="1",policy="trident_qtree_pool_export_policy",protocol="nfs",rorule="any",rwrule="any",superuser="any",svm="OMSHIFT"} 1.0
export_rule_labels{clientmatch="0.0.0.0/0",cluster="AFF",datacenter="blg",index="2",policy="demo_source_data",protocol="any",rorule="any",rwrule="any",superuser="any",svm="A_SVM_FOR_CONTAINERS"} 1.0
export_rule_labels{clientmatch="0.0.0.0/0",cluster="AFF",datacenter="blg",index="3",policy="default",protocol="any",rorule="any",rwrule="any",superuser="any",svm="SVM_NAS"} 1.0
export_rule_labels{clientmatch="0.0.0.0/0",cluster="AFF",datacenter="blg",index="3",policy="default",protocol="cifs,nfs",rorule="any",rwrule="any",superuser="any",svm="A_SVM_FOR_CONTAINERS"} 1.0
export_rule_labels{clientmatch="10.65.176.0/24",cluster="AFF",datacenter="blg",index="4",policy="default",protocol="nfs",rorule="any",rwrule="any",superuser="any",svm="A_SVM_FOR_CONTAINERS"} 1.0

```
