### DISCUSSION TITLE
Rest Collector total_provisioned_space metric for Aggregates

### DISCUSSION THREAD

**Discussion by rahulguptajss** [NetApp/harvest#2130] [Show and tell]
Below steps are for REST collector.

We are going to create a new template and add it to your `custom.yaml`. In the commands below, Harvest is installed in `/opt/harvest`. Adjust as needed.

1. Edit `vi /opt/harvest/conf/rest/custom.yaml` 

2. Add below content to this file. If `custom.yaml` already exists then add the `AggregateSpace` line under the `Objects:` section.

```yaml
objects:
  AggregateSpace:                   aggr_space.yaml
```

3. Create the `custom_aggr.yaml` file `vi /opt/harvest/conf/rest/9.12.0/aggr_space.yaml`
4. Copy paste the following into file and save.

```yaml

name:               AggregateSpace
query:              api/private/cli/aggr/show-space
object:             aggr

counters:
  - ^^aggregate_uuid                     => uuid
  - ^^bin_num                            => bin_num
  - ^aggregate_name                      => aggr
  - ^tier_name                           => tier_name
  - total_provisioned_space
  - total_provisioned_space_percent


export_options:
  instance_keys:
    - bin_num
    - aggr
    - tier_name

```

5. Restart Harvest
6. After a few minutes you should see export rules in Prometheus. E.g. 
```bash
curl http://localhost:$promPort/metrics | grep total_provisioned_space

aggr_total_provisioned_space{datacenter="u2",cluster="umeng-aff300-01-02",bin_num="0",aggr="umeng_aff300_aggr2",tier_name=" "} 87586967617536
aggr_total_provisioned_space{datacenter="u2",cluster="umeng-aff300-01-02",bin_num="0",aggr="aggr0",tier_name=" "} 374328692736
aggr_total_provisioned_space{datacenter="u2",cluster="umeng-aff300-01-02",bin_num="0",aggr="aggr0_umeng_aff300_02_0",tier_name=" "} 374328692736
aggr_total_provisioned_space{datacenter="u2",cluster="umeng-aff300-01-02",bin_num="0",aggr="test",tier_name="Performance Tier"} 15885509300224


```
