### DISCUSSION TITLE
Adding NetApp CLI commands to collector

### DISCUSSION THREAD

**Discussion by JustinNet1** [NetApp/harvest#2198] [Q&A]
Hey Team, I have a customer wondering how hard it would be to get the following NetApp CLI commands put into the collector:

 

                        "statistics show-periodic -interval 1 -iterations 1 -summary true -object process -instance secd -counter total_stat_period"

                        "statistics show-periodic -interval 1 -iterations 1 -summary true -object process -instance mgwd -counter total_stat_period"

                        "statistics show-periodic -interval 1 -iterations 1 -summary true -object process -instance vldb -counter total_stat_period"

                        "statistics show-periodic -interval 1 -iterations 1 -summary true -object process -instance cifsKsmfUpCallThreadMain -counter total_stat_period"

**Comment by cgrinds** [comment]
Hi @JustinNet1 give this a try.

## Summary

- Add a new ZapiPerf template to collect these performance counters. Keep in mind these won't work with the RestPerf collector since these counters are not currently available via Rest.
- Tell Harvest to use the new template

## Steps

All of these commands are run from the Harvest install directory.

1. Create a new ZapiPerf template
```bash
vi conf/zapiperf/cdot/9.8.0/custom_process.yaml
```
2. Copy and paste the following into `custom_process.yaml`, save and exit.
```yaml

name:                     Process
query:                    process
object:                   process

instance_key:             uuid

counters:
  - instance_name       => name
  - node_name           => node
  - total_stat_period

plugins:
  LabelAgent:
    - include_equals:
        - name `cifsKsmfUpCallThreadMain`
        - name `mgwd`
        - name `secd`
        - name `vldb`

export_options:
  instance_keys:
    - name
    - node
```

3. Tell Harvest to use your new template by creating a file named `conf/zapiperf/custom.yaml`
4. Copy and paste the following into the `conf/zapiperf/custom.yaml` file
```yaml
objects:
  Process:                  custom_process.yaml
```
5. Restart Harvest
6. Collect new metrics, e.g.
```bash
curl -s 'http://localhost:12990/metrics' | grep process_total_stat_period

process_total_stat_period{cluster="umeng-aff300-01-02",datacenter="dc-1",name="cifsKsmfUpCallThreadMain",node="umeng-aff300-02"} 1681817534
process_total_stat_period{cluster="umeng-aff300-01-02",datacenter="dc-1",name="cifsKsmfUpCallThreadMain",node="umeng-aff300-03"} 1680601455
process_total_stat_period{cluster="umeng-aff300-01-02",datacenter="dc-1",name="mgwd",node="umeng-aff300-02"} 1681819055
process_total_stat_period{cluster="umeng-aff300-01-02",datacenter="dc-1",name="mgwd",node="umeng-aff300-03"} 1680604456
process_total_stat_period{cluster="umeng-aff300-01-02",datacenter="dc-1",name="secd",node="umeng-aff300-02"} 1681822536
process_total_stat_period{cluster="umeng-aff300-01-02",datacenter="dc-1",name="secd",node="umeng-aff300-03"} 1680605967
process_total_stat_period{cluster="umeng-aff300-01-02",datacenter="dc-1",name="vldb",node="umeng-aff300-02"} 1681822105
process_total_stat_period{cluster="umeng-aff300-01-02",datacenter="dc-1",name="vldb",node="umeng-aff300-03"} 1680602381
```
