### DISCUSSION TITLE
Qtree Historical Labels

### DISCUSSION THREAD

**Discussion by cgrinds** [NetApp/harvest#2223] [Show and tell]
> You probably don't want these and instead should use Harvest's out-of-the-box qtree templates

Example of qtree templates similar to version `22.05`. Take the out-of-the-box [qtree.yaml](https://github.com/NetApp/harvest/blob/release/23.05.0/conf/zapi/cdot/9.8.0/qtree.yaml) and extend with the following

### cdot
`conf/zapi/cdot/9.8.0/custom_qtree.yaml`

```yaml
counters:
  qtree-info:
    - id

plugins:
  - Qtree:
      historicalLabels: true
      quotaType:
        - user
        - group
        - tree
 ```

### Validate

```bash
bin/harvest doctor merge --template conf/zapi/cdot/9.8.0/qtree.yaml --with conf/zapi/cdot/9.8.0/custom_qtree.yaml
```

```yaml
name: Qtree
query: qtree-list-iter
object: qtree
client_timeout: 2m
counters:
  qtree-info:
    - ^^qtree   => qtree
    - ^^volume
    - ^^vserver => svm
    - ^export-policy
    - ^oplocks
    - ^security-style
    - ^status
    - id
collect_only_labels: true
plugins:
  LabelAgent:
    exclude_equals:
      - qtree ``
  Qtree:
    objects:
      - disk-limit
      - disk-used
      - disk-used-pct-disk-limit
      - disk-used-pct-soft-disk-limit
      - disk-used-pct-threshold
      - file-limit
      - files-used
      - files-used-pct-file-limit
      - files-used-pct-soft-file-limit
      - soft-disk-limit
      - soft-file-limit
      - threshold
    quotaType:
      - tree
      - user
      - group
    historicalLabels: true
export_options:
  instance_keys:
    - qtree
    - svm
    - volume
  instance_labels:
    - export_policy
    - oplocks
    - security_style
    - status

```
