### DISCUSSION TITLE
How to get tiering usage data?

### DISCUSSION THREAD

**Discussion by wooyoungAhn** [NetApp/harvest#2228] [Q&A] [answered]
Hello
I want to monitor how much used tiered data is by volume.

### CLI
```
FsxId014772ac53ce1ec23::> volume show-footprint -volume cifs_Vol


      Vserver : FsxN
      Volume  : cifs_Vol

      Feature                                         Used       Used%
      --------------------------------             ----------    -----
      Volume Data Footprint                            3.09MB       0%
             Footprint in Performance Tier            10.14MB     100%
             Footprint in FSxFabricpoolObjectStore         0B       0%
      Volume Guarantee                                     0B       0%
      Flexible Volume Metadata                        10.50MB       0%
      Delayed Frees                                    7.05MB       0%

      Total Footprint                                 20.64MB       0%

```

## API (may be..?)
```
CRED=fsxadmin:"---------"
ONTAP=172.30.4.224
curl -X GET -u ${CRED} -k https://${ONTAP}/api/storage/volumes?fields=space.capacity_tier_footprint,svm
```
```json
{
  "records": [
    {
      "uuid": "18ed9a59-26e5-11ee-a15c-710ff4588dd1",
      "name": "nfs_Vol",
      "svm": {
        "name": "FsxN",
        "uuid": "f4df1cdb-26e4-11ee-a15c-710ff4588dd1",
        "_links": {
          "self": {
            "href": "/api/svm/svms/f4df1cdb-26e4-11ee-a15c-710ff4588dd1"
          }
        }
      },
      "space": {
        "capacity_tier_footprint": 0
      },
      "_links": {
        "self": {
          "href": "/api/storage/volumes/18ed9a59-26e5-11ee-a15c-710ff4588dd1"
        }
      }
    },
    {
      "uuid": "5e531b2f-26fa-11ee-a15c-710ff4588dd1",
      "name": "cifs_Vol",
      "svm": {
        "name": "FsxN",
        "uuid": "f4df1cdb-26e4-11ee-a15c-710ff4588dd1",
        "_links": {
          "self": {
            "href": "/api/svm/svms/f4df1cdb-26e4-11ee-a15c-710ff4588dd1"
          }
        }
      },
      "space": {
        "capacity_tier_footprint": 0
      },
      "_links": {
        "self": {
          "href": "/api/storage/volumes/5e531b2f-26fa-11ee-a15c-710ff4588dd1"
        }
      }
    },
    {
      "uuid": "9c470c4b-26ea-11ee-a15c-710ff4588dd1",
      "name": "vol1",
      "svm": {
        "name": "FsxN",
        "uuid": "f4df1cdb-26e4-11ee-a15c-710ff4588dd1",
        "_links": {
          "self": {
            "href": "/api/svm/svms/f4df1cdb-26e4-11ee-a15c-710ff4588dd1"
          }
        }
      },
      "space": {
        "capacity_tier_footprint": 0
      },
      "_links": {
        "self": {
          "href": "/api/storage/volumes/9c470c4b-26ea-11ee-a15c-710ff4588dd1"
        }
      }
    },
    {
      "uuid": "f25c133d-26e8-11ee-a15c-710ff4588dd1",
      "name": "cifs_Vol2",
      "svm": {
        "name": "FsxN",
        "uuid": "f4df1cdb-26e4-11ee-a15c-710ff4588dd1",
        "_links": {
          "self": {
            "href": "/api/svm/svms/f4df1cdb-26e4-11ee-a15c-710ff4588dd1"
          }
        }
      },
      "space": {
        "capacity_tier_footprint": 0
      },
      "_links": {
        "self": {
          "href": "/api/storage/volumes/f25c133d-26e8-11ee-a15c-710ff4588dd1"
        }
      }
    },
    {
      "uuid": "f52e8271-26e4-11ee-ae01-6ddd05c78c3c",
      "name": "FsxN_root",
      "svm": {
        "name": "FsxN",
        "uuid": "f4df1cdb-26e4-11ee-a15c-710ff4588dd1",
        "_links": {
          "self": {
            "href": "/api/svm/svms/f4df1cdb-26e4-11ee-a15c-710ff4588dd1"
          }
        }
      },
      "space": {
        "capacity_tier_footprint": 0
      },
      "_links": {
        "self": {
          "href": "/api/storage/volumes/f52e8271-26e4-11ee-ae01-6ddd05c78c3c"
        }
      }
    }
  ],
  "num_records": 5,
  "_links": {
    "self": {
      "href": "/api/storage/volumes?fields=space.capacity_tier_footprint,svm"
    }
  }
}
```

so i tried to modify ```/opt/harvest/conf/volume.yaml``` file but it is too hard..
can you help me?

**Comment by Hardikl** [comment]
@wooyoungAhn 

This is the mapping of the requested ONTAP zapi, cli and rest is as per below.
CLI: `volume show-footprint`
ZAPI: `volume-footprint-get-iter`
REST: `api/storage/volumes`

`volume-footprint-get-iter.footprint-info.volume-blocks-footprint-bin0  --> storage/volumes?fields=space.performance_tier_footprint `
`volume-footprint-get-iter.footprint-info.volume-blocks-footprint-bin1 --> storage/volumes?fields=space.capacity_tier_footprint `

------------------------------------------------------
Below steps are for REST collector volume object.
We are going to create a new template and add it to your `custom.yaml`. In the commands below, Harvest is installed in `/opt/harvest`. 
Adjust as needed.

1. Edit `vi /opt/harvest/conf/rest/custom.yaml`.
2. Add below content to this file. If `custom.yaml` already exists then add the `Volume` line under the `objects:` section.
```
objects:
  Volume:                   custom_volume.yaml
```
3. Create the `custom_volume.yaml` file `vi /opt/harvest/conf/rest/9.12.0/custom_volume.yaml`
4. Copy paste the following into file and save.
```
# This api would provide all volumes(but node).

name:                     Volume
query:                    api/storage/volumes
object:                   volume

counters:
  - ^^name                                        => volume
  - ^^svm.name                                    => svm
  - ^aggregates.#.name                            => aggr
  - ^aggregates.#.uuid                            => aggrUuid        # handled in plugin for flexgroup
  - ^anti_ransomware.state                        => antiRansomwareState
  - ^encryption.enabled                           => isEncrypted
  - ^is_svm_root                                  => svm_root
  - ^snaplock.type                                => snaplock_type
  - ^snapshot_policy.name                         => snapshot_policy
  - ^space.snapshot.autodelete.enabled            => snapshot_autodelete
  - ^state                                        => state
  - ^style                                        => style
  - ^type                                         => type
  - autosize.grow_threshold                       => autosize_grow_threshold_percent
  - autosize.maximum                              => autosize_maximum_size
  - snapshot_count
  - space.afs_total                               => size_total
  - space.available                               => size_available
  - space.capacity_tier_footprint                 => capacity_tier_footprint
  - space.expected_available                      => space_expected_available
  - space.filesystem_size                         => filesystem_size
  - space.logical_space.available                 => space_logical_available
  - space.logical_space.used                      => space_logical_used
  - space.logical_space.used_by_afs               => space_logical_used_by_afs
  - space.logical_space.used_by_snapshots         => space_logical_used_by_snapshots
  - space.logical_space.used_percent              => space_logical_used_percent
  - space.overwrite_reserve                       => overwrite_reserve_total
  - space.overwrite_reserve_used                  => overwrite_reserve_used
  - space.percent_used                            => size_used_percent
  - space.performance_tier_footprint              => performance_tier_footprint
  - space.physical_used                           => space_physical_used
  - space.physical_used_percent                   => space_physical_used_percent
  - space.size                                    => size
  - space.size_available_for_snapshots            => snapshots_size_available
  - space.snapshot.reserve_available              => snapshot_reserve_available
  - space.snapshot.reserve_percent                => snapshot_reserve_percent
  - space.snapshot.reserve_size                   => snapshot_reserve_size
  - space.snapshot.space_used_percent             => snapshot_reserve_used_percent
  - space.snapshot.used                           => snapshots_size_used
  - space.used                                    => size_used
  - hidden_fields:
      - anti_ransomware.state
      - autosize
      - encryption.enabled
      - is_svm_root
      - snaplock.type
      - space

endpoints:
  - query: api/private/cli/volume
    counters:
      - ^^volume
      - ^^vserver                                 => svm
      - ^is_sis_volume                            => is_sis_volume
      - ^nodes                                    => node
      - compression_space_saved                   => sis_compress_saved
      - compression_space_saved_percent           => sis_compress_saved_percent
      - dedupe_space_saved                        => sis_dedup_saved
      - dedupe_space_saved_percent                => sis_dedup_saved_percent
      - files                                     => inode_files_total
      - files_used                                => inode_files_used
      - sis_space_saved                           => sis_total_saved
      - sis_space_saved_percent                   => sis_total_saved_percent

  - query: api/storage/volumes
    counters:
      - ^^name                                    => volume
      - ^^svm.name                                => svm
      - ^clone.parent_snapshot.name               => clone_parent_snapshot
      - ^clone.parent_svm.name                    => clone_parent_svm
      - ^clone.parent_volume.name                 => clone_parent_volume
      - clone.split_estimate                      => clone_split_estimate
      - hidden_fields:
          - clone
      - filter:
          - clone.is_flexclone=true

  - query: api/private/cli/volume/efficiency/stat
    counters:
      - ^^volume
      - ^^vserver                                 => svm
      - num_compress_attempts
      - num_compress_fail
      - filter:
          - privilege_level=diagnostic

plugins:
  - Volume:
      schedule:
        - data: 15m  # should be multiple of poll duration
  - MetricAgent:
      compute_metric:
        - inode_used_percent PERCENT inode_files_used inode_files_total
        - snapshot_reserve_used SUBTRACT snapshot_reserve_size snapshot_reserve_available
        - overwrite_reserve_available SUBTRACT overwrite_reserve_total overwrite_reserve_used
  - LabelAgent:
      exclude_equals:
        - style `flexgroup_constituent`
      value_to_num:
        - new_status state online online `0`
      replace:
        - svm_root root_volume `false` `No`
        - svm_root root_volume `true` `Yes`
      # To prevent visibility of transient volumes, uncomment the following lines
#      exclude_regex:
#        # Exclude SnapProtect/CommVault Intellisnap, Clone volumes have a “_CVclone” suffix
#        - volume `.+_CVclone`
#        # Exclude SnapCenter, Clone volumes have a “DDMMYYhhmmss” suffix
#        - volume `.+(0[1-9]|[12][0-9]|3[01])(0[1-9]|1[012])\d\d[0-9]{6}`
#        # Exclude manually created SnapCreator clones, Clone volumes have a “cl_” prefix and a “_YYYYMMDDhhmmss” suffix
#        - volume `cl_.+_(19|20)\d\d(0[1-9]|1[012])( 0[1-9]|[12][0-9]|3[01])[0-9]{6}`
#        # Exclude SnapDrive/SnapManager, Clone volumes have a “sdw_cl_” prefix
#        - volume `sdw_cl_.+`
#        # Exclude Metadata volumes, CRS volumes in SVM-DR or MetroCluster have a “MDV_CRS_” prefix
#        - volume `MDV_CRS_.+`
#        # Exclude Metadata volumes, Audit volumes have a “MDV_aud_” prefix
#        - volume `MDV_aud_.+`

export_options:
  instance_keys:
    - aggr
    - node
    - style
    - svm
    - volume
  instance_labels:
    - antiRansomwareState
    - clone_parent_snapshot
    - clone_parent_svm
    - clone_parent_volume
    - isEncrypted
    - isHardwareEncrypted
    - is_sis_volume
    - root_volume
    - snaplock_type
    - snapshot_autodelete
    - snapshot_policy
    - state
    - svm_root
    - type
```
5. Restart Harvest
6. After a few minutes you should see data in Prometheus. E.g.
```
% curl -s http://localhost:$promPort/metrics  | grep volume_performance_tier_footprint | head
volume_performance_tier_footprint{datacenter="rest",cluster="umeng-aff300-01-02",aggr="test1",node="umeng-aff300-02",style="flexvol",svm="kk_svm",volume="temp4"} 2383872
volume_performance_tier_footprint{datacenter="rest",cluster="umeng-aff300-01-02",aggr="test1",node="umeng-aff300-02",style="flexvol",svm="astra_304",volume="astra_304_root"} 30236672
volume_performance_tier_footprint{datacenter="rest",cluster="umeng-aff300-01-02",aggr="test1",node="umeng-aff300-02",style="flexvol",svm="astra_301",volume="trident_pvc_9dd385e9_a4e8_4c57_a89e_e02757d20834"} 144662528
volume_performance_tier_footprint{datacenter="rest",cluster="umeng-aff300-01-02",aggr="test1",node="umeng-aff300-02",style="flexvol",svm="astra_301",volume="vol2_dp"} 352256
volume_performance_tier_footprint{datacenter="rest",cluster="umeng-aff300-01-02",aggr="test1",node="umeng-aff300-02",style="flexvol",svm="astra_301",volume="trident_pvc_c6d4c2e5_0be9_4938_b586_9a6a7d4d709d"} 22110208
volume_performance_tier_footprint{datacenter="rest",cluster="umeng-aff300-01-02",aggr="test1",node="umeng-aff300-02",style="flexvol",svm="astra_301",volume="trident_pvc_add8c638_d45f_44b9_bff5_4304b4f605c5"} 1325953024
volume_performance_tier_footprint{datacenter="rest",cluster="umeng-aff300-01-02",aggr="test1",node="umeng-aff300-02",style="flexvol",svm="testsvm_154_22",volume="testvol_154_3"} 2371584
volume_performance_tier_footprint{datacenter="rest",cluster="umeng-aff300-01-02",aggr="test1",node="umeng-aff300-02",style="flexvol",svm="astra_301",volume="vol1"} 2351104
volume_performance_tier_footprint{datacenter="rest",cluster="umeng-aff300-01-02",aggr="test1",node="umeng-aff300-02",style="flexvol",svm="astra_301",volume="trident_pvc_cf16c72a_044e_4e3c_9b04_d2cf06efd0c4"} 39071744
volume_performance_tier_footprint{datacenter="rest",cluster="umeng-aff300-01-02",aggr="test1",node="umeng-aff300-02",style="flexvol",svm="vs_test",volume="new_vol"} 4128768
```

```
 % curl -s http://localhost:$promPort/metrics  | grep volume_capacity_tier_footprint  | head   
volume_capacity_tier_footprint{datacenter="rest",cluster="umeng-aff300-01-02",aggr="test1",node="umeng-aff300-02",style="flexvol",svm="kk_svm",volume="temp4"} 0
volume_capacity_tier_footprint{datacenter="rest",cluster="umeng-aff300-01-02",aggr="test1",node="umeng-aff300-02",style="flexvol",svm="astra_304",volume="astra_304_root"} 0
volume_capacity_tier_footprint{datacenter="rest",cluster="umeng-aff300-01-02",aggr="test1",node="umeng-aff300-02",style="flexvol",svm="astra_301",volume="trident_pvc_9dd385e9_a4e8_4c57_a89e_e02757d20834"} 0
volume_capacity_tier_footprint{datacenter="rest",cluster="umeng-aff300-01-02",aggr="test1",node="umeng-aff300-02",style="flexvol",svm="astra_301",volume="vol2_dp"} 0
volume_capacity_tier_footprint{datacenter="rest",cluster="umeng-aff300-01-02",aggr="test1",node="umeng-aff300-02",style="flexvol",svm="astra_301",volume="trident_pvc_c6d4c2e5_0be9_4938_b586_9a6a7d4d709d"} 0
volume_capacity_tier_footprint{datacenter="rest",cluster="umeng-aff300-01-02",aggr="test1",node="umeng-aff300-02",style="flexvol",svm="astra_301",volume="trident_pvc_add8c638_d45f_44b9_bff5_4304b4f605c5"} 0
volume_capacity_tier_footprint{datacenter="rest",cluster="umeng-aff300-01-02",aggr="test1",node="umeng-aff300-02",style="flexvol",svm="testsvm_154_22",volume="testvol_154_3"} 0
volume_capacity_tier_footprint{datacenter="rest",cluster="umeng-aff300-01-02",aggr="test1",node="umeng-aff300-02",style="flexvol",svm="astra_301",volume="vol1"} 0
volume_capacity_tier_footprint{datacenter="rest",cluster="umeng-aff300-01-02",aggr="test1",node="umeng-aff300-02",style="flexvol",svm="astra_301",volume="trident_pvc_cf16c72a_044e_4e3c_9b04_d2cf06efd0c4"} 0
volume_capacity_tier_footprint{datacenter="rest",cluster="umeng-aff300-01-02",aggr="test1",node="umeng-aff300-02",style="flexvol",svm="vs_test",volume="new_vol"} 0

```
