### DISCUSSION TITLE
Workload changes in Harvest 23.08 version

### DISCUSSION THREAD

**Discussion by rahulguptajss** [NetApp/harvest#2265] [General]
In the upcoming Harvest 23.08 release, changes have been made to the workload templates, as detailed [here](https://github.com/NetApp/harvest/pull/2100#issue-1717241934). If you prefer to revert to the Harvest 23.05 behavior, you will need to use the following templates: `workload_detail_volume.yaml` and `workload_volume.yaml`. Refer [Zapi](https://netapp.github.io/harvest/latest/configure-templates/#how-to-extend-a-zapizapiperf-collectors-existing-object-template) and [Rest](https://netapp.github.io/harvest/latest/configure-templates/#how-to-extend-a-restrestperfems-collectors-existing-object-template) for how to extend templates. The templates will work without changes concerning the template merge for Zapi.

**For ZapiPerf Collector:**
<details>
  <summary>workload_detail_volume.yaml</summary>

```yaml
# object provides latency breakdown per service or delay center per volume
name:                     WorkloadDetailVolume
query:                    workload_detail_volume
object:                   qos_detail_volume

instance_key:             name

# recommended to use a large interval, since workload objects are expensive
client_timeout:           1m30s
workload_class:
  - autovolume
  - user_defined

schedule:
  - counter: 1200s
  - instance: 600s
  - data: 180s

counters:
  - instance_name
  - instance_uuid
  - service_time
  - visits
  - wait_time

resource_map:
  CPU_dblade : backend
  CPU_nblade : frontend
  DELAY_CENTER_CLOUD_IO : cloud
  DELAY_CENTER_CLUSTER_INTERCONNECT : cluster
  DELAY_CENTER_DISK_IO : disk
  DELAY_CENTER_NETWORK : network
  DELAY_CENTER_NVLOG_TRANSFER : nvlog
  DELAY_CENTER_QOS_LIMIT : throttle
  DELAY_CENTER_WAFL_SUSP_OTHER : suspend
  DELAY_CENTER_QOS_MIN_THROUGHPUT: qos_min
  DELAY_CENTER_WAFL_SUSP_CP: cp
  DELAY_CENTER_FLEXCACHE_RAL : flexcache_ral
  DELAY_CENTER_FLEXCACHE_SPINHI : flexcache_spinhi
  DELAY_CENTER_SYNC_REPL : sync_repl
  DELAY_CENTER_COP: cop
  DELAY_CENTER_WAFL_ADM_CTRL: admission
#  CPU_dblade_background :
#  CPU_exempt :
#  CPU_ha :
#  CPU_idle :
#  CPU_kahuna :
#  CPU_network :
#  CPU_protocol :
#  CPU_raid :
#  CPU_wafl_exempt :
#  DISK_SSD_OTHER :

qos_labels:
  - vserver       => svm
  - volume
  - qtree
  - lun
  - file
  - policy-group
  - wid
  - workload-name => workload

export_options:
  instance_keys:
    - file
    - lun
    - policy_group
    - qtree
    - svm
    - volume
    - wid
    - workload
```
</details>

<details>
  <summary>workload_volume.yaml</summary>

```yaml
name:                     WorkloadVolume
query:                    workload_volume
object:                   qos_volume

# recommended to use large interval, since workload objects are expensive
client_timeout:           1m30s
schedule:
  - counter: 1200s
  - instance: 600s
  - data: 180s

instance_key:             name
workload_class:
  - autovolume
  - user_defined

counters:
  - concurrency
  - instance_name
  - instance_uuid
  - latency
  - ops
  - other_ops
  - read_data
  - read_io_type
  - read_latency
  - read_ops
  - sequential_reads
  - sequential_writes
  - total_data
  - write_data
  - write_latency
  - write_ops


override:
  - read_io_type_base: delta

qos_labels:
  - vserver       => svm
  - volume
  - qtree
  - lun
  - file
  - policy-group
  - wid
  - workload-name => workload

export_options:
  instance_keys:
    - file
    - lun
    - policy_group
    - qtree
    - svm
    - volume
    - wid
    - workload
```
</details>

**For RestPerf Collector:**

<details>
  <summary>workload_detail_volume.yaml</summary>

```yaml
# object provides latency breakdown per service or delay center per volume
name:                     WorkloadDetailVolume
query:                    api/cluster/counter/tables/qos_detail_volume
object:                   qos_detail_volume

# recommended to use large interval, since workload objects are expensive
client_timeout:           1m30s
workload_class:
  - autovolume
  - user_defined

schedule:
  - counter: 1200s
  - instance: 600s
  - data: 180s

counters:
  - ^^id
  - service_time
  - visits
  - wait_time

resource_map:
  CPU_dblade : backend
  CPU_nblade : frontend
  DELAY_CENTER_CLOUD_IO : cloud
  DELAY_CENTER_CLUSTER_INTERCONNECT : cluster
  DELAY_CENTER_DISK_IO : disk
  DELAY_CENTER_NETWORK : network
  DELAY_CENTER_NVLOG_TRANSFER : nvlog
  DELAY_CENTER_QOS_LIMIT : throttle
  DELAY_CENTER_WAFL_SUSP_OTHER : suspend
  DELAY_CENTER_QOS_MIN_THROUGHPUT: qos_min
  DELAY_CENTER_WAFL_SUSP_CP: cp
  DELAY_CENTER_FLEXCACHE_RAL: flexcache_ral
  DELAY_CENTER_FLEXCACHE_SPINHI: flexcache_spinhi
  DELAY_CENTER_SYNC_REPL: sync_repl
  DELAY_CENTER_COP: cop
  DELAY_CENTER_WAFL_ADM_CTRL: admission
  # CPU_dblade_background : 
  # CPU_exempt : 
  # CPU_ha : 
  # CPU_idle : 
  # CPU_kahuna : 
  # CPU_network : 
  # CPU_protocol : 
  # CPU_raid : 
  # CPU_wafl_exempt :
  # DISK_SSD_OTHER :

qos_labels:
  - name          => workload
  - svm.name      => svm
  - volume
  - qtree
  - lun
  - file
  - policy.name   => policy_group
  - wid

export_options:
  instance_keys:
    - file
    - lun
    - policy_group
    - qtree
    - svm
    - volume
    - wid
    - workload
```
</details>

<details>
  <summary>workload_volume.yaml</summary>

```yaml
name:                     WorkloadVolume
query:                    api/cluster/counter/tables/qos_volume
object:                   qos_volume

# recommended to use large interval, since workload objects are expensive
client_timeout:           1m30s
workload_class:
  - autovolume
  - user_defined

schedule:
  - counter: 1200s
  - instance: 600s
  - data: 180s

counters:
  - ^^uuid
  - concurrency
  - latency
  - ops
  - read_data
  - read_io_type_percent        => read_io_type
  - read_latency
  - read_ops
  - sequential_reads_percent    => sequential_reads
  - sequential_writes_percent   => sequential_writes
  - total_data
  - write_data
  - write_latency
  - write_ops


override:
  - read_io_type_base: delta

qos_labels:
  - name         => workload
  - svm.name     => svm
  - volume
  - qtree
  - lun
  - file
  - policy.name  => policy_group
  - wid

export_options:
  instance_keys:
    - file
    - lun
    - policy_group
    - qtree
    - svm
    - volume
    - wid
    - workload
```
</details>
