### DISCUSSION TITLE
enable the Rest collector for OntapS3 template

### DISCUSSION THREAD

**Discussion by Garydep** [NetApp/harvest#2369] [Q&A]
Hi all,

I have a requirement to pull stats from a Netapp  S3 bucket.  
I have added the Netapp system running 9.13.1, all dashboards seem to be pulling data fine, except for the s3 Object Storage dashboard, gives the message:

This dashboard requires ONTAP 9.7+. One action is required to use this dashboard:
1. On Harvest, enable the Rest collector for OntapS3 template in your harvest.yml config for configuration metrics

im not entirely sure where i have missed this in the yml file ?

**Comment by cgrinds** [comment]
hi @Garydep that information text is trying to say that those metrics are only available via REST - there is no ZAPI equivalent. That means you need to make sure the REST collector is configured before the ZAPI collector, for the cluster in question. E.g.

Poller u2 will use the Zapi and ZapiPerf collectors, while sar will try Rest and RestPerf collectors first and only if something is not available in one of those two will sar try Zapi and ZapiPerf next. Details about [duplication resolution](https://netapp.github.io/harvest/23.08/architecture/rest-strategy/#can-i-use-the-rest-and-zapi-collectors-at-the-same-time).

For your cluster, you probably want a list of collectors similar to `sar` below.

```yaml
Pollers:
    u2:
        datacenter: dc-1
        addr: 10.193.48.11
        collectors:
            - Zapi
            - ZapiPerf
    
    sar:
        datacenter: dc-1
        addr: 10.193.48.137
        collectors:
            - Rest
            - RestPerf
            - Zapi
            - ZapiPerf
```
