### DISCUSSION TITLE
fci Zapi Perf templates

### DISCUSSION THREAD

**Discussion by rahulguptajss** [NetApp/harvest#2466] [Show and tell]
The `fci_port` object reports counters associated with each adapter port for Fibre Channel connected disks and tapes. Below is the `ZapiPerf` template for this.

```yaml
name:                     FciPort
query:                    fci_port
object:                   fci_port

instance_key:             uuid

counters:
  - adapter_name           => adapter
  - frame_in_count
  - frame_out_count
  - invalid_crc_count
  - instance_name          => port
  - instance_uuid
  - link_failure_count
  - loss_of_sync_count
  - node_name              => node

export_options:
  instance_keys:
    - adapter
    - node
    - port
```

The `fci_itn` object reports counters associated with each initiator port and target port nexus for Fibre Channel connected disks and tapes. Below is the `ZapiPerf` template for this.

```yaml
name:                     FciItn
query:                    fci_itn
object:                   fci_itn

instance_key:             uuid

counters:
  - adapter_name           => adapter
  - frame_in_count
  - frame_out_count
  - invalid_crc_count
  - instance_name          => port
  - instance_uuid
  - link_failure_count
  - loss_of_sync_count
  - node_name              => node

export_options:
  instance_keys:
    - adapter
    - node
    - port
```

[Discord](https://discord.com/channels/855068651522490400/1171192432516415578)
