### DISCUSSION TITLE
Template for Metrocluster Switchover Check

### DISCUSSION THREAD

**Discussion by wagneradrian92** [NetApp/harvest#2517] [Q&A]
hi everyone, 
currently i am trying to create a template zapi or rest to get the information from the scheduled metrocluster switchover -simulate task that can be found under api/cluster/metrocluster/diagnostics

but either with zapi or rest i am not able to get the metrics out. here is an example .yaml file for zapi

```
name:             MetroclusterCheck
query:            metrocluster-check-cluster-get-iter
object:           metrocluster_check

counters:
  - ^^check  => check_name
  - ^result  => check_result

plugins:
  - LabelAgent:
    # metric label zapi_value rest_value `default_value`
    value_to_num:
      - new_result check_result ok ok `0`

export_options:
  instance_keys:
    - check_name
  instance_labels:
    - check_result
```

when i test the object with the following command i get an error that no metrics were found

/bin/harvest start mypoller --foreground --loglevel=2 --collectors Zapi --objects MetroclusterCheck

when i try to get the attributes using the query metrocluster-check-cluster-get-iter i get "request rejected" 
API request rejected => Insufficient privileges: user 'harvest' does not have read access to this resource
doing the same using the rest tool to get the metrics from cluster/metrocluster/diagnostics works

now i am a bit clueless on where to start searching. what do i have to adjust or check to make this work? 

thanks a lot!

**Comment by cgrinds** [comment]
hi @wagneradrian92 

That template does not have any metrics defined in the `counters` section and does not say that collecting only labels is fine. The intent is to prevent you from making a mistake, but seems like the error could be clearer.

Try adding `collect_only_labels: true` at the top-level above export_options, like this:
```yaml
plugins:
  - LabelAgent:
    # metric label zapi_value rest_value `default_value`
    value_to_num:
      - new_result check_result ok ok `0`

collect_only_labels: true

export_options:
  instance_keys:
    - check_name
  instance_labels:
    - check_result
```

The permissions problem is probably because you are using the [least-privilege](https://netapp.github.io/harvest/23.11/prepare-cdot-clusters/#least-privilege-approach) approach to permissions? If so, you can add that permission to your harvest or harvest2-role (depending on what you named the role) like this, at the ONTAP CLI.

```
security login role create -role harvest2-role -access readonly -cmddirname "metrocluster check cluster show"
```

With those two changes how does your Zapi template work?
