### DISCUSSION TITLE
harvest exporter Storagegrid exporting additional metrics

### DISCUSSION THREAD

**Discussion by santosh725** [NetApp/harvest#2540] [General]
hello, 

I run harvest exporter-Storagegrid  on K8. Apart from the two default objects provided I am trying to extract additional metrics.  but unable to do so.  Any help would be greatly appreciated. 

here is how I am setting up my configuration.

default.yaml
/opt/harvest/conf/storagegrid # more default.yaml

collector:         StorageGrid

schedule:
  - data: 5m

objects:
  Tenant:          tenant.yaml
  Prometheus:      storagegrid_metrics.yaml
  Health:          health.yaml

health.yaml

/opt/harvest/conf/storagegrid/11.6.0 # more health.yaml
name:   Health
query:  api/v3/grid/health
object: storagegrid

schedule:
  - data: 1m

counters:
  - alarms.critical               => alarms_critical
  - alarms.major                  => alarms_major
  - alarms.minor                  => alarms_minor
  - nodes.connected               => nodes_connected
  - nodes.administratively-down   => nodes_admin_down
  - nodes.unknown                 => nodes_unknown
 
export_options:
  include_all_labels: true

(hyphen are showing up as bullet points )

**Comment by cgrinds** [comment]
hi @santosh725 this is caused by the StorageGRID collector not supporting the template option `only_cluster_instance`. That parameter is needed when there is no way to identify unique instances from the REST response. That's the case with this API since it returns data like this:
```json
{
  "alarms": {
    "critical": 0,
    "major": 0,
    "minor": 0,
    "notice": 0
  },
  "alerts": {
    "critical": 0,
    "major": 0,
    "minor": 0
  },
  "nodes": {
    "connected": 2,
    "administratively-down": 0,
    "unknown": 3
  }
}
```

Nothing in there about node, cluster, etc. so Harvest was rejecting it. Once I added support for `only_cluster_instance` to the StorageGRID colellector and fixed the template query (`grid/health` instead of `api/v3/grid/health`), I'm able to retrieve the SG metrics like so:

```bash
curl -s 'http://localhost:14002/metrics' | grep -Ev "#|metadata_" | sort

sg_health_alarms_critical{cluster="SG5712FP",datacenter="rtp"} 0
sg_health_alarms_major{cluster="SG5712FP",datacenter="rtp"} 0
sg_health_alarms_minor{cluster="SG5712FP",datacenter="rtp"} 0
sg_health_nodes_admin_down{cluster="SG5712FP",datacenter="rtp"} 0
sg_health_nodes_connected{cluster="SG5712FP",datacenter="rtp"} 2
sg_health_nodes_unknown{cluster="SG5712FP",datacenter="rtp"} 3
```

Here's the template I used,
```yaml
name:     Health
query:    grid/health
object:   sg_health
api:      v3

schedule:
  - data: 1m

counters:
  - alarms.critical             => alarms_critical
  - alarms.major                => alarms_major
  - alarms.minor                => alarms_minor
  - nodes.connected             => nodes_connected
  - nodes.administratively-down => nodes_admin_down
  - nodes.unknown               => nodes_unknown

only_cluster_instance: true
```
