### DISCUSSION TITLE
Add a new REST ISCSISession template

### DISCUSSION THREAD

**Discussion by cgrinds** [NetApp/harvest#2616] [Show and tell]
**Note:** These steps are for NABox.

**Prerequisite:** ssh to NABox via [root](https://nabox.org/documentation/configuration/) 

## Step 1: Create `custom_iscsi.yaml`

Navigate to the `rest` directory:

```bash
cd /opt/harvest2-conf/conf/rest
```

Create custom_iscsi.yaml:

```bash
vi custom_iscsi.yaml
```

Update the file with the following content:

```yaml
objects:
  ISCSISession:
    - iscsi_session.yaml
```

## Step 2: Create `iscsi_session.yaml`

Navigate to the `9.6.0` directory:

```bash
cd /opt/harvest2-conf/conf/rest/9.6.0
```

Create `iscsi_session.yaml`:

```bash
vi iscsi_session.yaml
```

Update the file with the following content:

```yaml
name:               ISCSISession
query:              api/protocols/san/iscsi/sessions
object:             iscsi_session

counters:
  - ^^connections.#.initiator_address.address => initiator_address
  - ^^initiator.name                          => initiator
  - ^^tsih                                    => tsih
  - ^svm.name                                 => svm

plugins:
  - LabelAgent:
      split_regex:
        - initiator `:(.*?)(:|$)` host,

export_options:
  instance_keys:
    - initiator
    - initiator_address
    - tsih
  instance_labels:
    - host
    - svm
```

## Step 3: Restart NABox containers

```
dc restart
```

## Step 4: Validate ISCSISession Collection in Harvest

Wait for at least 1 minute. To ensure that the `Rest:ISCSISession` metrics are being collected, run the following command:

```
dc logs nabox-harvest2 | grep -w 'Rest:ISCSISession'
```

In the screenshot below, you can see that the poller `pstejska_vsim` is collecting `Rest:ISCSISession` instances. 

<img width="1512" alt="image" src="https://github.com/NetApp/harvest/assets/242252/9de3345d-2e13-4488-a225-90f338d61aa5">

## Step 5: Verify ISCSISession Metrics are in Prometheus

Confirm that the ISCSISession metrics are being scraped by Prometheus by running the following query from Prometheus (`https://NABox/prometheus`):

```
iscsi_session_labels
```

<img width="1113" alt="image" src="https://github.com/NetApp/harvest/assets/242252/978b5b1e-2607-4475-ae3c-d56507310d76">

**Comment by chuan137** [comment]
This is great, thank you for working this out. I just see many warnings like,
```
2024-01-31T07:54:11Z WRN rest/rest.go:495 > This instance is already processed. instKey is not unique Poller=stnpca1-bb091 collector=Rest:ISCSISession instKey="iqn.1998-01.com.vmware:node003-bb092-53e3b8e2[\"10.46.69.134\"]"
```
I think for same initiator, only one `tsih` is processed. For our use case, it might be ok. But I guess it would be nicer to poll all the session ids. Otherwise it might be confusing.

**Comment by rahulguptajss** [comment]
@chuan137 See if below template fixes warnings.

```yaml
name:               ISCSISession
query:              api/protocols/san/iscsi/sessions
object:             iscsi_session

counters:
  - ^^connections.#.initiator_address.address => initiator_address
  - ^^initiator.name                          => initiator
  - ^^tsih                                    => tsih
  - ^svm.name                                 => svm

export_options:
  instance_keys:
    - initiator
    - initiator_address
    - tsih
  instance_labels:
    - svm
```

**Reply by chuan137** [reply]
this has fixed the warnings, thank you @rahulguptajs

**Reply by chuan137** [reply]
discussed on the discord, I would like also to split the initiator address to get only the hostname
can you iterate on that pls?

**Comment by rahulguptajss** [comment]
@chuan137 See if below works.

```yaml
name:               ISCSISession
query:              api/protocols/san/iscsi/sessions
object:             iscsi_session

counters:
  - ^^connections.#.initiator_address.address => initiator_address
  - ^^initiator.name                          => initiator
  - ^^tsih                                    => tsih
  - ^svm.name                                 => svm

plugins:
  - LabelAgent:
      split_regex:
        - initiator `:(.*?):` host

export_options:
  instance_keys:
    - initiator
    - initiator_address
    - tsih
  instance_labels:
    - host
    - svm
```

**Comment by rahulguptajss** [comment]
@chuan137 I have updated the regex in the template below to accommodate other naming conventions for the `initiator` name.
Tested with below patterns
```
iqn.1991-05.com.microsoft:abc.netapp.com
iqn.1998-01.com.vmware:abc.netapp.com:1258008586:64
```

```yaml
name:               ISCSISession
query:              api/protocols/san/iscsi/sessions
object:             iscsi_session

counters:
  - ^^connections.#.initiator_address.address => initiator_address
  - ^^initiator.name                          => initiator
  - ^^tsih                                    => tsih
  - ^svm.name                                 => svm

plugins:
  - LabelAgent:
      split_regex:
        - initiator `:(.*?)(:|$)` host,

export_options:
  instance_keys:
    - initiator
    - initiator_address
    - tsih
  instance_labels:
    - host
    - svm
```
