### DISCUSSION TITLE
Add module_fw_revision for shelf and firmware_revision for disk via Rest Collector

### DISCUSSION THREAD

**Discussion by rahulguptajss** [NetApp/harvest#2735] [Show and tell]
Relevant to discord [discussion](https://discord.com/channels/855068651522490400/1216651034622169138)

**Note:** These steps are for a native,rpm,deb installation and applicable to Rest Collector. **In this example, let's assume that Harvest is installed in** `/opt/harvest`

## Step 1: Create `custom.yaml`

Navigate to the `rest` directory:

```bash
cd /opt/harvest/conf/rest
```

Create custom.yaml

```bash
vi custom.yaml
```

Update the file with the following content:

```yaml
objects:
  Disk: custom_disk.yaml
  Shelf: custom_shelf.yaml
```

## Step 2: Create `custom_disk.yaml`

Navigate to the `9.12.0` directory:

```bash
cd /opt/harvest/conf/rest/9.12.0
```

Create `custom_disk.yaml`:

```bash
vi custom_disk.yaml
```

Update the file with the following content:

```yaml

name:             Disk
query:            api/storage/disks
object:           disk

counters:
  - ^^uid                       => uuid
  - ^bay                        => shelf_bay
  - ^container_type
  - ^home_node.name             => owner_node
  - ^firmware_version
  - ^model
  - ^name                       => disk
  - ^node.name                  => node
  - ^node.uuid
  - ^outage.reason              => outage
  - ^serial_number
  - ^shelf.uid                  => shelf
  - ^state
  - bytes_per_sector            => bytes_per_sector
  - sector_count                => sectors
  - stats.average_latency       => stats_average_latency
  - stats.power_on_hours        => power_on_hours
  - usable_size

endpoints:
  - query: api/private/cli/disk
    counters:
      - ^^uid                   => uuid
      - ^type
      - disk_io_kbps_total      => stats_io_kbps
      - sectors_read            => stats_sectors_read
      - sectors_written         => stats_sectors_written

plugins:
  - Disk
  - LabelAgent:
      value_to_num:
        - new_status outage - - `0` #ok_value is empty value, '-' would be converted to blank while processing.
      join:
        - index `_` node,disk
  - MetricAgent:
      compute_metric:
        - uptime MULTIPLY stats.power_on_hours 60 60 #convert to second for zapi parity

export_options:
  instance_keys:
    - disk
    - index
    - node
  instance_labels:
    - container_type
    - failed
    - firmware_version
    - model
    - outage
    - owner_node
    - serial_number
    - shared
    - shelf
    - shelf_bay
    - type
```

## Step 3: Create `custom_shelf.yaml`

Navigate to the `9.12.0` directory:

```bash
cd /opt/harvest/conf/rest/9.12.0
```

Create `custom_shelf.yaml`:

```bash
vi custom_shelf.yaml
```

Update the file with the following content:

```yaml

name:               Shelf
query:              api/storage/shelves
object:             shelf

counters:
  - ^^serial_number       => serial_number
  - ^manufacturer.name    => vendor_name
  - ^model                => model
  - ^module_type          => module_type
  - ^name                 => shelf
  - ^state                => state
  - ^uid                  => uuid
  - disk_count            => disk_count

endpoints:
  - query: api/private/cli/storage/shelf
    counters:
      - ^^serial_number      => serial_number
      - ^op_status           => op_status
      - ^module_fw_revision  => module_fw_revision


plugins:
  - Shelf
  - LabelAgent:
      replace:
        - state state `ok` `online`
      value_to_num:
        - new_status state online online `0`

export_options:
  instance_keys:
    - shelf
  instance_labels:
    - isEmbedded
    - model
    - module_fw_revision
    - module_type
    - op_status
    - serial_number
    - state
    - vendor_name
```

## Step 4: Verify disk_labels metric in Prometheus

<img width="1915" alt="image" src="https://github.com/NetApp/harvest/assets/25551691/c2c99a26-5606-452e-b584-2911c14db63a">

## Step 5: Verify shelf_labels metric in Prometheus

<img width="962" alt="image" src="https://github.com/NetApp/harvest/assets/25551691/085f5607-293a-46a1-a876-7b7fce3aae95">
