### DISCUSSION TITLE
Renaming Harvest Labels Using Prometheus Relabeling Configurations

### DISCUSSION THREAD

**Discussion by rahulguptajss** [NetApp/harvest#2762] [Show and tell]
To duplicate a label in Prometheus, add the `metric_relabel_configs` to the appropriate `scrape_configs` section in your `prometheus.yml`. This allows you to copy the value of an existing label to a new label, while keeping the original label intact.

Here's an example of how to copy the `aggr` label to a new label called `aggregate`:

```yaml
scrape_configs:
  - job_name: 'your_job_name'
    # ... other configuration for the job ...
    metric_relabel_configs:
      - source_labels: [aggr]
        target_label: aggregate
        action: replace    # The 'replace' action will create a new label 'aggregate' with the value of 'aggr' without removing the original 'aggr' label.
```

Be sure to replace `your_job_name` with the actual name of the job for which you want to apply the label duplication. This configuration will result in both `aggr` and `aggregate` labels being present on the metrics, with `aggregate` having the same value as `aggr`.

After updating your `prometheus.yml` file, restart prometheus to apply the changes.

**Example:**

**Before applying `metric_relabel_configs`:**

The original metric looks like this:

```plaintext
aggr_labels{aggr="test1", cluster="abc", datacenter="u2", instance="localhost:12993", is_encrypted="false", job="prometheus", node="abc-1", state="online", type="ssd"}
```

**After applying `metric_relabel_configs`:**

Once you've updated the configuration and restarted Prometheus, the metric will now include both the original `aggr` label and the new `aggregate` label with the same value:

```plaintext
aggr_labels{aggr="test1", aggregate="test1", cluster="abc", datacenter="u2", instance="localhost:12993", is_encrypted="false", job="prometheus", node="abc-1", state="online", type="ssd"}
```

Notice that the metric now has an additional label `aggregate` with the value `"test1"`, which is the same as the `aggr` label's value.

**Note:**

Keep in mind that `metric_relabel_configs` only affects the labels as they are scraped and ingested by Prometheus. It does not change the labels in the historical data already stored in Prometheus. You will only see the new `aggregate` label on data scraped after the configuration change and restart.
