### DISCUSSION TITLE
How to disable system-defined policy workloads in NABox?

### DISCUSSION THREAD

**Discussion by rahulguptajss** [NetApp/harvest#2827] [Show and tell]
Below docs are with reference to [Discord](https://discord.com/channels/855068651522490400/1228194469095018496)

> :warning: **Note:** 
Below steps are applicable for NABox.

**Prerequisite:** ssh to NABox via [root](https://nabox.org/documentation/configuration/) 

## Step 1: Create `custom_my_workload_filter.yaml`

Navigate to the `zapiperf` directory:

```bash
cd /opt/harvest2-conf/conf/zapiperf
```

Create custom_my_workload_filter.yaml:

```bash
vi custom_my_workload_filter.yaml
```

Update the file with the following content:

```yaml
objects:
  Workload:
    - custom_workload_filter.yaml
```

## Step 2: Create `custom_workload_filter.yaml`

Navigate to the `cdot/9.8.0` directory:

```bash
cd /opt/harvest2-conf/conf/zapiperf/cdot/9.8.0
```

Create `custom_workload_filter.yaml`:

```bash
vi custom_workload_filter.yaml
```

Update the file with the following content. 

For more details, refer to the [workload filter templates](https://netapp.github.io/harvest/nightly/configure-zapi/#workload-templates). 

```yaml
counters:
  - filter:
      - workload-class: "user_defined"
```

## Step 3: Restart NABox containers

```
dc restart
```

**Comment by rahulguptajss** [comment]
Below docs are with reference to [Discord](https://discord.com/channels/855068651522490400/1228194469095018496/1228258884486041601)

> :warning: **Note:** 
Below steps are applicable for NABox.

**Prerequisite:** ssh to NABox via [root](https://nabox.org/documentation/configuration/) 

## Step 1: Create `custom_my_workload_volume_filter.yaml`

Navigate to the `zapiperf` directory:

```bash
cd /opt/harvest2-conf/conf/zapiperf
```

Create custom_my_workload_volume_filter.yaml:

```bash
vi custom_my_workload_volume_filter.yaml
```

Update the file with the following content:

```yaml
objects:
  WorkloadVolume:
    - custom_my_workload_volume_filter.yaml
```

## Step 2: Create `custom_my_workload_volume_filter.yaml`

Navigate to the `cdot/9.8.0` directory:

```bash
cd /opt/harvest2-conf/conf/zapiperf/cdot/9.8.0
```

Create `custom_my_workload_volume_filter.yaml`:

```bash
vi custom_my_workload_volume_filter.yaml
```

Update the file with the following content. 

For more details, refer to the [workload filter templates](https://netapp.github.io/harvest/nightly/configure-zapi/#workload-templates). 

```yaml
counters:
  - filter:
      - policy-group: "!User-Best-Effort"
```


## Step 3: Restart NABox containers

```
dc restart
```
