### DISCUSSION TITLE
Quota metrics duplicate removal

### DISCUSSION THREAD

**Discussion by rahulguptajss** [NetApp/harvest#2895] [General]
Starting from Release 24.05, Harvest will no longer publish duplicate quota metrics that were previously maintained for backward compatibility. The following metrics have been removed:

```
qtree_disk_limit
qtree_disk_used
qtree_disk_used_pct_disk_limit
qtree_disk_used_pct_soft_disk_limit
qtree_file_limit
qtree_files_used
qtree_files_used_pct_soft_file_limit
qtree_soft_disk_limit
qtree_soft_file_limit
qtree_threshold
```

Instead, you are advised to use the following metrics, which have been available in previous versions:

```
quota_disk_limit
quota_disk_used
quota_disk_used_pct_disk_limit
quota_disk_used_pct_soft_disk_limit
quota_file_limit
quota_files_used
quota_files_used_pct_soft_file_limit
quota_soft_disk_limit
quota_soft_file_limit
quota_threshold
```

It's likely that you won't need the removed metrics and should instead utilize Harvest's pre-configured qtree templates. If you wish to re-enable these metrics, follow the instructions below.

<details>
<summary><b>ZAPI Steps</b></summary>

1. Create a `custom_qtree.yaml` file in the `conf/zapi/cdot/9.8.0/` directory:

```yaml
plugins:
  - Qtree:
      qtreeMetrics: true
```

2. Validate your configuration with the following command:

```bash
bin/harvest doctor merge --template conf/zapi/cdot/9.8.0/qtree.yaml --with conf/zapi/cdot/9.8.0/custom_qtree.yaml
```

Your configuration should look like this:

```yaml
name: Qtree
query: qtree-list-iter
object: qtree
client_timeout: 2m
counters:
  qtree-info:
    - ^^qtree   => qtree
    - ^^volume
    - ^^vserver => svm
    - ^export-policy
    - ^oplocks
    - ^security-style
    - ^status
collect_only_labels: true
plugins:
  LabelAgent:
    exclude_equals:
      - qtree ``
  Qtree:
    objects:
      - disk-limit
      - disk-used
      - disk-used-pct-disk-limit
      - disk-used-pct-soft-disk-limit
      - disk-used-pct-threshold
      - file-limit
      - files-used
      - files-used-pct-file-limit
      - files-used-pct-soft-file-limit
      - soft-disk-limit
      - soft-file-limit
      - threshold
    quotaType:
      - tree
    qtreeMetrics: true
export_options:
  instance_keys:
    - qtree
    - svm
    - volume
  instance_labels:
    - export_policy
    - oplocks
    - security_style
    - status
```
</details>

<details>
<summary><b>REST Steps</b></summary>

Use the following template for qtree:

```yaml
name:                       Qtree
query:                      api/storage/qtrees
object:                     qtree

client_timeout: 2m

counters:
  - ^^name                => qtree
  - ^^svm.name            => svm
  - ^^volume.name         => volume
  - ^export_policy.name   => export_policy
  - ^security_style       => security_style
  - id                    => id
  - filter:
      - name=!""


endpoints:
  - query: api/private/cli/qtree
    counters:
      - ^^qtree           => qtree
      - ^^volume          => volume
      - ^^vserver         => svm
      - ^oplock_mode      => oplocks
      - ^status           => status
      - filter:
          - qtree=!""
plugins:
  - Qtree:
      qtreeMetrics: true
      quotaType:
        - tree
#        - user
#        - group
  - LabelAgent:
      replace:
        - oplocks oplocks `enable` `enabled`

export_options:
  instance_keys:
    - qtree
    - svm
    - volume
  instance_labels:
    - export_policy
    - oplocks
    - security_style
    - status
```
</details>
