### DISCUSSION TITLE
Enable User/Group Quota in Harvest

### DISCUSSION THREAD

**Discussion by rahulguptajss** [NetApp/harvest#2911] [Show and tell]
**Note:**  
> Below steps are applicable for rpm/deb/native/container installation. **In this example, let's assume that Harvest is installed in** `/opt/harvest`

<details>
<summary><b>ZAPI Steps</b></summary>

1. Navigate to the `zapi` directory:

```bash
cd /opt/harvest/conf/zapi
```

Create `custom.yaml`:

```bash
vi custom.yaml
```

Update the file with the following content:

```yaml
objects:
  Qtree: custom_qtree.yaml
```

2. Create a `custom_qtree.yaml` file in the `/opt/harvest/conf/zapi/cdot/9.8.0/` directory. Update `custom_qtree.yaml` as below.

```yaml
plugins:
  - Qtree:
      quotaType:
        - tree
        - user
        - group
```

3. Restart harvest

</details>

<details>
<summary><b>REST Steps</b></summary>

1. Navigate to the `rest` directory:

```bash
cd /opt/harvest/conf/rest
```

Create `custom.yaml`:

```bash
vi custom.yaml
```

Update the file with the following content:

```yaml
objects:
  Quota:                       custom_quota.yaml
```

2. Create a `custom_quota.yaml` file in the `/opt/harvest/conf/rest/9.12.0/` directory. Update `custom_quota.yaml` as below.

```yaml
name:                       Quota
query:                      api/storage/quota/reports
object:                     quota

client_timeout: 2m

counters:
  - ^^index                       => index
  - ^^volume.uuid                 => volume_uuid
  - ^group.name                   => groupName
  - ^qtree.name                   => qtree
  - ^svm.name                     => svm
  - ^type                         => type
  - ^users.0.id                   => userId
  - ^users.0.name                 => userName
  - ^volume.name                  => volume
  - files.hard_limit              => file_limit
  - files.soft_limit              => soft_file_limit
  - files.used.hard_limit_percent => files_used_pct_file_limit
  - files.used.soft_limit_percent => files_used_pct_soft_file_limit
  - files.used.total              => files_used
  - space.hard_limit              => disk_limit
  - space.soft_limit              => soft_disk_limit
  - space.used.hard_limit_percent => disk_used_pct_disk_limit
  - space.used.soft_limit_percent => disk_used_pct_soft_disk_limit
  - space.used.total              => disk_used
  - filter:
      - show_default_records=false
      - type=tree|user|group

plugins:
  - Quota

export_options:
  instance_keys:
    - group
    - group_id
    - qtree
    - svm
    - type
    - user
    - user_id
    - volume
```

3. Restart harvest

</details>

<details>
<summary><b>NABox4 Steps</b></summary>

> :warning: **Note:**  
Below steps are applicable for NABox and Rest Collector. 

**Prerequisite:** ssh to NABox via [admin](https://nabox.org/documentation/configuration/) 
Create relevant directories if they don't exist. You need to run these commands in `sudo bash`

## Step 1: Create `custom.yaml`

Navigate to the `rest` directory:

```bash
cd /etc/nabox/harvest/user/rest
```

Create custom.yaml:

```bash
vi custom.yaml
```

Update the file with the following content:

```yaml
objects:
  Quota: custom_quota.yaml
```

## Step 2: Create `quota.yaml`

Navigate to the `9.12.0` directory:

```bash
mkdir -p /etc/nabox/harvest/user/rest/9.12.0
cd /etc/nabox/harvest/user/rest/9.12.0
```

Create `custom_quota.yaml`:

```bash
vi custom_quota.yaml
```

Update the file with the following content:

```yaml
name:                       Quota
query:                      api/storage/quota/reports
object:                     quota

client_timeout: 2m

counters:
  - ^^index                       => index
  - ^^volume.uuid                 => volume_uuid
  - ^group.name                   => groupName
  - ^qtree.name                   => qtree
  - ^svm.name                     => svm
  - ^type                         => type
  - ^users.0.id                   => userId
  - ^users.0.name                 => userName
  - ^volume.name                  => volume
  - files.hard_limit              => file_limit
  - files.soft_limit              => soft_file_limit
  - files.used.hard_limit_percent => files_used_pct_file_limit
  - files.used.soft_limit_percent => files_used_pct_soft_file_limit
  - files.used.total              => files_used
  - space.hard_limit              => disk_limit
  - space.soft_limit              => soft_disk_limit
  - space.used.hard_limit_percent => disk_used_pct_disk_limit
  - space.used.soft_limit_percent => disk_used_pct_soft_disk_limit
  - space.used.total              => disk_used
  - filter:
      - show_default_records=false
      - type=tree|user|group

plugins:
  - Quota

export_options:
  instance_keys:
    - group
    - group_id
    - qtree
    - svm
    - type
    - user
    - user_id
    - volume
```

## Step 3: Restart NABox containers

```
dc restart
```
</details>
