### DISCUSSION TITLE
Add a new REST Snapshot template

### DISCUSSION THREAD

**Discussion by cgrinds** [NetApp/harvest#2970] [Show and tell]
**Note:** These steps are for native install.

## Step 1: Create `custom_snapshot.yaml`

Let's assume Harvest is installed in `/opt/harvest` directory. Adjust paths as needed.

Navigate to the `rest` directory:

```bash
cd /opt/harvest/conf/rest
```

Create custom_snapshot.yaml:

```bash
vi custom_snapshot.yaml
```

Update the file with the following content:

```yaml
objects:
  Snapshot:
    - snapshot.yaml
```

## Step 2: Create `snapshot.yaml`

Navigate to the `9.12.0` directory:

```bash
cd /opt/harvest/conf/rest/9.12.0
```

Create `snapshot.yaml`:

```bash
vi snapshot.yaml
```

Update the file with the following content:

```yaml
name:                     Snapshot
query:                    api/private/cli/snapshot
object:                   snapshot
 
counters:
  - ^^snapshot               => snapshot
  - ^^volume                 => volume
  - ^^vserver                => svm
  - create_time(timestamp)   => create_time
  - size                     => size
 
export_options:
  include_all_labels: true
```

## Step 3: Restart Harvest pollers

```
bin/harvest restart
```

## Step 4: Validate Snapshot collection in Harvest

Wait for at least 1 minute. To ensure that the `Rest:Snapshot` metrics are being collected, run the following command:

Substitute the name of your poller for `$poller`

```
grep -w 'Rest:Snapshot' /var/log/harvest/$poller.log
```

In the screenshot below, you can see that the poller `sar` is collecting `Rest:Snapshot` instances. 

<img width="1747" alt="image" src="https://github.com/NetApp/harvest/assets/242252/b0772bc7-01d7-4ca6-acf7-c69da7203208">

## Step 5: Verify Snapshot metrics are in Prometheus

Confirm that the Snapshot metrics are being scraped by Prometheus by running the following query from Prometheus:

```
snapshot_size
```

<img width="1561" alt="image" src="https://github.com/NetApp/harvest/assets/242252/78e98e5a-c3af-4c52-826f-e7a97cfcfaf3">
