### DISCUSSION TITLE
NetApp Harvest configuration

### DISCUSSION THREAD

**Discussion by chaithi88** [NetApp/harvest#2994] [General]
Hi,
I am working on setting up Netapp harvest using Prometheus and I am running into an issue where I am not able to see the NetApp filer included in the pollers is not discovered on the Prometheus targets. Can you please help review config and let me know where/what the issue is? Appreciate your help. Thanks
 

root@ntap-harvest-poc: ~# cat /opt/harvest/harvest.yml
version: 1

logging:
  level: debug
  file: /opt/harvest/harvest.log
Exporters:
  prometheus:
    exporter: Prometheus
    local_http_addr: 0.0.0.0
    port: 12990

Defaults:
  collectors:
    - Zapi
    - ZapiPerf
    - Rest
    - RestPerf
    - Ems
  use_insecure_tls: true

Pollers:
  unix:
    datacenter: local
    addr: localhost
    collectors:
      - Unix
    exporters:
      - prometheus

  cluster-01:
    datacenter: IAD1
    addr: 10.x.x.x
    auth_style: basic_auth
    username: admin
    password: xxxxxxx
    use_insecure_tls: true
    exporters:
      - prometheus
    schedule:
      1: 1m   # example to run every minute

**Comment by cgrinds** [comment]
Not sure how you installed Harvest, but can you share your log file?
It should tell us what’s going on.
https://netapp.github.io/harvest/nightly/help/log-collection/
 
We have a `bin/harvest doctor` command that is handy to validate your harvest.yml file. It will point out common errors.
 
If I run “harvest doctor” with your config file it points out a problem with your Prometheus exporters, which I’ve pasted here:
 
```
Error: Multiple pollers export to the same PromPort
  Each poller should export to a unique Prometheus exporter or use PortRange. Change the following pollers to use unique exporters:
  pollers [unix, cluster-01] export to the same static PrometheusExporter: [prometheus]
 ```

When using a [Prometheus exporter](https://netapp.github.io/harvest/nightly/prometheus-exporter/), each poller needs its own unique port. In your case, you are attempting to make two different pollers (unix and cluster-01) use the same port. That won’t work, and the log files should say that.
 
You can create another Prometheus exporter or comment out the unix poller. Below, I've pasted a new harvest.yml with an additional Prometheus exporter that should work for you. If you decide to use the attached harvest.yml, you’ll need to update your [Prometheus scrape target](https://netapp.github.io/harvest/nightly/prometheus-exporter/#static-scrape-targets) to include the unix poller too.
 
```yaml
Exporters:
    prometheus1:
        exporter: Prometheus
        local_http_addr: 0.0.0.0
        port: 12990
    prometheus2:
        exporter: Prometheus
        local_http_addr: 0.0.0.0
        port: 12991   
Defaults:
    collectors:
        - Zapi
        - ZapiPerf
        - Rest
        - RestPerf
        - Ems
    use_insecure_tls: true
Pollers:
    unix:
        datacenter: local
        collectors:
            - Unix
        exporters:
            - prometheus2
    cluster-01:
        datacenter: IAD1
        addr: -REDACTED-
        auth_style: basic_auth
        username: -REDACTED-
        password: -REDACTED-
        use_insecure_tls: true
        exporters:
            - prometheus1
```
