### DISCUSSION TITLE
How to obtain user/group quota by rest? I can get these data from storage/quota/reports,but cannot get them from metrics?

### DISCUSSION THREAD

**Discussion by qrm1982** [NetApp/harvest#3024] [General]
Hello,How to obtain user/group quota by rest? I can get these data from storage/quota/reports,but cannot get them from metrics?

**Comment by qrm1982** [comment]
We cannot see the yaml file config of storage/quota/reports.

**Comment by cgrinds** [comment]
Hi @qrm1982 which version of Harvest are you using and how did you install it? 

The Qtree template `conf/rest/9.12.0/qtree.yaml` has a Qtree plugin that includes tree, user, and group types. Sounds like you want to enable user and group. See if these instructions help https://github.com/NetApp/harvest/discussions/2911.

**Reply by qrm1982** [reply]
Morning cgrinds,our harvest version is 24.06.24-nightly and we use RPM to install. About help #2911,Rest steps use the Zapi yaml,is it right? And we have about 400 users,are there too big to download?We need to get all users and gruops quota .

**Reply by qrm1982** [reply]
We use Rest to get data, other data has downloaded,but only user/group quota cannot get. We can access these data from metrics.

**Reply by rahulguptajss** [reply]
@qrm1982 #2911 lists steps for both ZAPI and REST templates. If you are using REST, you only need to follow the steps for REST. I have copied the same as below.

**In this example, let's assume that Harvest is installed in** `/opt/harvest`

1. Navigate to the `rest` directory:

```bash
cd /opt/harvest/conf/rest
```

Create `custom.yaml`:

```bash
vi custom.yaml
```

Update the file with the following content:

```yaml
objects:
  Qtree: custom_qtree.yaml
```

2. Create a `custom_qtree.yaml` file in the `/opt/harvest/conf/rest/9.12.0/` directory. Update `custom_qtree.yaml` as below.

```yaml
name:                       Qtree
query:                      api/storage/qtrees
object:                     qtree

client_timeout: 2m

counters:
  - ^^name                => qtree
  - ^^svm.name            => svm
  - ^^volume.name         => volume
  - ^export_policy.name   => export_policy
  - ^security_style       => security_style
  - id                    => id
  - filter:
      - name=!""


endpoints:
  - query: api/private/cli/qtree
    counters:
      - ^^qtree           => qtree
      - ^^volume          => volume
      - ^^vserver         => svm
      - ^oplock_mode      => oplocks
      - ^status           => status
      - filter:
          - qtree=!""
plugins:
  - Qtree:
      quotaType:
        - tree
        - user
        - group
  - LabelAgent:
      replace:
        - oplocks oplocks `enable` `enabled`

export_options:
  instance_keys:
    - qtree
    - svm
    - volume
  instance_labels:
    - export_policy
    - oplocks
    - security_style
    - status
```

3. Restart harvest

**Reply by rahulguptajss** [reply]
Regarding the 400 users, you can use the following curl command with your cluster to check the number of records and the time taken. This will give us an idea of the amount of data we are looking at.

Please note that the `USERNAME`, `PASSWORD`, `URL` should be replaced with the appropriate credentials.

```
curl -s -k -u USERNAME:PASSWORD 'https://URL/api/storage/quota/reports?return_records=true&fields=*&return_unmatched_nested_array_objects=true&show_default_records=false&type=tree|user|group'
```

**Reply by qrm1982** [reply]
Hi,rahulguptajss
     We can get the data with your command very fast. But in harvest metrics,we only get a wrong message as 'failed to fetch data:error making request StatusCode: 400,Message: expected argument name.,Code: 262179 ,Target: name ,API: /api/storage/quota/reports?fields......'

**Reply by rahulguptajss** [reply]
@qrm1982 I suspect there may be an issue with the template copy, as it seems to work fine for me. Could you try running the following command from the Harvest home directory and share the output? 

Please replace `POLLER` with the appropriate value from your Harvest configuration.

```sh
./bin/poller --poller POLLER --config harvest.yml --collectors Rest --objects Qtree --loglevel 1
```

**Reply by qrm1982** [reply]
Hi rahulguptajss,

   I run your command and  jam now, attached is result.

![error](https://github.com/NetApp/harvest/assets/109878489/a2310a12-2824-4db8-9766-fa20f9f52813)

**Reply by rahulguptajss** [reply]
Based on the logs, it appears that no template was selected for running the Qtree object.

Could you run the following commands from the Harvest home directory and share the output?

```sh
find . -name "qtree.yaml"
```

```sh
cat conf/rest/default.yaml
```

```sh
cat conf/rest/custom.yaml
```

**Reply by qrm1982** [reply]
Hi rahulguptajss,
     Attached is FYI！
![default](https://github.com/NetApp/harvest/assets/109878489/4f7e3784-a7b5-44d9-9489-619f6b01e088)
![find](https://github.com/NetApp/harvest/assets/109878489/aeb76034-b7a9-4254-ad42-60046c71a47d)

**Reply by cgrinds** [reply]
Can you edit your custom.yaml and add a space between `Qtree:` and the template name, like so:

```yaml
objects:
  Qtree: custom_qtree.yaml
```

and then try this command again?
```bash
./bin/poller --poller POLLER --config harvest.yml --collectors Rest --objects Qtree --loglevel 1
```

**Reply by qrm1982** [reply]
Hi cgrinds,
    Still error as attached.

![error](https://github.com/NetApp/harvest/assets/109878489/7892539f-485d-4a36-9fd8-adb5838c6e36)

**Reply by rahulguptajss** [reply]
Can you create a `custom_qtree.yaml` file in the `/opt/harvest/conf/rest/cdot/9.12.0/` directory. Note that there were some previous steps involving the zapi path Rest, which may have caused confusion. I have edited the original post to clarify this.

**Reply by qrm1982** [reply]
Hi rahulguptajss,
   As you know,there is no cdot in rest path at first, your mean we need create a new folder cdot/9.12.0?

**Reply by rahulguptajss** [reply]
Correct `/opt/harvest/conf/rest/9.12.0/`

**Reply by qrm1982** [reply]
Hi rahulguptajss,
        still as attached status.
![error](https://github.com/NetApp/harvest/assets/109878489/a61ae2be-4611-40f6-aaab-1bbacdbd090f)

**Reply by qrm1982** [reply]
Hi all,
    Is this message normal?  "no exports initialized,continuing without exporters ..."

**Reply by cgrinds** [reply]
Progress! The template is being loaded now as seen by this line
> best-fit template Poller=ntap-01 collector=Rest:Qtreecollector=Rest:Qtree jitter=none path=conf/rest/9.12.0/custom _qtree.yaml v=9.9.1

Looks like you have an error in your harvest.yml file. 
<img width="1157" alt="image" src="https://github.com/NetApp/harvest/assets/242252/564fb039-3d92-420f-9ba5-63a59841dc0e">

Can you run `bin/harvest doctor` and share the results?

**Reply by qrm1982** [reply]
Morning cgrinds,

    Result is attached.
![error](https://github.com/NetApp/harvest/assets/109878489/2ae91e47-5ccd-482b-951e-ae01d7671bfb)

**Reply by rahulguptajss** [reply]
Thanks, @qrm1982, for the information. Based on the logs, it appears that there are no qtrees on this cluster.

Could you run the following `curl` command to check for any results? If possible, try this on a cluster that has records, it should work now. Alternatively, you can also run Harvest as usual, and any cluster with quota trees, users, or groups should start populating.

Please replace `USERNAME`, `PASSWORD`, and `URL` with the appropriate credentials:

```sh
curl -s -k -u USERNAME:PASSWORD 'https://URL/api/storage/qtrees?return_records=true&fields=*&name=!""'
```

**Reply by qrm1982** [reply]
Hi rahulguptajss,
      It shows attached content after exec your command.

![error](https://github.com/NetApp/harvest/assets/109878489/b590537d-4159-45ab-842c-baf5fd124a07)

**Reply by qrm1982** [reply]
It can show all the data after exec "curl -s -k -u USERNAME:PASSWORD 'https://URL/api/storage/quota/reports?return_records=true&fields=*&return_unmatched_nested_array_objects=true&show_default_records=false&type=tree|user|group':.

**Reply by qrm1982** [reply]
What data we need is from api/storage/quota/report,but not from api/storage/trees,there are different as attached.

![data](https://github.com/NetApp/harvest/assets/109878489/5ea623cc-d29c-4aee-b3a9-f1d649aea3c7)

**Reply by qrm1982** [reply]
Here is the discuss about it .https://community.netapp.com/t5/Active-IQ-Unified-Manager-Discussions/User-Quotas-in-Netapp-Harvest/td-p/115210

**Reply by rahulguptajss** [reply]
@qrm1982 The provided link refers to Harvest 1.6. In Harvest 2, quotas are collected exclusively through the Qtree template, which utilizes a plugin called Qtree.

To clarify, are you not receiving any Qtree data when executing the following `curl` command? This could explain why the plugin isn't being invoked. If no records are returned from this call, the plugin is never reached, and quotas are not collected.

```bash
curl -s -k -u USERNAME:PASSWORD 'https://URL/api/storage/qtrees?return_records=true&fields=*&name=!""'
```


Do you receive any Qtree data with the following `curl` command?

```bash
curl -s -k -u USERNAME:PASSWORD 'https://URL/api/storage/qtrees?return_records=true&fields=*'
```

If you do, Could you try using the following template in `custom_qtree.yaml` and then run the CLI command. Could you share the logs from that execution?

```bash
./bin/poller --poller POLLER --config harvest.yml --collectors Rest --objects Qtree --loglevel 1
```


```yaml
name:                       Qtree
query:                      api/storage/qtrees
object:                     qtree

client_timeout: 2m

counters:
  - ^^name                => qtree
  - ^^svm.name            => svm
  - ^^volume.name         => volume
  - ^export_policy.name   => export_policy
  - ^security_style       => security_style
  - id                    => id


endpoints:
  - query: api/private/cli/qtree
    counters:
      - ^^qtree           => qtree
      - ^^volume          => volume
      - ^^vserver         => svm
      - ^oplock_mode      => oplocks
      - ^status           => status

plugins:
  - Qtree:
      quotaType:
        - tree
        - user
        - group
  - LabelAgent:
      replace:
        - oplocks oplocks `enable` `enabled`

export_options:
  instance_keys:
    - qtree
    - svm
    - volume
  instance_labels:
    - export_policy
    - oplocks
    - security_style
    - status
```

**Reply by qrm1982** [reply]
Hi rahulguptajss,
     I will show you one by one.

**Comment by qrm1982** [comment]


**Reply by qrm1982** [reply]
With curl -s -k -u USERNAME:PASSWORD 'https://URL/api/storage/qtrees?return_records=true&fields=*'

![2](https://github.com/NetApp/harvest/assets/109878489/95d91b08-0b2e-40dd-bcf6-fb2a0f4ccbcd)

**Reply by qrm1982** [reply]
With ./bin/poller --poller POLLER --config harvest.yml --collectors Rest --objects Qtree --loglevel 1

![3](https://github.com/NetApp/harvest/assets/109878489/0ab33d69-5a92-4e91-a8e4-dac1351bb37f)

**Reply by qrm1982** [reply]
Also with curl -s -k -u USERNAME:PASSWORD 'https://URL/api/storage/quota/reports?return_records=true&fields=*&return_unmatched_nested_array_objects=true&show_default_records=false&type=tree|user|group'

![4](https://github.com/NetApp/harvest/assets/109878489/8790fc2a-001e-404a-80fb-599d42b4c485)

**Reply by rahulguptajss** [reply]
@qrm1982 Have you updated the new `custom_qtree.yaml` template as I shared earlier? If so, could you please share your version of the `custom_qtree.yaml` file?

**Reply by qrm1982** [reply]
Yes,please have a look.

![5](https://github.com/NetApp/harvest/assets/109878489/3425cb5b-13eb-48b7-a930-f1f4b041c9b4)

**Reply by rahulguptajss** [reply]
Could you update this file to have below content and then try again with harvest CLI

```yaml
name:                       Qtree
query:                      api/storage/qtrees
object:                     qtree

client_timeout: 2m

counters:
  - ^^name                => qtree
  - ^^svm.name            => svm
  - ^^volume.name         => volume
  - ^export_policy.name   => export_policy
  - ^security_style       => security_style
  - id                    => id


endpoints:
  - query: api/private/cli/qtree
    counters:
      - ^^qtree           => qtree
      - ^^volume          => volume
      - ^^vserver         => svm
      - ^oplock_mode      => oplocks
      - ^status           => status

plugins:
  - Qtree:
      quotaType:
        - tree
        - user
        - group
  - LabelAgent:
      replace:
        - oplocks oplocks `enable` `enabled`

export_options:
  instance_keys:
    - qtree
    - svm
    - volume
  instance_labels:
    - export_policy
    - oplocks
    - security_style
    - status
 ```
