### DISCUSSION TITLE
Collect quotas from a cluster that has no qtrees

### DISCUSSION THREAD

**Discussion by Hardikl** [NetApp/harvest#3057] [Show and tell]
#### This changes would be needed only for Rest collector.
Below is the out-of-the-box template with the `filter` lines removed

<details>
<summary>Native</summary>

> :warning: **Note:**  
Below steps are applicable for native install. 

## Step 1: Create `custom.yaml`

Let's assume Harvest is installed in `/opt/harvest` directory. Adjust paths as needed.

Navigate to the `rest` directory:

```bash
cd /opt/harvest/conf/rest
```

Create custom.yaml:

```bash
vi custom.yaml
```

Update the file with the following content:

```yaml
objects:
  Qtree:  custom_qtree.yaml
```

## Step 2: Create `custom_qtree.yaml`

Navigate to the `9.12.0` directory:

```bash
cd /opt/harvest/conf/rest/9.12.0
```

Create `custom_qtree.yaml`:

```bash
vi custom_qtree.yaml
```

Update the file with the following content:
```yaml
name:                       Qtree
query:                      api/storage/qtrees
object:                     qtree

client_timeout: 2m

counters:
  - ^^name                => qtree
  - ^^svm.name            => svm
  - ^^volume.name         => volume
  - ^export_policy.name   => export_policy
  - ^security_style       => security_style
  - id                    => id

endpoints:
  - query: api/private/cli/qtree
    counters:
      - ^^qtree           => qtree
      - ^^volume          => volume
      - ^^vserver         => svm
      - ^oplock_mode      => oplocks
      - ^status           => status

plugins:
  - Qtree:
      quotaType:
        - tree
#        - user
#        - group
  - LabelAgent:
      replace:
        - oplocks oplocks `enable` `enabled`

export_options:
  instance_keys:
    - qtree
    - svm
    - volume
  instance_labels:
    - export_policy
    - oplocks
    - security_style
    - status
```

## Step 3: Restart Harvest pollers

```
bin/harvest restart
```
</details>

<details>
<summary>NABox4</summary>

> :warning: **Note:**  
Below steps are applicable for NABox and Rest Collector. 

**Prerequisite:** ssh to NABox via [root](https://nabox.org/documentation/configuration/) 

## Step 1: Create `custom.yaml`

Navigate to the `rest` directory:

```bash
cd /etc/nabox/harvest/user/rest
```

Create custom.yaml:

```bash
vi custom.yaml
```

Update the file with the following content:

```yaml
objects:
  Qtree:
    - qtree.yaml
```

## Step 2: Create `qtree.yaml`

Navigate to the `9.12.0` directory:

```bash
cd /etc/nabox/harvest/user/rest/9.12.0
```

Create `qtree.yaml`:

```bash
vi qtree.yaml
```

Update the file with the following content:

```yaml
name:                       Qtree
query:                      api/storage/qtrees
object:                     qtree

client_timeout: 2m

counters:
  - ^^name                => qtree
  - ^^svm.name            => svm
  - ^^volume.name         => volume
  - ^export_policy.name   => export_policy
  - ^security_style       => security_style
  - id                    => id

endpoints:
  - query: api/private/cli/qtree
    counters:
      - ^^qtree           => qtree
      - ^^volume          => volume
      - ^^vserver         => svm
      - ^oplock_mode      => oplocks
      - ^status           => status

plugins:
  - Qtree:
      quotaType:
        - tree
#        - user
#        - group
  - LabelAgent:
      replace:
        - oplocks oplocks `enable` `enabled`

export_options:
  instance_keys:
    - qtree
    - svm
    - volume
  instance_labels:
    - export_policy
    - oplocks
    - security_style
    - status
```

## Step 3: Restart NABox containers

```
dc restart
```
</details>

Customer discussion here: https://github.com/NetApp/harvest/discussions/3024
