### DISCUSSION TITLE
Enabling and Configuring NFS Clients and iSCSI Sessions Tracking in Harvest

### DISCUSSION THREAD

**Discussion by rahulguptajss** [NetApp/harvest#3155] [Show and tell]
**Note:** Below steps are applicable to `Rest` Collector. NFS clients template below provides data for clients active in the last 48 hours. If you need real-time data, you will need to add a filter for `idle_duration` in the template.
 

<details>
<summary><b>NABox4</b></summary>

> :warning: **Note:**  
**Prerequisite:** ssh to NABox via [admin](https://nabox.org/documentation/configuration/) 
Create relevant directories if they don't exist. You need to run these commands in `sudo bash`

1. Navigate to the `rest` directory:

```bash
mkdir -p  /etc/nabox/harvest/user/rest
cd /etc/nabox/harvest/user/rest
```

Create `custom.yaml`:

```bash
vi custom.yaml
```

Update the file with the following content:

```yaml
objects:
  ISCSISessions: custom_iscsi_sessions.yaml
  NFSClientsConnection: custom_nfs_clients_connection.yaml
```

2. Create a `custom_iscsi_sessions.yaml` file in the `/etc/nabox/harvest/user/rest/9.12.0` directory. Update `custom_iscsi_sessions.yaml` as below.

```yaml
name:             ISCSISessions
query:            api/protocols/san/iscsi/sessions
object:           iscsi_sessions

counters:
  - ^^tsih                         => tsih
  - ^^target_portal_group          => target_portal_group
  - ^^initiator.name               => initiator
  - ^^isid                         => isid
  - ^^svm.name                     => svm

plugins:
  - LabelAgent:
      value_to_num_regex:
        - count initiator .* .* `0`
  - Aggregator:
      # plugin will create summary/average for each object
      # any names after the object names will be treated as
      # label names that will be added to instances
      - svm

# only export node/aggr aggregations from plugin
# set this true or comment, to get data for each lock
export_data: false
```

3. Create a `custom_nfs_clients_connection.yaml` file in the `/etc/nabox/harvest/user/rest/9.12.0` directory. Update `custom_nfs_clients_connection.yaml` as below.

```yaml
name:             NFSClientsConnection
query:            api/protocols/nfs/connected-clients
object:           nfs_clients

counters:
  - ^^client_ip                    => client_ip
  - ^^node.name                    => node
  - ^^protocol                     => protocol
  - ^^server_ip                    => server_ip
  - ^^svm.name                     => svm
  - ^^volume.name                  => volume

plugins:
  - LabelAgent:
      value_to_num_regex:
        - count protocol .* .* `0`
  - Aggregator:
      # plugin will create summary/average for each object
      # any names after the object names will be treated as
      # label names that will be added to instances
      - node
      # - svm
      # - volume

# only export node/aggr aggregations from plugin
# set this true or comment, to get data for each lock
export_data: false
```

4. Restart harvest
```sh
dc restart
```

</details>

<details>
<summary><b>rpm/deb/native/container</b></summary>

**Note:**  
> Below steps are applicable for rpm/deb/native/container installation. **In this example, let's assume that Harvest is installed in** `/opt/harvest`

1. Navigate to the `rest` directory:

```bash
cd /opt/harvest/conf/rest
```

Create `custom.yaml`:

```bash
vi custom.yaml
```

Update the file with the following content:

```yaml
objects:
  ISCSISessions: custom_iscsi_sessions.yaml
  NFSClientsConnection: custom_nfs_clients_connection.yaml
```

2. Create a `custom_iscsi_sessions.yaml` file in the `/opt/harvest/conf/rest/9.12.0/` directory. Update `custom_iscsi_sessions.yaml` as below.

```yaml
name:             ISCSISessions
query:            api/protocols/san/iscsi/sessions
object:           iscsi_sessions

counters:
  - ^^tsih                         => tsih
  - ^^target_portal_group          => target_portal_group
  - ^^initiator.name               => initiator
  - ^^isid                         => isid
  - ^^svm.name                     => svm

plugins:
  - LabelAgent:
      value_to_num_regex:
        - count initiator .* .* `0`
  - Aggregator:
      # plugin will create summary/average for each object
      # any names after the object names will be treated as
      # label names that will be added to instances
      - svm

# only export node/aggr aggregations from plugin
# set this true or comment, to get data for each lock
export_data: false
```

3. Create a `custom_nfs_clients_connection.yaml` file in the `/opt/harvest/conf/rest/9.12.0/` directory. Update `custom_nfs_clients_connection.yaml` as below.

```yaml
name:             NFSClientsConnection
query:            api/protocols/nfs/connected-clients
object:           nfs_clients

counters:
  - ^^client_ip                    => client_ip
  - ^^node.name                    => node
  - ^^protocol                     => protocol
  - ^^server_ip                    => server_ip
  - ^^svm.name                     => svm
  - ^^volume.name                  => volume

plugins:
  - LabelAgent:
      value_to_num_regex:
        - count protocol .* .* `0`
  - Aggregator:
      # plugin will create summary/average for each object
      # any names after the object names will be treated as
      # label names that will be added to instances
      - node
      # - svm
      # - volume

# only export node/aggr aggregations from plugin
# set this true or comment, to get data for each lock
export_data: false
```

4. Restart harvest

</details>

You should see relevant data for NFS Clients and iSCSI Sessions as below in prometheus for metrics `svm_iscsi_sessions_count` and `node_nfs_clients_count`

<img width="1373" alt="image" src="https://github.com/user-attachments/assets/b374145a-af70-4da6-b569-cc5604a81be9">
