### DISCUSSION TITLE
NAbox v4 - Dashboard for FC port status and alerting

### DISCUSSION THREAD

**Discussion by dphan85** [NetApp/harvest#3206] [Q&A] [answered]
Hi All,

I am new in the storage area and with netapp. The team just installed NaBox v4, I notice under one of the Cdot-Network dashboards it has FC information. However I am trying to add the status of the FC itself if it's in an Online/Offline status. I also want to create an alert when a FC go from Online to Offline. 

Can someone help me with how I can archive this?

Below is the version that was deployed as part of the installation.

NAbox v4.0.7 (08fc923)
Harvest 24.08.0
Grafana 11.2.0

**Comment by cgrinds** [comment, marked as answer]
hi @dphan85 

What version of ONTAP are you running?

Do you see the `FC ports with Fabric detail` panel when you expand the `FibreChannel` row like shown below? You will need the REST collector enabled since this table is populated with metrics collected from that collector.

<img width="1002" alt="image" src="https://github.com/user-attachments/assets/b56556fd-087a-4223-9b23-b4f9181a8400">

The `FC ports with Fabric detail` has a `State` row. Does that have the info you need? 

[ONTAP returns](https://docs.netapp.com/us-en/ontap-restapi/ontap/swagger-ui/index.html#model-fc_port) an enum for that field and it will have one of `[startup, link_not_connected, online, link_disconnected, offlined_by_user, offlined_by_system, node_offline, unknown]`

<img width="1070" alt="image" src="https://github.com/user-attachments/assets/c3622790-5c1f-479e-a3ad-bc04c969fe8d">

In terms of creating an alert, try adding something like this to your `rules` section of your `alert_rules.yml`.

```yaml
  - alert: FC port is not online
    expr: fcp_labels{state!="online"} == 1
    for: 5m
    labels:
      severity: "critical"
    annotations:
      summary: "FC port [{{ $labels.port }}] state is [{{ $labels.state }}]"
      description: "FC port [{{ $labels.port }}] state is [{{ $labels.state }}]"
```
