### DISCUSSION TITLE
Performance metrics not being collected

### DISCUSSION THREAD

**Discussion by gaur-piyush** [NetApp/harvest#3336] [Q&A]
Hi Team,

We are using Harvest to collect ONTAP metrics. However, the performance metrics aren't being collected. I have already enabled the collector in the configuration. 

Below is the configuration yaml. 

```
harvest.yml: |
     Exporters:
        prometheus1:
          exporter: Prometheus
          port_range: 12900-14000
          add_meta_tags: false
     Defaults:
       use_insecure_tls: true
       perfer_zapi: true
     Pollers:
       harvest:
         datacenter: {{ .Values.datacenter }}
         addr: "{{ `{{ .pvt_ip }}` }}"
         username: "{{ `{{ .username }}` }}"
         password: "{{ `{{ .password }}` }}"
         collectors:
         - Rest
         - Ems
         exporters:
         - prometheus1
```

Example of missing metrics

https://netapp.github.io/harvest/23.11/ontap-metrics/#node_volume_avg_latency

Please let me know if we need to add additional configuration for it. 

Regards,
Piyush

**Comment by rahulguptajss** [comment]
@gaur-piyush You should also enable `RestPerf` collector which is meant for performance metrics.
https://netapp.github.io/harvest/24.11.1/configure-rest/#restperf-collector

**Reply by gaur-piyush** [reply]
> @gaur-piyush You should also enable `RestPerf` collector which is meant for performance metrics. https://netapp.github.io/harvest/24.11.1/configure-rest/#restperf-collector

Sorry, this is enabled. Below is the applied configuration.

```
apiVersion: v1
data:
  harvest.yml: |
    Exporters:
       prometheus1:
         exporter: Prometheus
         port_range: 12900-14000
         add_meta_tags: false
    Defaults:
      use_insecure_tls: true
      perfer_zapi: true
    Pollers:
      harvest:
        datacenter: us-oma
        addr: "{{ .pvt_ip }}"
        username: "{{ .username }}"
        password: "{{ .password }}"
        collectors:
        - Rest
        - Ems
        - RestPerf
        - ZapiPerf
        - Zapi
        exporters:
        - prometheus1
```
