### DISCUSSION TITLE
Enable SMB2 histogram metrics in NABox4

### DISCUSSION THREAD

**Discussion by rahulguptajss** [NetApp/harvest#3344] [Show and tell]
Below steps are applicable for NABox4

<details>
<summary><b>RestPerf</b></summary>

> :warning: **Note:**  
**Prerequisite:** ssh to NABox via [admin](https://nabox.org/documentation/configuration/) 
Create relevant directories if they don't exist. You need to run these commands in `sudo bash`

1. Navigate to the `restperf` directory. 

```bash
cd /etc/nabox/harvest/user/restperf
```

Create `custom.yaml`:

```bash
vi custom.yaml
```

Update the file with the following content:

```yaml
objects:
  SMB2: custom_smb2.yaml
```

2. Create a `custom_smb2.yaml` file in the `/etc/nabox/harvest/user/restperf/9.14.1` directory. Update `custom_smb2.yaml` as below.

```yaml
name:                     SMB2
query:                    api/cluster/counter/tables/smb2
object:                   smb2

counters:
  - ^^id
  - ^node.name                         => node
  - ^svm.name                          => svm
  - close_latency
  - close_ops
  - create_latency
  - create_ops
  - lock_latency
  - lock_ops
  - negotiate_latency
  - negotiate_ops
  - oplock_break_latency
  - oplock_break_ops
  - query_directory_latency
  - query_directory_ops
  - query_info_latency
  - query_info_ops
  - read_latency
  - read_ops
  - session_setup_latency
  - session_setup_ops
  - set_info_latency
  - set_info_ops
  - tree_connect_latency
  - tree_connect_ops
  - write_latency
  - write_ops
  - close_latency_histogram
  - create_latency_histogram
  - lock_latency_histogram
  - oplock_break_latency_histogram
  - query_directory_latency_histogram
  - query_info_latency_histogram
  - session_setup_latency_histogram
  - set_info_latency_histogram

export_options:
  instance_keys:
    - node
    - svm
```

3. Restart harvest

</details>

<details>
<summary><b>ZapiPerf</b></summary>

**Note:**  
> Below steps are applicable for rpm/deb/native/container installation. **In this example, let's assume that Harvest is installed in** `/opt/harvest`

1. Navigate to the `rest` directory:

```bash
cd /etc/nabox/harvest/user/zapiperf
```

Create `custom.yaml`:

```bash
vi custom.yaml
```

Update the file with the following content:

```yaml
objects:
  SMB2: custom_smb2.yaml
```

2. Create a `custom_smb2.yaml` file in the `/etc/nabox/harvest/user/zapiperf/cdot/9.8.0/` directory.  Update `custom_smb2.yaml` as below.

```yaml
counters:
  - close_latency_histogram
  - create_latency_histogram
  - lock_latency_histogram
  - oplock_break_latency_histogram
  - query_directory_latency_histogram
  - query_info_latency_histogram
  - session_setup_latency_histogram
  - set_info_latency_histogram
```

5. Restart harvest

</details>
