### DISCUSSION TITLE
Configuring ZapiPerf Collector to Exclude Specific SVMs for Qtree

### DISCUSSION THREAD

**Discussion by rahulguptajss** [NetApp/harvest#3376] [Show and tell]
This example demonstrates how to configure the ZapiPerf collector to exclude certain SVMs for a poller in the Qtree ZapiPerf template.

## Step 1: Update Harvest Configuration

For the relevant poller in your Harvest configuration (harvest.yml), make the following changes under `ZapiPerf`:

```yaml
Pollers:
  jamaica:
    datacenter: munich
    addr: 10.10.10.10
    collectors:
      - ZapiPerf:
          - default.yaml
          - limited.yaml # will use conf/zapiperf/limited.yaml
```

## Step 2: Create `limited.yaml` under `conf/zapiperf`

In your `limited.yaml`, include the following content:

```yaml
objects:
  Qtree: custom_qtree.yaml
```

## Step 3: Create `custom_qtree.yaml`

Create a file named `custom_qtree.yaml` under `conf/zapiperf/cdot/9.8.0` with the following content:
Note: Make relevant vserver_name changes as needed.

```yaml
counters:
  - filter:
      - vserver_name!=abc_300,vserver_name!=abcdef
```

## Step 4: Start the Poller

After making these changes, restart the poller to apply the new configuration.
