### DISCUSSION TITLE
Using a Go Binary as a Credential Script for Harvest

### DISCUSSION THREAD

**Discussion by rahulguptajss** [NetApp/harvest#3380] [Show and tell]
## Use Case

When running Harvest inside a container, you might encounter environments where tools like `jq` and `curl` are not available. In such cases, you can use a Go binary as a credential script to fetch authentication information. This guide explains how to build and use a Go binary for this purpose.

For detailed information on configuring the `credentials_script`, refer to the [Harvest documentation](https://netapp.github.io/harvest/latest/configure-harvest-basic/#credentials-script).

## Writing the Go Script

1. Create a Go file named `main.go` with the following content. Note that this is a sample and you will need to modify it to fetch the relevant password for your use case:

    ```go
    package main

    import (
        "fmt"
        "os"
        "strings"
    )

    func main() {
        if len(os.Args) < 2 {
            fmt.Println("Please provide an argument.")
            return
        }

        address := os.Args[1]

        pass := processInput(address)

        fmt.Println("password:", pass)
    }

    func processInput(address string) string {
        if address != "" {
            // process and return password
            // Add custom logic to fetch password for the address
            return strings.ToUpper(address)
        }
        return ""
    }
    ```

## Building the Go Binary

2. Build the Go binary for Linux with the following command:

    ```sh
    GOOS=linux GOARCH=amd64 go build -o get_credentials main.go
    ```

This command will produce a standalone binary named `get_credentials` that can be executed on a Linux system without requiring the Go framework.

## Using the Binary in a Container

3. When running Harvest inside a container, ensure the Go binary is available inside the container. You can achieve this by mounting the binary into the container.

    Example Docker compose file:

```yaml
services:
  sar:
    image: ghcr.io/netapp/harvest:latest
    container_name: sar
    restart: unless-stopped
    ports:
      - "12990:12990"
    command: '--poller sar --promPort 12990 --config /opt/harvest.yml'
    volumes:
      - ./cert:/opt/harvest/cert
      - ./harvest.yml:/opt/harvest.yml
      - ./conf:/opt/harvest/conf
      - ./get_credentials:/opt/harvest/get_credentials    
```
