### DISCUSSION TITLE
Configuring ZapiPerf Collector to Exclude Qtree Collection

### DISCUSSION THREAD

**Discussion by rahulguptajss** [NetApp/harvest#3397] [Ideas]
This example demonstrates how to configure the ZapiPerf collector to exclude Qtree collection for a poller.

## Step 1: Update Harvest Configuration

For the relevant poller in your Harvest configuration (harvest.yml), make the following changes under `ZapiPerf`:

```yaml
Pollers:
  jamaica:
    datacenter: munich
    addr: 10.10.10.10
    collectors:
      - ZapiPerf:
          - exclude_qtree.yaml # will use conf/zapiperf/exclude_qtree.yaml
```

## Step 2: Create `exclude_qtree.yaml` under `conf/zapiperf`

In your `exclude_qtree.yaml`, copy all the content from conf/zapiperf/default.yaml **excluding** below
```
Qtree:                    qtree.yaml
```

## Step 3: Start the Poller

After making these changes, restart the poller to apply the new configuration.
