### DISCUSSION TITLE
Can Harvest collect qtree related metrics in versions lower than 9.15?

### DISCUSSION THREAD

**Discussion by wooyoungAhn** [NetApp/harvest#3420] [Q&A]
Hi
Is qtree_read_data metric available in ontap version 9.13?
It seems to be available only in vserion 9.15 and later.

```conf/keyperf/9.15.0/qtree.yaml```

https://netapp.github.io/harvest/24.11.1/ontap-metrics/#qtree_read_data

This metric appears to be supported in version 9.13 as well.
```statistics.throughput_raw.read```
https://docs.netapp.com/us-en/ontap-restapi-9131//ontap/get-storage-qtrees-.html#response

**Comment by rahulguptajss** [comment]
@wooyoungAhn Harvest uses the Best Fit concept to select templates for an ONTAP version, as detailed [here](https://netapp.github.io/harvest/24.11.1/configure-templates/#harvest-versioned-templates). This means that even if the template version is 9.15, it will also apply to version 9.13.

This metric is part of the `KeyPerf` collector, which is currently in beta. You can find more information about it [here](https://netapp.github.io/harvest/nightly/configure-keyperf/#keyperf-collector).

**Comment by wooyoungAhn** [comment]
Hello rahul
How to apply Keyperf conf on harvest?
I applied this configuration on my system but it didn't work.
```yaml
  CVO-KR:
    collectors:
      - Ems
      - Rest
      - RestPerf
      - KeyPerf
```
```bash
# bin/harvest version
harvest version 24.11.20-nightly (commit 73d63fd7) (build date 2024-11-20T14:11:39-0500) linux/amd64
checking GitHub for 
```

**Comment by rahulguptajss** [comment]
@wooyoungAhn 
Based on your current collector order, the KeyPerf collector will only run for objects that do not exist in RestPerf. For instance, with this order, you'll only see Qtree running with RestPerf and not KeyPerf, since Qtree exists in both collectors and RestPerf has higher precedence than KeyPerf. 

Could you change the order of the collectors as shown below and check if it works for the `qtree` metric `statistics.throughput_raw.read`?

```yaml
  CVO-KR:
    collectors:
      - Ems
      - Rest
      - KeyPerf
      - RestPerf
```

**Comment by wooyoungAhn** [comment]
thank you I can see this
![image](https://github.com/user-attachments/assets/862f48c3-e08a-47d2-8ed6-4c833dbf736f)

**Comment by wooyoungAhn** [comment]
Hello
when apply Keyperf template to harvest, can not see the some metrics.

so i apply to only qtree.yaml but it was not working

How can I apply keyperf to only qtree items?

```yaml
[root@ip-172-30-2-82 keyperf]# pwd
/opt/harvest/conf/keyperf
[root@ip-172-30-2-82 keyperf]# cat custom.yaml 
collector:          KeyPerf

# Order here matters!
schedule:
  - counter:  24h
  - data:      1m

objects:
#  Aggregate:                   aggr.yaml
#  CIFSvserver:                 cifs_vserver.yaml
#  Cluster:                     cluster.yaml
#  FlexCache:                   flexcache.yaml
#  LIF:                         lif.yaml
#  Lun:                         lun.yaml
#  Namespace:                   namespace.yaml
#  NFSv3:                       nfsv3.yaml
#  NFSv41:                      nfsv4_1.yaml
#  NFSv4:                       nfsv4.yaml
#  SystemNode:                  system_node.yaml
#  Volume:                      volume.yaml
  Qtree:                       qtree.yaml
```

![image](https://github.com/user-attachments/assets/dd61f10d-f60e-4779-be75-1421f3b31f10)

### poller log
```log
time=2025-01-22T07:33:54.608Z level=INFO source=collector.go:601 msg=Collected Poller=CVO-KR collector=KeyPerf:NFSv41 apiMs=23 bytesRx=769 calcMs=0 exportMs=0 instances=1 instancesExported=1 metrics=15 metricsExported=11 numCalls=1 numPartials=0 parseMs=0 pluginInstances=0 pluginMs=0 pollMs=23 renderedBytes=903 skips=0 zBegin=1737531234585
time=2025-01-22T07:33:54.836Z level=INFO source=collector.go:601 msg=Collected Poller=CVO-KR collector=KeyPerf:Cluster apiMs=21 bytesRx=526 calcMs=0 exportMs=0 instances=1 instancesExported=1 metrics=15 metricsExported=12 numCalls=1 numPartials=0 parseMs=0 pluginInstances=0 pluginMs=0 pollMs=21 renderedBytes=1205 skips=0 zBegin=1737531234815
time=2025-01-22T07:33:54.906Z level=INFO source=collector.go:601 msg=Collected Poller=CVO-KR collector=KeyPerf:SystemNode apiMs=23 bytesRx=334 calcMs=0 exportMs=0 instances=1 instancesExported=1 metrics=6 metricsExported=1 numCalls=1 numPartials=0 parseMs=0 pluginInstances=0 pluginMs=0 pollMs=23 renderedBytes=90 skips=0 zBegin=1737531234883
time=2025-01-22T07:33:54.915Z level=INFO source=collector.go:601 msg=Collected Poller=CVO-KR collector=KeyPerf:Qtree apiMs=36 bytesRx=643 calcMs=0 exportMs=0 instances=1 instancesExported=1 metrics=13 metricsExported=8 numCalls=1 numPartials=0 parseMs=0 pluginInstances=0 pluginMs=0 pollMs=36 renderedBytes=754 skips=0 zBegin=1737531234878
time=2025-01-22T07:33:54.947Z level=INFO source=collector.go:601 msg=Collected Poller=CVO-KR collector=KeyPerf:Volume apiMs=64 bytesRx=5015 calcMs=0 exportMs=0 instances=4 instancesExported=6 metrics=76 metricsExported=72 numCalls=2 numPartials=0 parseMs=29 pluginInstances=2 pluginMs=0 pollMs=64 renderedBytes=8094 skips=0 zBegin=1737531234883
time=2025-01-22T07:34:49.450Z level=INFO source=collector.go:601 msg=Collected Poller=CVO-KR collector=KeyPerf:NFSv4 apiMs=24 bytesRx=669 calcMs=0 exportMs=0 instances=1 instancesExported=1 metrics=15 metricsExported=11 numCalls=1 numPartials=0 parseMs=0 pluginInstances=0 pluginMs=0 pollMs=24 renderedBytes=877 skips=0 zBegin=1737531289426
time=2025-01-22T07:34:49.493Z level=INFO source=collector.go:601 msg=Collected Poller=CVO-KR collector=KeyPerf:NFSv3 apiMs=37 bytesRx=731 calcMs=0 exportMs=0 instances=1 instancesExported=1 metrics=15 metricsExported=11 numCalls=1 numPartials=0 parseMs=0 pluginInstances=0 pluginMs=0 pollMs=37 renderedBytes=877 skips=0 zBegin=1737531289456
time=2025-01-22T07:34:49.522Z level=INFO source=collector.go:601 msg=Collected Poller=CVO-KR collector=KeyPerf:LIF apiMs=47 bytesRx=2929 calcMs=0 exportMs=0 instances=6 instancesExported=6 metrics=57 metricsExported=18 numCalls=1 numPartials=0 parseMs=0 pluginInstances=0 pluginMs=0 pollMs=47 renderedBytes=2064 skips=0 zBegin=1737531289475
time=2025-01-22T07:34:49.757Z level=INFO source=collector.go:601 msg=Collected Poller=CVO-KR collector=KeyPerf:Aggregate apiMs=60 bytesRx=726 calcMs=0 exportMs=0 instances=1 instancesExported=1 metrics=17 metricsExported=12 numCalls=1 numPartials=0 parseMs=0 pluginInstances=0 pluginMs=0 pollMs=60 renderedBytes=987 skips=0 zBegin=1737531289697
time=2025-01-22T07:34:54.607Z level=INFO source=collector.go:601 msg=Collected Poller=CVO-KR collector=KeyPerf:NFSv41 apiMs=22 bytesRx=769 calcMs=0 exportMs=0 instances=1 instancesExported=1 metrics=15 metricsExported=11 numCalls=1 numPartials=0 parseMs=0 pluginInstances=0 pluginMs=0 pollMs=22 renderedBytes=903 skips=0 zBegin=1737531294585
time=2025-01-22T07:34:54.837Z level=INFO source=collector.go:601 msg=Collected Poller=CVO-KR collector=KeyPerf:Cluster apiMs=20 bytesRx=526 calcMs=0 exportMs=0 instances=1 instancesExported=1 metrics=15 metricsExported=12 numCalls=1 numPartials=0 parseMs=0 pluginInstances=0 pluginMs=0 pollMs=20 renderedBytes=1205 skips=0 zBegin=1737531294816
time=2025-01-22T07:34:54.909Z level=INFO source=collector.go:601 msg=Collected Poller=CVO-KR collector=KeyPerf:SystemNode apiMs=26 bytesRx=334 calcMs=0 exportMs=0 instances=1 instancesExported=1 metrics=6 metricsExported=1 numCalls=1 numPartials=0 parseMs=0 pluginInstances=0 pluginMs=0 pollMs=26 renderedBytes=90 skips=0 zBegin=1737531294884
time=2025-01-22T07:34:54.921Z level=INFO source=collector.go:601 msg=Collected Poller=CVO-KR collector=KeyPerf:Qtree apiMs=42 bytesRx=643 calcMs=0 exportMs=0 instances=1 instancesExported=1 metrics=13 metricsExported=8 numCalls=1 numPartials=0 parseMs=0 pluginInstances=0 pluginMs=0 pollMs=42 renderedBytes=790 skips=0 zBegin=1737531294878
time=2025-01-22T07:34:54.954Z level=INFO source=collector.go:601 msg=Collected Poller=CVO-KR collector=KeyPerf:Volume apiMs=70 bytesRx=5015 calcMs=0 exportMs=0 instances=4 instancesExported=6 metrics=76 metricsExported=72 numCalls=2 numPartials=0 parseMs=31 pluginInstances=2 pluginMs=0 pollMs=71 renderedBytes=8094 skips=0 zBegin=1737531294884
time=2025-01-22T07:35:49.451Z level=INFO source=collector.go:601 msg=Collected Poller=CVO-KR collector=KeyPerf:NFSv4 apiMs=25 bytesRx=669 calcMs=0 exportMs=0 instances=1 instancesExported=1 metrics=15 metricsExported=11 numCalls=1 numPartials=0 parseMs=0 pluginInstances=0 pluginMs=0 pollMs=25 renderedBytes=877 skips=0 zBegin=1737531349426
time=2025-01-22T07:35:49.478Z level=INFO source=collector.go:601 msg=Collected Poller=CVO-KR collector=KeyPerf:NFSv3 apiMs=21 bytesRx=731 calcMs=0 exportMs=0 instances=1 instancesExported=1 metrics=15 metricsExported=11 numCalls=1 numPartials=0 parseMs=0 pluginInstances=0 pluginMs=0 pollMs=21 renderedBytes=877 skips=0 zBegin=1737531349457
time=2025-01-22T07:35:49.515Z level=INFO source=collector.go:601 msg=Collected Poller=CVO-KR collector=KeyPerf:LIF apiMs=40 bytesRx=2929 calcMs=0 exportMs=0 instances=6 instancesExported=6 metrics=57 metricsExported=18 numCalls=1 numPartials=0 parseMs=0 pluginInstances=0 pluginMs=0 pollMs=40 renderedBytes=2062 skips=0 zBegin=1737531349475
time=2025-01-22T07:35:49.730Z level=INFO source=collector.go:601 msg=Collected Poller=CVO-KR collector=KeyPerf:Aggregate apiMs=32 bytesRx=726 calcMs=0 exportMs=0 instance
```

**Reply by rahulguptajss** [reply]
@wooyoungAhn You can try like below to just use `Qtree` with `KeyPerf` where `custom.yaml` in `KeyPerf` folder has only `Qtree` object enabled.

```yaml
  collectors:
    - KeyPerf:
        - custom.yaml
    - RestPerf
 ```
