### DISCUSSION TITLE
ChangeLog Detection for NSSwitch and NFS Changes in an SVM

### DISCUSSION THREAD

**Discussion by rahulguptajss** [NetApp/harvest#3501] [Show and tell]
Below are examples of how the ChangeLog [plugin](https://netapp.github.io/harvest/latest/plugins/#changelog) can be extended for other objects for Zapi Collector. The same can be achieved in the REST collector via relevant templates.

### Example 1: NFS Template

```yaml

name:       NFS
query:      nfs-service-get-iter
object:     nfs_service

counters:
  nfs-info:
    - ^^vserver                                => svm
    - ^auth-sys-extended-groups                => auth_sys_extended_groups
    - ^cached-cred-positive-ttl                => cached_cred_positive_ttl
    - ^extended-groups-limit                   => extended_groups_limit
    - ^ignore-nt-acl-for-root                  => ignore_nt_acl_for_root
    - ^is-nfsv2-enabled                        => is_nfsv2_enabled
    - ^is-nfsv3-64bit-identifiers-enabled      => is_nfsv3_64bit_identifiers_enabled
    - ^is-nfsv3-enabled                        => is_nfsv3_enabled
    - ^is-nfsv40-enabled                       => is_nfsv40_enabled
    - ^is-nfsv41-enabled                       => is_nfsv41_enabled
    - ^ntfs-unix-security-ops                  => ntfs_unix_security_ops

collect_only_labels: true

plugins:
  - LabelAgent:
    - join:
        - uuid `_` svm
  - ChangeLog:
      track:
        - auth_sys_extended_groups
        - cached_cred_positive_ttl
        - extended_groups_limit
        - ignore_nt_acl_for_root
        - is_nfsv2_enabled
        - is_nfsv3_64bit_identifiers_enabled
        - is_nfsv3_enabled
        - is_nfsv40_enabled
        - is_nfsv41_enabled
        - ntfs_unix_security_ops
      publish_labels:
        - svm

export_options:
  instance_keys:
    - svm
  instance_labels:
    - auth_sys_extended_groups
    - cached_cred_positive_ttl
    - extended_groups_limit
    - ignore_nt_acl_for_root
    - is_nfsv2_enabled
    - is_nfsv3_64bit_identifiers_enabled
    - is_nfsv3_enabled
    - is_nfsv40_enabled
    - is_nfsv41_enabled
    - ntfs_unix_security_ops
```

This template publishes a metric in the following format when a change in `is_nfsv40_enabled` is detected:

```
change_log{category="label", cluster="umeng-aff300-01-02", datacenter="u2", index="0", instance="localhost:12992", job="prometheus", new_value="false", object="nfs_service", old_value="true", op="update", svm="harvesttest1", track="is_nfsv40_enabled"} 1
```

### Example 2: NSSwitch Template

```yaml
name:       NSSwitch
query:      nameservice-nsswitch-get-iter
object:     nsswitch

counters:
  namservice-nsswitch-config-info:
    - ^^nameservice-database                   => nameservice_database
    - ^^vserver-name                           => svm
    - nameservice-sources:
        - ^nss-source-type                       => nss_source_type

collect_only_labels: true

plugins:
  - LabelAgent:
      - join:
          - uuid `_` svm,nameservice_database
  - ChangeLog:
      track:
        - nameservice_database
        - nss_source_type
      publish_labels:
        - svm

export_options:
  instance_keys:
    - nameservice_database
    - svm
  instance_labels:
    - nameservice_database
    - nss_source_type
```

This template publishes a metric in the following format when a change is detected in `nss_source_type`:

```
change_log{category="label", cluster="umeng-aff300-01-02", datacenter="u2", index="0", instance="localhost:12992", job="prometheus", new_value="ldap", object="nsswitch", old_value="files", op="update", svm="harvesttest1", track="nss_source_type"} 1
```
