### DISCUSSION TITLE
Can Harvest collect NFSv3 RPC slot tables

### DISCUSSION THREAD

**Discussion by cgrinds** [NetApp/harvest#962] [Q&A] [answered]
Matt asked on Slack if Harvest could be used to collect NFSv3 RPC slot tables
 
# Related
- https://www.netapp.com/pdf.html?item=/media/10720-tr-4067.pdf page 123

**Comment by cgrinds** [comment, marked as answer]
1. Create file `conf/zapiperf/cdot/9.8.0/nfsv3_rpc.yaml` with the following content or create a `custom_yaml` as mentioned [here](https://github.com/NetApp/harvest/tree/main/conf#create-a-new-object-template).

```yaml
name:                     NFSv3_rpc
query:                    cid
object:                   nfs_rpc

instance_key:             uuid

global_labels:
  - nfsv: v3

counters:
  - node_name  => node
  - execs_blocked_on_cid

export_options:
  require_instance_keys: false
  instance_keys:
    - node
```

3. Tell Harvest to use the new template by editing `conf/zapiperf/default.yaml` or creating a `custom.yaml` and adding the same there.

```yaml
  NFSv3_rpc:              nfsv3_rpc.yaml
```

4. Test with `bin/poller --poller u2 --objects NFSv3_rpc --promPort 16001`

5. Verify metrics are being collected
```bash
curl -s 'http://localhost:16001/metrics' | grep -E "nfs_rpc"
nfs_rpc_execs_blocked_on_cid{cluster="umeng-aff300-05-06",datacenter="dc-1",nfsv="v3",node="umeng-aff300-05"} 0
nfs_rpc_execs_blocked_on_cid{cluster="umeng-aff300-05-06",datacenter="dc-1",nfsv="v3",node="umeng-aff300-06"} 7
```

**Reply by mdotten** [reply]
Amazing, I'll present that to the customer, and let you know how it goes! Thanks again, Chris!

**Reply by cgrinds** [reply]
ONTAP returns this counter as a delta, let us know if you would prefer the raw value.

```
  [counter-info]                                   -                                   *
    [desc]                                         - Total execs blocked on per cid limit.
    [is-deprecated]                                -                               false
    [name]                                         -                execs_blocked_on_cid
    [privilege-level]                              -                                diag
    [properties]                                   -                               delta
    [unit]                                         -                                none
````

**Reply by mdotten** [reply]
Hey Chris,

Sorry, newb question here ;) 

What would that delta value look like?  I would think we would want raw values, but is the delta value, a delta from full? sorry not sure what it would show as the properties of the counter being delta

Thanks!!

**Reply by cgrinds** [reply]
In this case, the delta will be the change in the number of `execs_blocked_on_cid` since the previous poll. More details on (metric calculations](https://github.com/NetApp/harvest/blob/main/cmd/collectors/zapiperf/README.md#metrics)

If you want the raw value, you can edit the template like so:
```yaml
name:                     NFSv3_rpc
query:                    cid
object:                   nfs_rpc

instance_key:             uuid

global_labels:
  - nfsv: v3

counters:
  - node_name  => node
  - execs_blocked_on_cid

override:
  - execs_blocked_on_cid: raw

export_options:
  require_instance_keys: false
  instance_keys:
    - node
```
