### ISSUE TITLE
Prometheus exporter: incomplete metatags

### ISSUE THREAD

**Issue by vgratian** [NetApp/harvest#104]
**Describe the bug**
- instance labels (when exported as separate metric) and status metrics do not get the "HELP" and "TYPE" metatags

This was reported by a customer, I will add more details when I get them from the customer and/or reproduce the issues myself.

**Comment by vgratian** [comment]
I moved the second issue to #132

**Comment by cgrinds** [comment]
Please provide test steps @vgratian.
Here's what I tried
```
Exporters:
    prometheus2:
        exporter: Prometheus
        port: 12991
        local_http_addr: 0.0.0.0
Pollers:
    ocum-mobility-01-02:
        datacenter: nane
        addr: -REDACTED-
        auth_style: password
        username: -REDACTED-
        password: -REDACTED-
        use_insecure_tls: true
        add_meta_tags: true
        collectors:
            - Zapi
            - ZapiPerf
        exporters:
            - prometheus2
``` 

Restarted that poller, waited 10 minutes.
Executed `curl -s localhost:12990/metrics | grep "#"`
expected `HELP` lines

None appeared
