### ISSUE TITLE
Add option to use user-defined Collector template

### ISSUE THREAD

**Issue by vgratian** [NetApp/harvest#124]
**Is your feature request related to a problem? Please describe.**
Currently they way poller loads and merges the templates of a Collector is hardcoded:
- First, poller loads `conf/<collector>/default.yaml`
- Second, if exists, it loads `conf/<collector>/custom.yaml` and merges to default.

Users can create `conf/<collector>/custom.yaml` and add additional objects they want to collect. But they can't:
- disable objects that are already defined in `conf/<collector>/default.yaml`
- create multiple custom templates and apply to different pollers

**Describe the solution you'd like**
Add the option to add list of (custom) templates in the `collectors:` parameter in the `Pollers:` section of `harvest.yml`. 

**Describe alternatives you've considered**
Alternative is to add a `Collectors:` section to `harvest.yml` where you define different configurations of the same collector in the same way we do with exporters. But I think this is much more work than adding a single parameter.

**Additional context**
In Harvest 2.0 Alpha (Python version) a similar parameter was implemented. The `collectors:` section could be expanded to with any (valid) collector parameters. E.g.:

```yaml
Pollers:

  shopfloor:
    datacenter: Walldorf
    url: 10.0.0.2
    exporters:
      - prometheus01
    collectors:
      Zapi:
        templates:
           - custom2.yaml
```
