### ISSUE TITLE
Ensure Harvest monitors IPv6-only clusters

### ISSUE THREAD

**Issue by cgrinds** [NetApp/harvest#1289]
- [x] Harvest can export open-metrics via IPv6
- [x] Harvest monitors IPv6 only ONTAP

**Comment by Hardikl** [comment]
This workflow has been tried and tested:
**Case 1:** Enabled the ipv6 in cluster and used that ipv6 format(**Note**: ipv6 and ipv4 both are enabled while testing)
1. Monitoring ipv6 format:
- Added entry in harvest.yml as ipv6 format --> Harvest can able to monitor the cluster seamlessly
Example:
```
      cluster-05:
        datacenter: DC-Rest
        addr: "[0:0:0:0:0:ffff:0ac1:309a]"
        auth_style: basic_auth
        username: xxxxx
        password: xxxxx
        use_insecure_tls: true
        exporters:
          - prometheus
        collectors:
          - Rest
```

2. Exporting in ipv6 format:
- Added entry in prometheus.yml as ipv6 format --> Prometheus can able to pull data from the given ipv6 endpoint seamlessly
Example:
```
  - job_name: 'J5'
    static_configs:
    - targets: ['[0000:0000:0000:0000:0000:ffff:c0a8:2b85]:15002']
```
From prometheus configuration:
```
- job_name: J5
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  static_configs:
  - targets:
    - '[0000:0000:0000:0000:0000:ffff:c0a8:2b85]:15002'
```

Harvest exporting data at ipv6:15002 endpoint
<img width="1212" alt="image" src="https://user-images.githubusercontent.com/83282894/233609766-81f8d1ac-adcf-4f01-ac92-7887c8fe180b.png">

Both way - monitoring cluster and exporting the data from Harvest via ipv6 format are working fine.

**Case 2:** Enabled only ipv6 in cluster and ipv4 disabled 
--> This workflow is yet to be tested
