### ISSUE TITLE
Poller does not open port where it's listening on for prometheus

### ISSUE THREAD

**Issue by florianmulatz** [NetApp/harvest#140]
I expect that the poller should open the configured port where we can point the prometheus target to. 

**Environment**
Provide accurate information about the environment to help us reproduce the issue.

- Harvest version: harvest version 21.05.1-1 (commit 2211c00) (build date 2021-05-21T01:28:12+0530) linux/amd64
- Command line arguments used: bin/harvest status vihsdnclu01 --config /opt/git-repos/config/harvest/harvest-test.yml (for testing)
- OS: Red Hat Enterprise Linux release 8.3 (Ootpa)
- Install method: rpm-package
- ONTAP Version: NetApp Release 9.7P11: Tue Jan 12 23:00:49 UTC 2021
- Other:

**To Reproduce**
Steps to reproduce the behavior: just run the poller with the above mentioned command 

**Expected behavior**
I expect that the poller should open the configured port where we can point the prometheus target to. 

**Actual behavior**
The poller does not open any listening port

**Possible solution, workaround, fix**
Nothing found at the moment / tried to change "prometheus_port" to "promport" or "port" as well - nothing changed.

**Additional context**
harvest-test.yml for review:
```
Exporters:
  prometheus:
    exporter: prometheus
    addr: 10.162.170.102

Defaults:
  collectors:
    - Zapi
    - ZapiPerf
  exporters:
    - prometheus
  use_insecure_tls: true
  auth_style: basic_auth
  username: admin
  password: supersecretpassword
  log_max_bytes: 10000000
  log_max_files: 10

Pollers:
  vihsdnclu01:
    datacenter: VIH
    addr: vihsdnclu01.eu.infineon.com
    prometheus_port: 12000
```

the repspective section im prometheus.yml is
```
  - job_name: 'netapp'
    scrape_interval: 60s
    static_configs:
      - targets:
        - '10.162.170.102:12000' ## vihsdnclu01
```

Don't be confused about the IP - the prometheus server is running on same host as docker container.
