### ISSUE TITLE
Storagegrid overview dashboard

### ISSUE THREAD

**Issue by rahulguptajss** [NetApp/harvest#1718]
Test story for #1420

**Comment by Bhagyasri-Dolly** [comment]
using harvest prometheus - what all metrics we can collect from storage grid 
i can pull the metrics which are in con/storagegrid_metrics.yaml 
how to pull more metrics from storage grid

**Comment by cgrinds** [comment]
Hi @Bhagyasri-Dolly Harvest can collect any of the Prometheus metrics that StorageGRID makes available. As you noted, you can extend or modify the template at `conf/storagegrid/11.6.0/storagegrid_metrics.yaml` or create an new template that has a similar shape as `storagegrid_metrics.yaml`.

Here's a snippet from that file:

```yaml
name:   Prometheus
query:  prometheus
object: storagegrid

schedule:
  - data: 3m

counters:
  - node_cpu_seconds_total
  - storagegrid_ilm_awaiting_client_objects  =>  ilm_awaiting_client_objects

```

The counter name on the left side is the name of the StorageGRID counter you want to collect and the name on the right side is the name you want Harvest to use when exporting this counter. 

The right side will be prefixed with the template's `object` value (in the example above `storagegrid`). When the right side is not defined, the left side is used instead.

Here are a few examples continuing with the template above:
* `node_cpu_seconds_total` - this is the name of the metric that you want to collect from StorageGRID. Since a right side is not defined, Harvest will use `node_cpu_seconds_total` for the right side, and after prefixing, Harvest will export that metric as `storagegrid_node_cpu_seconds_total`.

* `storagegrid_ilm_awaiting_client_objects` name of the metric that you want to collect from StorageGRID. The right side is defined as `ilm_awaiting_client_objects`, which after prefixing, means Harvest will export that metric as `storagegrid_ilm_awaiting_client_objects`.
