### ISSUE TITLE
Prometheus Exporter should support port range

### ISSUE THREAD

**Issue by cgrinds** [NetApp/harvest#172]
# Port Range Prometheus

This solution works well for systemd, native, and containers. It looks like this:

```
Exporters:
  prometheus1:
    exporter: Prometheus
    addr: 0.0.0.0
    port_range: 2000-2030
Pollers:
  cluster-01:
    exporters:
    - prometheus1
  cluster-02:
    exporters:
    - prometheus1
  cluster-03:
    exporters:
    - prometheus1
```

A port range is [inclusive, inclusive] and deterministic. In the example above, `cluster-01` will always be assigned port `2000`, while `cluster-03` will be assigned `2003`. 

Validate ranges as part of doctor, overflow, overlap, etc.

It probably still make sense to generate the Prometheus `target.yml` per file SD discussion, but the port range makes that more deterministic.
