### ISSUE TITLE
Harvest should collect ip routes

### ISSUE THREAD

**Issue by cgrinds** [NetApp/harvest#1795]
As reported by jfong on [Discord](https://discord.com/channels/855068651522490400/1080896292835823627/1080896292835823627)

jfong also contributed a REST template. Thanks!

```yaml
name:                     NetRoute
query:                    api/network/ip/routes
object:                   net_route

counters:
  - ^^uuid                                   => uuid
  - ^svm.name                                => svm
  - ^gateway                                 => gateway
  - ^destination.netmask                     => netmask_length
  - ^destination.address                     => destination

export_options:
  instance_keys:
    - uuid
  instance_labels:
    - svm
    - gateway
    - netmask_length
    - destination
```

@rahulguptajss checked and the ZAPI iter does not include the full set of counters. We will add a template for REST only.
