### ISSUE TITLE
generate docker command is not working

### ISSUE THREAD

**Issue by florianmulatz** [NetApp/harvest#235]
**Describe the bug**
generate docker command is not working as described in release notes

**Environment**
Provide accurate information about the environment to help us reproduce the issue.

- Harvest version: harvest version 21.05.3-1 (commit 63f0b11) (build date 2021-06-23T22:11:00+0530) linux/amd64
- Command line arguments used: started via systemd
- OS: Red Hat Enterprise Linux release 8.3 (Ootpa)
- Install method: rpm-package
- ONTAP Version: NetApp Release 9.5 upwards until 9.8

**To Reproduce**
```
[root@vihlv0230 harvest]# pwd
/opt/harvest
[root@vihlv0230 harvest]# bin/harvest generate docker
panic: open docker/onePollerPerContainer/docker-compose.tmpl: no such file or directory

goroutine 1 [running]:
goharvest2/cmd/tools/generate.generateDockerCompose(0x905636, 0xd)
        goharvest2/cmd/tools/generate/generate.go:72 +0x6e5
goharvest2/cmd/tools/generate.doDockerCompose(0xbf4e60, 0xc2a4f8, 0x0, 0x0)
        goharvest2/cmd/tools/generate/generate.go:47 +0xcb
github.com/spf13/cobra.(*Command).execute(0xbf4e60, 0xc2a4f8, 0x0, 0x0, 0xbf4e60, 0xc2a4f8)
        github.com/spf13/cobra@v1.1.3/command.go:856 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0xbf5fe0, 0x0, 0xbb5768, 0xc000096058)
        github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.1.3/command.go:897
main.main()
        command-line-arguments/harvest.go:683 +0x34
```

**Expected behavior**
should create docker-compose file for each poller configured in harvest.yml

**Actual behavior**
generates error messages and does not create docker-compose files

**Additional context**
seems that docker-template/docker-folder is missing in RPM. Can not find the docker-compose.tmpl file in current working directory.

**Comment by cgrinds** [comment]
You're right @florianmulatz some files were missed in the rpm/deb build. If you want to give it a try sooner you can you grab the tar.gz and add the directories to your rpm install or alternatively just try from the exploded tar.gz?

Thanks for reporting

**Comment by florianmulatz** [comment]
Hi @cgrinds,
I can confirm that grabbing the docker directory from the harvest-21.05.3.tar and putting into the harvest-directory leads to working creation of docker-compose stdout. Maybe you should mention in documentation that output to a docker-compose.yml should be piped via ">". 

Altough I suggest to not use "restart: always" option for the docker but "restart: unless-stopped" so the administrator does have more control over the container start/stop behaviour if wanted. 

Just my two cents
Cheers

**Comment by cgrinds** [comment]
Agree on the redirect - this is what `bin/harvest generate systemd` says
```
Save the following to /etc/systemd/system/harvest.target or | sudo tee /etc/systemd/system/harvest.target
```

I'll add similar to docker.
Agreed, restart policies are tricky, but you're right `unless-stopped` sounds better. Will update
> Similar to always, except that when the container is stopped (manually or otherwise), it is not restarted even after Docker daemon restarts.

**Comment by cgrinds** [comment]
verified on `release/21.05.4` running on RHEL8. 

```
bin/harvest generate docker
Save the following to docker-compose.yml or > docker-compose.yml
and then run docker-compose -f docker-compose.yml up -d --remove-orphans
version: "3.5"
services:

  foo2:
    image: harvest:latest
    container_name: harvest_21.05.4_foo2
    restart: unless-stopped

    stdin_open: true # docker run -i
    tty: true        # docker run -t
    command: ' --poller foo2 --loglevel 2  --config /opt/harvest.yml'
    #entrypoint: ["sh", "-c", "sleep 2073600"]
    volumes:
      - harvest:/opt/harvest/
      - type: bind
        source: /opt/harvest/harvest.yml
        target: /opt/harvest.yml

volumes:
  harvest:⏎
```
