### ISSUE TITLE
Ensure StorageGRID collector works with password

### ISSUE THREAD

**Issue by cgrinds** [NetApp/harvest#2468]
Thanks to Dess on [Discord](https://discord.com/channels/855068651522490400/1171471600319741962/1171471600319741962) for reporting!

22.08.1

They are getting the following error
```
"level":"warn","Poller":"gridname01","error":"invalid character 'I' looking for beginning of value => failed to unmarshal storage grid err","collector":"StorageGrid","object":"Tenant","caller":"poller/poller.go:665","time":"2023-11-07T15:25:29+01:00","message":"init collector-object"}
{"level":"warn","Poller":"gridname01","error":"invalid character 'I' looking for beginning of value => failed to unmarshal storage grid err","collector":"StorageGrid","object":"Prometheus","caller":"poller/poller.go:665","time":"2023-11-07T15:25:29+01:00","message":"init collector-object"}
```

with this config and a password that is like this `%#8mdrUcPANDY#ei`

```yaml
gridname01:
    datacenter: "Location Here"
    addr: 10.x.x.x
    username: "user-name"
    password: "password"
    use_insecure_tls: true
    exporters:
      - prometheus1    
    collectors:
      - StorageGrid
```
