### ISSUE TITLE
Add additional SMBC EMS Events support in Harvest

### ISSUE THREAD

**Issue by Nikhita-13** [NetApp/harvest#2495]
**Is your feature request related to a problem? Please describe.**
We would like to add the following EMS Events to Harvest. This will help users better monitor and manage their SMBC relationships via Harvest

  - name: sms.resync.attempt.failed
    exports:
      - ^^parameters.relationship_id    => relationship_id
      - parameters.dstpath              => dst_path
      - parameters.srcpath              => src_path
      - parameters.next_resync_interval => next_resync_interval

  - name: sms.common.snapshot.failed
    exports:
      - ^^parameters.relationship_id => relationship_id
      - parameters.dstpath           => dst_path
      - parameters.srcpath           => src_path
      - parameters.error_msg         => error_msg
      - parameters.css_fail_interval => css_fail_interval

  - name: sms.snap.not.replicated
    exports:
      - parameters.snapshot      => snapshot 
      - parameters.transferId    => transfer_id
      - parameters.volumeDSID    => volume_DSID
      - parameters.volumePath    => volume_path
      - parameters.failureReason => failure_reason

  - name: sms.fanout.comm.snap.deleted
    exports:
      - parameters.sm_operation      => sm_operation
      - ^^parameters.relationship_id => relationship_id

  - name: smbc.aufo.failed
    exports:
      - parameters.dstpath => dst_path
    
  - name: smbc.aufo.failover.incapable
    exports:
      - parameters.dstpath => dst_path 
 
  - name: smbc.aufo.completed
    exports:
      - parameters.dstpath => dst_path

  - name: smbc.pfo.failed
    exports:
      - parameters.dstpath => dst_path

  - name: smbc.pfo.completed
    exports:
      - parameters.dstpath => dst_path
  
  - name: smc.snapmir.init.fail
    exports:
      - ^^parameters.relationship_id => relationship_id
      - parameters.dstpath           => dst_path
      - parameters.srcpath           => src_path
      - parameters.error             => error

**Comment by cgrinds** [comment]
Rest Template

`conf/rest/9.12.0/smbc.yaml`

```yaml

name:               Smbc
query:              api/cluster/mediators
object:             mediator

counters:
  - ^^uuid                       => uuid
  - ^ip_address                  => ip_address
  - ^peer_cluster.name           => peer_name
  - ^peer_mediator_connectivity  => peer_connectivity
  - ^port                        => port
  - ^reachable                   => reachable

export_options:
  instance_keys:
    - uuid
  instance_labels:
    - ip_address
    - peer_name
    - peer_connectivity
    - port
    - reachable

```

```bash
bin/poller --poller $poller --promPort 12990 --collectors Rest --objects Smbc
```

```bash
curl -s 'http://localhost:12990/metrics' | grep -Ev "#|metadata_" | sort
mediator_labels{cluster="C1_sti238-vsim-sr107e_cluster",datacenter="rtp",ip_address="10.236.166.169",peer_connectivity="connected",peer_name="C2_sti238-vsim-sr107g_cluster",port="31784",reachable="true",uuid="ccfcde33-9273-11ee-8a47-005056aeeb5a"} 1.0
```

## Actions
- [ ] Need to figure out RBAC. The following fails with [least privileged approach](https://netapp.github.io/harvest/23.11/prepare-cdot-clusters/#ontap-cli) 

Tried `security login role create -role harvest2-role -access readonly -cmddirname "storage iscsi-initiator show"` and `security login role create -role harvest2-role -access readonly -cmddirname "metrocluster show"`

```bash
curl --user harvest2:pass -k -n 'https://10.235.145.12/api/cluster/mediators?fields=*'
{
  "error": {
    "message": "not authorized for that command",
    "code": "6"
  }
}
```
- [ ] Validate SMBC EMS alerts
- [ ] Decide if a matching ZAPI template is needed in addition to the REST one
