### ISSUE TITLE
Can't use Poller_files without defining at least one Poller

### ISSUE THREAD

**Issue by joshuacook-tamu** [NetApp/harvest#2640]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please let us know in a comment

### Problem

In setting up my Harvest environment, I wanted to have all Poller configuration defined in individual config files for ease of management. However, when I defined the config as below (without a Poller section but with a Poller_files section) I always get this error when running `bin/harvest doctor --config /etc/harvest/harvest.yml  --print`: 
```
error unmarshalling config file=[/etc/harvest/harvest.yml] configuration error => [Pollers] section not found
error reading config file=[/etc/harvest/harvest.yml] configuration error => [Pollers] section not found
```

My config looks like this:

```
Admin:
  # Listen address for Prometheus HTTP service discovery end-point
  # The endpoint is reachable at SCHEMA://<listen>/api/v1/sd
  # Should be one of: localhost:port, :port, or ip:port
  httpsd:
    listen: localhost:8887
    
    # Basic auth for - /api/v1/sd
    # auth_basic: 
    #   username: admin
    #   password: admin

    # create self-signed certs with 'bin/harvest admin tls create server'
    # tls:
    #   cert_file: cert/admin-cert.pem
    #   key_file: cert/admin-key.pem

Tools:
#  grafana_api_token: 'aaa-bbb-ccc-ddd'
#  autosupport_disabled: true

Exporters:
  prometheus:
    exporter: Prometheus
    local_http_addr: 0.0.0.0
    port: 12990
  prometheus1:
    exporter: Prometheus
    port_range: 13000-14000

Defaults:
  collectors:
    - Zapi
    - ZapiPerf
    - Ems
  use_insecure_tls: false
  
Poller_files:
  - /etc/harvest/configs/*.yml
```

I have one entry in `/etc/harvest/configs/unix.yml` which looks like:

```
Pollers:
  unix:
    datacenter: local
    addr: localhost
    collectors:
      - Unix
    exporters:
      - prometheus
```

I can "fix" this if I define one entry under Pollers so that my config file now looks like:

```
Admin:
  # Listen address for Prometheus HTTP service discovery end-point
  # The endpoint is reachable at SCHEMA://<listen>/api/v1/sd
  # Should be one of: localhost:port, :port, or ip:port
  httpsd:
    listen: localhost:8887
    
    # Basic auth for - /api/v1/sd
    # auth_basic: 
    #   username: admin
    #   password: admin

    # create self-signed certs with 'bin/harvest admin tls create server'
    # tls:
    #   cert_file: cert/admin-cert.pem
    #   key_file: cert/admin-key.pem

Tools:
#  grafana_api_token: 'aaa-bbb-ccc-ddd'
#  autosupport_disabled: true

Exporters:
  prometheus:
    exporter: Prometheus
    local_http_addr: 0.0.0.0
    port: 12990
  prometheus1:
    exporter: Prometheus
    port_range: 13000-14000

Defaults:
  collectors:
    - Zapi
    - ZapiPerf
    - Ems
  use_insecure_tls: false
  
Poller_files:
  - /etc/harvest/configs/*.yml

Pollers:
# This is an optional poller that provides stats about harvest itself.
# To remove it, simply delete the "unix" section
  unix:
    datacenter: local
    addr: localhost
    collectors:
      - Unix
    exporters:
      - prometheus
```

If I now add an additional Poller config `/etc/harvest/configs/ontap.yml`

```
Pollers:
  ontap-wc:
    datacenter: DC1
    addr: x.x.x.x
    use_insecure_tls: true  # Disable TLS verification when connecting to ONTAP cluster
    auth_style: basic_auth
    credentials_file: /etc/harvest/secrets/ontap.yml # read credentials from the file
    exporters:
      - prometheus1
```

If I now run `bin/harvest doctor --config /etc/harvest/harvest.yml  --print`

I get the output below

```
Admin:
    httpsd:
        listen: localhost:8887
Tools:
Exporters:
    prometheus:
        exporter: Prometheus
        local_http_addr: 0.0.0.0
        port: 12990
    prometheus1:
        exporter: Prometheus
        port_range: 13000-14000
Defaults:
    collectors:
        - Zapi
        - ZapiPerf
        - Ems
    use_insecure_tls: false
Poller_files:
    - /etc/harvest/configs/*.yml
Pollers:
    unix:
        datacenter: local
        addr: -REDACTED-
        collectors:
            - Unix
        exporters:
            - prometheus

add 1 poller(s) from poller_file=/etc/harvest/configs/ontap.yml
```

A couple of requests and comments:

- Based on the docs around the `Poller_files` - https://netapp.github.io/harvest/23.11/configure-harvest-basic/#poller_files - I would have expected to be able to define this *WITHOUT* having to define at least one `Poller` in the main `harvest.yml` file - this does not work in this way - I believe this to be a bug or at the very least something that is not clear from the docs if that is how it is supposed to work. But if so, I would request that it be made to work like I was trying to use it - a Pollers_file section with no Pollers defined in the main config file.
- Secondly, in the case where I have one Poller defined in the main config file and one or more defined in the location referenced by `Poller_files` and then run `bin/harvest doctor --config /etc/harvest/harvest.yml  --print` I would expect to see the full config *INCLUDING* what is in the additional config files printed out - I would like to see this output listed just like I do things defined in the main config file

### Configuration

```text
See above
```

### Poller

See above

### Version

harvest version 23.11.0-1 (commit 166b0263) (build date 2023-11-13T09:53:10-0500) linux/amd64

### OS and platform

RHEL 9

### ONTAP or StorageGRID version

N/A since the problem is with harvest itself
