### ISSUE TITLE
Lock counts by node (and possibly cluster)

### ISSUE THREAD

**Issue by troysmullerna** [NetApp/harvest#2652]
I am trying to create a harvest template for doing a 'count' of the number of locks on the filers.  I don't want to capture all the locks, there could be thousands of them, but what I want is a count of locks per node (per cluster would be a bonus).

What we have previously done is use the Netapp_API call and search through the data.  For each record returned, we loop and search for a node list we provide (via another call) and if the node is in the list, we increment the dictionary to increase the number of locks that each node has.

The metric we publish looks like this:

fileserver_locks{filername="nodename"} 58
etc.

We then use this data in prometheus to set alerts that are sent if this number exceeds the total we would LIKE to not see.

**Comment by cgrinds** [comment]
hi @troysmullerna, if you want to try these out before the next release, you can grab the [nightly build](https://github.com/NetApp/harvest/releases/tag/nightly) and try them.

**Comment by troysmullerna** [comment]
I have downloaded the nightly build from 3/14 and tested this.

Aside from the naming of the metrics (which seemed weird to me), the counts look to be within reason of the other way we collect them.

I was expecting to see:

lock_svm_count
lock_lif_count
lock_node_count
lock_volume_count

But instead it was:

volume_lock_count
lif_lock_count
node_lock_count
svm_lock_count

Clearly the aggregator plugin does metric naming different than I expected.

-troy

Troy Muller
TCS Infrastructure and DevOps Engineer
Support: https://tapeout.intel.com/its/#/

From: Chris Grindstaff ***@***.***>
Date: Wednesday, March 6, 2024 at 9:10 AM
To: NetApp/harvest ***@***.***>
Cc: Muller, Troy S ***@***.***>, Mention ***@***.***>
Subject: Re: [NetApp/harvest] Lock counts by node (and possibly cluster) (Issue #2652)

hi @troysmullerna<https://github.com/troysmullerna>, if you want to try these out before the next release, you can grab the nightly build<https://github.com/NetApp/harvest/releases/tag/nightly> and try them.

**Comment by Hardikl** [comment]
Hi @troysmullerna,

Thanks for trying nightly build with the changes.

The Aggregator plugin usage and behaviour details are mentioned here:
https://netapp.github.io/harvest/24.02/plugins/#aggregator

You want `lock_svm_count` metric name instead of the `svm_lock_count`, This can be possible with the same Aggregator plugin just to override names like this:

```
plugins:
  - LabelAgent:
      # metric label zapi_value rest_value `default_value`
      value_to_num_regex:
        - count state .* .* `0`
  - Aggregator:
    # plugin will create summary/average for each object
    # any names after the object names will be treated as
    # label names that will be added to instances
    - node<>lock_node
    - svm<>lock_svm
    - lif<>lock_lif
    - volume<>lock_volume
```

```
harvest %  curl -s http://localhost:13002/metrics | grep -Ev "#|metadata_" 
lock_lif_count{cluster="umeng-aff300-01-02",datacenter="rest",lif="astra_301_lif"} 49
lock_volume_count{cluster="umeng-aff300-01-02",datacenter="rest",volume="trident_pvc_cf16c72a_044e_4e3c_9b04_d2cf06efd0c4"} 28
lock_volume_count{cluster="umeng-aff300-01-02",datacenter="rest",volume="trident_pvc_7ae88770_5935_4fb5_9d26_0f230688f8b3"} 21
lock_node_count{cluster="umeng-aff300-01-02",datacenter="rest",node="umeng-aff300-02"} 49
lock_svm_count{cluster="umeng-aff300-01-02",datacenter="rest",svm="astra_301"} 49
```
