### ISSUE TITLE
NABox doctor command errors for custom.yaml

### ISSUE THREAD

**Issue by rahulguptajss** [NetApp/harvest#2690]
`doctor` command in NABox prints below errors.

```bash
dc exec -w /conf nabox-harvest2 /netapp-harvest/bin/harvest doctor --print
````

```
Error: Problems found in custom.yaml files
  conf/zapi/custom.yaml references template file "custom_volume.yaml,custom_volume_blacklist.yaml,custom_volume_flexgroup.yaml" which does not exist in conf/zapi/**
  conf/zapiperf/custom.yaml references template file "custom_workload_volume.yaml,workload_volume.yaml" which does not exist in conf/zapiperf/**
  conf/zapiperf/custom.yaml references template file "custom_volume_blacklist.yaml,custom_volume_flexgroup.yaml" which does not exist in conf/zapiperf/**
```

**Comment by Hardikl** [comment]
Tested this way,

Updated NABox to **harvest-24.02.19-24.02.0_linux_amd64** (before the fix),
<img width="1152" alt="image" src="https://github.com/NetApp/harvest/assets/83282894/e7f2d49a-5681-4008-8b7a-ab0a6b14eb42">

```
nabox:~# dc exec -w /conf nabox-harvest2 /netapp-harvest/bin/harvest doctor --print
Defaults:
    collectors:
        - Zapi
        - ZapiPerf
        - Rest
    exporters:
        - nabox-prometheus
Exporters:
    nabox-prometheus:
        addr: -REDACTED-
        exporter: Prometheus
        master: true
Pollers:
    A250-41-42-43:
        addr: -REDACTED-
        autostart: '1'
        collectors:
            - Zapi
            - ZapiPerf
            - Rest
            - Ems
        datacenter: dc-1
        password: -REDACTED-
        prometheus_port: 12992
        use_insecure_tls: true
        username: -REDACTED-
    _unix:
        addr: -REDACTED-
        autostart: '1'
        collectors:
            - Unix
        datacenter: NAbox
        prometheus_port: 12800
    umeng-aff300-01-02:
        addr: -REDACTED-
        autostart: '1'
        collectors:
            - Zapi
            - ZapiPerf
            - Rest
        datacenter: dc-1
        password: -REDACTED-
        prometheus_port: 12990
        use_insecure_tls: true
        username: -REDACTED-
    unix:
        addr: -REDACTED-
        autostart: '1'
        collectors:
            - Unix
        datacenter: local
        prometheus_port: 12991
        use_insecure_tls: true
Tools:
    grafana_api_token: -REDACTED-
default:
    send_autosupport_stats: '1'

Error: Problems found in custom.yaml files
  conf/zapi/custom.yaml references template file "custom_volume.yaml,custom_volume_blacklist.yaml,custom_volume_flexgroup.yaml" which does not exist in conf/zapi/**
  conf/zapiperf/custom.yaml references template file "custom_workload_volume.yaml,workload_volume.yaml" which does not exist in conf/zapiperf/**
  conf/zapiperf/custom.yaml references template file "custom_volume_blacklist.yaml,custom_volume_flexgroup.yaml" which does not exist in conf/zapiperf/**
nabox:~# 
```

Updated NABox to **harvest-24.02.0-1_linux_amd64**,
<img width="1108" alt="image" src="https://github.com/NetApp/harvest/assets/83282894/7bd78dc6-ea92-4c63-a74c-02a5b71d41c4">

```
nabox:~# dc exec -w /conf nabox-harvest2 /netapp-harvest/bin/harvest doctor --print
Defaults:
    collectors:
        - Zapi
        - ZapiPerf
        - Rest
    exporters:
        - nabox-prometheus
Exporters:
    nabox-prometheus:
        addr: -REDACTED-
        exporter: Prometheus
        master: true
Pollers:
    A250-41-42-43:
        addr: -REDACTED-
        autostart: '1'
        collectors:
            - Zapi
            - ZapiPerf
            - Rest
            - Ems
        datacenter: dc-1
        password: -REDACTED-
        prometheus_port: 12992
        use_insecure_tls: true
        username: -REDACTED-
    _unix:
        addr: -REDACTED-
        autostart: '1'
        collectors:
            - Unix
        datacenter: NAbox
        prometheus_port: 12800
    umeng-aff300-01-02:
        addr: -REDACTED-
        autostart: '1'
        collectors:
            - Zapi
            - ZapiPerf
            - Rest
        datacenter: dc-1
        password: -REDACTED-
        prometheus_port: 12990
        use_insecure_tls: true
        username: -REDACTED-
    unix:
        addr: -REDACTED-
        autostart: '1'
        collectors:
            - Unix
        datacenter: local
        prometheus_port: 12991
        use_insecure_tls: true
Tools:
    grafana_api_token: -REDACTED-
default:
    send_autosupport_stats: '1'

nabox:~# 
```
