### ISSUE TITLE
Unable to forward logs to the /dev/stdout in podman

### ISSUE THREAD

**Issue by wally007** [NetApp/harvest#2692]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please let us know in a comment

### Problem

Hello,

I'm unable to get any logs output to the /dev/stdout when running multiple pollers inside a single container.
I've set my environment variable inside the container to `HARVEST_LOGS=/dev/stdout`

When I start my container, there is no entry in the podman logs.

The following works (ie. logs are in stdout in podman):
`bin/harvest start $POLLER_NAME --daemon=false --foreground`
But obviously this starts only single poller.

How exactly can we get logs print out to the stdout but with ability to start multiple pollers ?

### Poller

general poller

### Version

23.11.0

### OS and platform

RHEL 9.3 , podman

### ONTAP or StorageGRID version

Netapp 9.13.1P8

**Comment by wally007** [comment]
OK , I think I understand now. There is no way to have multiple pollers in a single container.

I wish this was highlighted more in the documentation. Anyway, feel free to clsoe this issue.

**Comment by cgrinds** [comment]
hi @wally007 You can run multiple pollers in a single container (we know of several customers that have been doing that since 2022) and that's originally how we shipped [container support](https://github.com/NetApp/harvest/discussions/2041). That's also how NAbox runs Harvest pollers.

As mentioned in #2041 there are downsides to that approach which caused us to move to one poller per container, but there is nothing in Harvest that prevents you from running multiple pollers in one container - that's just not a deployment option that the Harvest team ships. 

Where containers are considered, there are many different ways folks want to deploy/config them. We recommend one poller per container and try to make sure we don't get in the way of any other deployment models that customers may want (Terraform, K8, Ansible, etc.)

If you want to run with multiple pollers per container, you can use the Docker file in #2041 as a staring point. Let us know if you hit issues with your custom deployment and we'll try to help.

**Comment by wally007** [comment]
@rahulguptajss 

yes, I had a look and adjusted my Container file as advised - no difference.

**Containerfile**

```

FROM registry.access.redhat.com/ubi9/ubi

USER 0

EXPOSE 12990 12991

ENV HARVEST_DOCKER=yes \
    HARVEST_LOGS=/var/log/harvest \
    SUMMARY="RHEL UBI9 platform for running Harvest by Netapp" \
    VAULT_ADDR=https://xxxx:8200 \
    HTTP_PROXY=http://xxxx:8080 \
    http_proxy=http://xxxx:8080 \
    HTTPS_PROXY=http://xxxx:8080 \
    https_proxy=http://xxxx:8080 \
    NO_PROXY=127.0.0.1,localhost,xxxx \
    no_proxy=127.0.0.1,localhost,xxxx

LABEL summary="${SUMMARY}" \
      name="ubi9-netapp-harvest"

# List of default packages to install
RUN dnf install -y jq hostname && dnf -y clean all
COPY xxxx.crt /etc/pki/ca-trust/source/anchors/xxxx.crt
RUN update-ca-trust

# Configuration of the container for harvest
COPY get_vault_secret.sh /usr/local/bin/get_vault_secret.sh
RUN mkdir -p /opt/harvest && \
    curl -L -o /opt/harvest.tar.gz $(curl -s https://api.github.com/repos/NetApp/harvest/releases/latest | jq -r ".assets[] | select(.name | test(\"tar.gz\")) | .browser_download_url") && \
    tar -xf /opt/harvest.tar.gz -C /opt/harvest --strip-components=1
COPY harvest.yml /opt/harvest/harvest.yml
COPY harvest_entrypoint.sh /opt/harvest/harvest_entrypoint.sh
WORKDIR /opt/harvest
ENTRYPOINT ["./harvest_entrypoint.sh"]
CMD ["start", "--config", "harvest.yml"]
```

**harvest_entrypoint.sh**

```
#!/bin/bash
bin/harvest "$@"
`exec /bin/sleep infinity`
```

and for completeness sake, **harvest.yml**

```
Exporters:
  troy:
    exporter: Prometheus
    local_http_addr: 0.0.0.0
    port: 12990
    global_prefix: netapp_
  agora:
    exporter: Prometheus
    local_http_addr: 0.0.0.0
    port: 12991
    global_prefix: netapp_

Pollers:
  troy:
    datacenter: EQX
    addr: troy-cluster.deutsche-boerse.de
    auth_style: credentials_script
    credentials_script:
      path: /usr/local/bin/get_vault_secret.sh
      schedule: 24h
      timeout: 10s
    username: readonly
    use_insecure_tls: true
    exporters:
      - troy
    collectors:
      - Rest
      - RestPerf
      - Ems
  agora:
    datacenter: EQX
    addr: agora-cluster.deutsche-boerse.de
    auth_style: credentials_script
    credentials_script:
      path: /usr/local/bin/get_vault_secret.sh
      schedule: 24h
      timeout: 10s
    username: readonly
    use_insecure_tls: true
    exporters:
      - agora
    collectors:
      - Rest
      - RestPerf
      - Ems
```
