### ISSUE TITLE
Harvest should add BMC version

### ISSUE THREAD

**Issue by summertony15** [NetApp/harvest#2785]
We have customer requirements for improving ONTAP manageability, and the local team is looking for some resources to meet the customer requirements.

customer has already adopted Harvest to create its dashboard for daily operations, and they are seeking more comprehensive Harvest matrix support to meet its management requirements.

They are asking to monitor BMC version through harvest metric

**Comment by cgrinds** [comment]
@summertony15 do you need BMC version via ZAPI and REST or only REST?

**Comment by cgrinds** [comment]
Firmware versions via REST
```
curl --netrc-file ~/.curl-helper -skn 'https://10.195.15.41/api/cluster/nodes?fields=service_processor' | rg firmware_version
        "firmware_version": "15.6",
        "firmware_version": "15.6",
```

via ZAPI
```
bin/harvest zapi -p aff-251 show data --api service-processor-get-iter | dasel -r xml -w json | rg firmware-version
connected to A250-41-42-43 (NetApp Release Yellowdog__9.12.1: Wed Oct 05 05:47:17 UTC 2022)
          "firmware-version": "15.6",
          "firmware-version": "15.6",
```

**Comment by summertony15** [comment]
@cgrinds  I need BMC version via ZAPI and REST.
Is there any metric that can get the BMC version info now?

**Comment by cgrinds** [comment]
The following REST template will collect BMC version. This is the same REST template that you already have installed with two additions.

Here's what the firmware version looks like with the update REST template.
```bash
curl -s 'http://localhost:12990/metrics' | grep -Ev "#|metadata_" | grep labels
```

node_labels{**bmc_firmware_version="15.6"**,cluster="A250-41-42-43",cpu_firmware_release="17.7",datacenter="rtp",ha_partner="A250-42"...} 1.0


The ZAPI template requires a new plugin since ZAPI only returns BMC info via the `service-processor-get-iter` ZAPI which Harvest does not currently collect.


## Node REST Template 
Search for `bmc_firmware_version` for the two additions.

```yaml

name:                       Node
query:                      api/cluster/nodes
object:                     node

counters:
  - ^^name                                            => node
  - ^controller.cpu.firmware_release                  => cpu_firmware_release
  - ^controller.failed_fan.message.message            => failed_fan_message
  - ^controller.failed_power_supply.message.message   => failed_power_message
  - ^controller.over_temperature                      => over_temperature
  - ^ha.partners.0.name                               => ha_partner
  - ^location
  - ^model
  - ^serial_number                                    => serial
  - ^service_processor.firmware_version               => bmc_firmware_version
  - ^state
  - ^uuid
  - ^version.full                                     => version
  - controller.failed_fan.count                       => failed_fan
  - controller.failed_power_supply.count              => failed_power
  - uptime

endpoints:
  - query: api/private/cli/node
    counters:
      - ^^node                                        => node
      - ^health                                       => healthy
      - ^max_aggr_size                                => max_aggr_size
      - ^max_node_vvols                               => max_vol_num
      - ^max_vol_size                                 => max_vol_size
      - ^vendor                                       => vendor
      - cpu_busy_time                                 => cpu_busytime

plugins:
  - SystemNode
  - LabelAgent:
      value_to_num:
        - new_status healthy true up `0`
      join:
        - warnings `; ` failed_fan_message,failed_power_message,over_temperature
#  - ChangeLog

export_options:
  instance_keys:
    - ha_partner
    - node
    - serial
  instance_labels:
    - bmc_firmware_version
    - cpu_firmware_release
    - healthy
    - location
    - max_aggr_size
    - max_vol_num
    - max_vol_size
    - model
    - partner_healthy
    - state
    - uptime
    - vendor
    - version
    - warnings
```
