### ISSUE TITLE
Invalid syntax in 24.05 when VolumeAnalytics enabled

### ISSUE THREAD

**Issue by db-wally007** [NetApp/harvest#3023]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please let us know in a comment

### Problem

Hello,

I've upgraded Harvest from 24.02 to the latest (as of today) 24.05 and upon container start, I see the following error flooding container log output (journald in my case)

`Jun 29 17:00:28 podman1 netapp-harvest-exporter[3241772]: 2024-06-29T17:00:28Z ERR volumeanalytics/volumeanalytics.go:253 > set metric error="strconv.ParseFloat: parsing \"\": invalid syntax" Poller=agora object=VolumeAnalytics plugin=Rest:VolumeAnalytics value=`

**config file:**

```
---

Exporters:
  troy:
    exporter: Prometheus
    local_http_addr: 0.0.0.0
    port: 12990
    global_prefix: netapp_
  agora:
    exporter: Prometheus
    local_http_addr: 0.0.0.0
    port: 12991
    global_prefix: netapp_

Pollers:
  troy:
    datacenter: EQX
    addr: troy-cluster.xxx.de
    auth_style: basic_auth
    username: $__env{NETAPP_HARVEST_READONLY_USERNAME}
    password: $__env{NETAPP_HARVEST_READONLY_PASSWORD}
    use_insecure_tls: true
    exporters:
      - troy
    collectors:
      - Rest
      - RestPerf
      - Ems
  agora:
    datacenter: EQX
    addr: agora-cluster.xxx.de
    auth_style: basic_auth
    username: $__env{NETAPP_HARVEST_READONLY_USERNAME}
    password: $__env{NETAPP_HARVEST_READONLY_PASSWORD}
    use_insecure_tls: true
    exporters:
      - agora
    collectors:
      - Rest
      - RestPerf
      - Ems
```

**Container file:**

 ```
     FROM {{ netapp_harvest_exporter_podman_template }}
      EXPOSE 12990 12991
      COPY harvest.yml /opt/harvest/harvest.yml
      COPY harvest_entrypoint.sh /opt/harvest/harvest_entrypoint.sh
      ENV NETAPP_HARVEST_READONLY_USERNAME
      ENV NETAPP_HARVEST_READONLY_PASSWORD
      WORKDIR /opt/harvest
      ENTRYPOINT ["./harvest_entrypoint.sh"]
      CMD ["start", "--config", "harvest.yml", "--loglevel=4"]
```

**harvest_entrypoint.sh:**

```
      #!/bin/bash
      bin/harvest "$@"
      `exec /bin/sleep infinity`
```

### Poller

agora poller

### Version

```
root@podman1:~>podman exec -it  netapp-harvest-exporter bin/harvest version
harvest version 24.05.2-1 (commit bae3aad2) (build date 2024-06-13T07:58:11-0400) linux/amd64
```

### OS and platform

RHEL 9.4 , podman

### ONTAP or StorageGRID version

NetApp Release 9.13.1P7

### Additional Context

```
root@podman1:~>podman exec -it  netapp-harvest-exporter bin/harvest zapi -p agora show system
connected to AGORA (NetApp Release 9.13.1P7: Wed Jan 24 16:17:54 UTC 2024)
[results]                                          -                                   *
  [build-timestamp]                                -                          1706113074
  [is-clustered]                                   -                                true
  [version]                                        - NetApp Release 9.13.1P7: Wed Jan 24 16:17:54 UTC 2024

  [version-tuple]                                  -                                   *
    [system-version-tuple]                         -                                   *
      [generation]                                 -                                   9
      [major]                                      -                                  13
      [minor]                                      -                                   1

```
