### ISSUE TITLE
Harvest should collect quotas even when there are not qtrees

### ISSUE THREAD

**Issue by cgrinds** [NetApp/harvest#3035]
See https://github.com/NetApp/harvest/discussions/3024

**Comment by cgrinds** [comment]
Another way to address this missing feature would be to add a new collector template parameter that controls whether a plugin runs even when there are no instances.  

The default value would be false, but could be overridden. Name ideas:

```yaml
always_run_plugins: true
plugins_on_no_data: true
plugins_on_no_instances: true
plugins_on_empty_data: true
run_plugins_if_no_data: true
```
