### ISSUE TITLE
Export aggregate raid status

### ISSUE THREAD

**Issue by hashi825** [NetApp/harvest#311]
**Is your feature request related to a problem? Please describe.**
It would be ideal if harvest would export aggregate raid status, currently there's no way to tell if an aggregate is in a degraded or reconstructing state.

**Describe the solution you'd like**
https://github.com/NetApp/harvest/blob/ff83da0f1e38cc5f5502c806ba307b8333ec345f/conf/zapi/cdot/9.8.0/aggr.yaml#L12 currently only exports state . The SDK doesn't report degradation under the state attribute, attribute `raid-status` is used to summarise overall plex status in an aggregate if its rebuilding or degraded.

Using this value is a bit tricky as the values reported by that attribute can appear by themselves or comma separated, generally they are reported as 

"raid type, hybrid?, status"

(I am not sure if the order of the comma separated values is always the same, on my infrastructure I have always noticed the return value is raid_type, hybrid?, raid_status)

Example Hybrid aggregate with normal raid status:

`raid-status            : raid_dp, hybrid, normal`

Example standard aggregate with normal raid status:

`raid-status            : raid_dp, normal`

**Reference from sdk**

![raid-status](https://user-images.githubusercontent.com/12505096/125871594-5e4efb66-f5aa-43d6-bbb6-dc50477e0e4d.png)

**Describe alternatives you've considered**
I looked at using the `split` plugin but I don't think it would work since then number of values is not always constant.

Possible to use `split_regex` if raid-status is included (example below assumes raid-status is renamed to raid_status)?

`split_regex: raid_status (normal|copying|degraded|foreign|growing|mirror_degraded|parity|out-of-date|reconstruct|resyncing) raid_status`. Not a very elegant solution but might get around it.

**Comment by hashi825** [comment]
I managed to get this working by copying the existing zapi aggregate template and exporting the `raid-status` attribute

I added the following to the custom template

```yaml
plugins:
  LabelAgent:
    value_mapping: status state online `1`
    # metric label zapi_value rest_value `default_value`
    value_to_num: new_status state online online `0`
    split_regex: raid_status `(normal|copying|degraded|foreign|growing|mirror_degraded|parity|out-of-date|reconstruct|resyncing)` raid_status
    value_to_num: raid_status raid_status normal normal `0`

export_options:
  instance_keys:
    - aggr
    - node
  instance_labels:
    - type
    - state
    - raid_status
```
This added a new raid_status label to `aggr_labels` with the regex value and a new time series `aggr_raid_status` with the value to num mapping for raid_status

I found that with harvest version 21.08.0 that custom templates just override the existing ones, so I had to copy all the contents from the default `aggr.yaml` instead of being able to just extend it with some extra attributes.
