### ISSUE TITLE
Harvest Health != ONTAP GUI

### ISSUE THREAD

**Issue by db-wally007** [NetApp/harvest#3149]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please let us know in a comment

### Problem

Hi,

I had opened couple years ago a GitHub issue that ONTAP Web UI showed alerts that Harvest was not showing. I was told the new collector will be introduced to collect the data (I think Its called EMS)

We've had EMS collector enabled for awhile now and we just noticed that in ONTAP Web UI we have an alert that does not show up in Grafana Health dashboard.

**Our collector:**

```
  agora:
    datacenter: EQX
    addr: agora-cluster.deutsche-boerse.de
    auth_style: basic_auth
    username: $__env{NETAPP_HARVEST_READONLY_USERNAME}
    password: $__env{NETAPP_HARVEST_READONLY_PASSWORD}
    use_insecure_tls: true
    exporters:
      - agora
    collectors:
      - Rest
      - RestPerf
      - Ems
```

**ONTAP UI:**

![image](https://github.com/user-attachments/assets/577b56ef-094b-453f-8212-b95f789aecad)

![image](https://github.com/user-attachments/assets/9a190c35-5e72-45a0-8e49-15804280468c)

**Grafana Dashboard:**

![image](https://github.com/user-attachments/assets/92593e42-59ce-4726-976a-82a462fec622)

**In the Grafana panel popup it reads** 

"
The EMS collector gathers EMS events as defined in your ems.yml file. This panel displays events with emergency severity that occurred within the selected time range.
"

The way I understand it, in order to "recreate" ONTAP Web UI alerting, it would require user to recreate 1400+ definitions in the ems.yml ?

Essentially what we are trying to achieve is to use harvest as the ONLY source of metrics and alerts. However the suggested approach is maintenance overkill. We simply want to be alerted when ONTAP has an error without having to look at the Web UI.

We dont need to see the description of the event as in the ONTAP Web UI, but need to be made aware that there is an Alert (**ie. not show on the Grafana Dashboard "0" issues**)

### Poller

agora poller

### Version

latest

### OS and platform

docker

### ONTAP or StorageGRID version

Netapp 9.13.1P8
