### ISSUE TITLE
Possibility to monitor maxdirsize and dirsize used

### ISSUE THREAD

**Issue by BrendonA667** [NetApp/harvest#3243]
**Is your feature request related to a problem? Please describe.**
We had an EMS event that the maxdirsize was reached. To avoid such situations in the future, we would like to have a possibility to monitor the current usage of a dir and alert if it hits like 80% usage. With that we would have time to react.

**Describe the solution you'd like**
A possibility to alert if the maxdirsize is reached and the current usage of a dir is possible.

**Additional context**
Based on the KB article https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/FAQ_ONTAP_maximum_directory_size_maxdirsize there is no direct metric for that. Probably the only way is over EMS, but I am not sure about that.

**Comment by cgrinds** [comment]
Thanks for the KB article @BrendonA667, we'll take a look and see if there are any counters we can monitor. 

As you mentioned, it looks like you can monitor `wafl.dir.size.warning` via [EMS](https://kb.netapp.com/on-prem/ontap/OHW/OHW-KBs/Any_alert_traps_or_events_before_reaching_maximum_directory_size_(maxdirsize)_limit).

I've confirmed that works fine with Harvest. It also looks like you can [change the threshold used](https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_monitor_maxdir_alert_at_70_percent_threshold_or_below) for that warning.

If you want to try via Harvest's EMS collector, you can add the `wafl.dir.size.warning` event to Harvest's existing EMS collector by adding this section of yaml to the `events` section of your `conf/ems/9.6.0/ems.yaml` file.

```yaml
  - name: wafl.dir.size.warning
    exports:
      - parameters.fileid    => directory_inum
      - parameters.vol       => volume
      - parameters.app       => app
      - parameters.volident  => vol_ident
      - parameters.volume    => volume
```

After adding that event and restarting Harvest, Harvest collects that event as you can see in the following curl.
```bash
curl -s 'http://localhost:12990/metrics' | sort | grep -Ev '^#|metadata'
```

ems_events{app="3",cluster="umeng-aff300-01-02",cluster_uuid="cbd1757b-0580-11e8-bd9d-00a098d39e12",datacenter="dc-1",directory_inum="123",index="54859073",message="wafl.dir.size.warning",node="umeng-aff300-01",node_uuid="28e14eab-0580-11e8-bd9d-00a098d39e12",severity="alert",vol_ident="4",volume="vol1"} 1
