### ISSUE TITLE
Volume templates should hide transient volumes

### ISSUE THREAD

**Issue by cgrinds** [NetApp/harvest#3332]
```bash
rg 'To prevent visibility of transient volumes, uncomment the following lines' conf

conf/rest/9.14.0/volume.yaml
109:      # To prevent visibility of transient volumes, uncomment the following lines

conf/rest/9.12.0/volume.yaml
107:      # To prevent visibility of transient volumes, uncomment the following lines

conf/restperf/9.12.0/volume.yaml
62:#      # To prevent visibility of transient volumes, uncomment the following lines

conf/zapiperf/cdot/9.8.0/volume.yaml
53:#      # To prevent visibility of transient volumes, uncomment the following lines

conf/zapiperf/7mode/8.2.5/volume.yaml
29:#      # To prevent visibility of transient volumes, uncomment the following lines

conf/zapi/cdot/9.8.0/volume.yaml
94:    # To prevent visibility of transient volumes, uncomment the following lines

conf/zapi/7mode/8.6.0/volume.yaml
38:    # To prevent visibility of transient volumes, uncomment the following lines
```

**Comment by Hardikl** [comment]
From NABox4,
```
nabox:/opt/harvest2-conf# cat conf/zapi/cdot/9.8.0/custom_volume_blacklist.yaml
plugins:
  LabelAgent:
    exclude_regex:
      - volume `.+_CVclone`
      - volume `.+(0[1-9]|[12][0-9]|3[01])(0[1-9]|1[012])\d\d[0-9]{6}`
      - volume `cl_.+_(19|20)\d\d(0[1-9]|1[012])( 0[1-9]|[12][0-9]|3[01])[0-9]{6}`
      - volume `sdw_cl_.+`
      - volume `MDV_CRS_.+`
      - volume `MDV_aud_.+`
```
