### ISSUE TITLE
Getting "error reading api response => 408 Request Timeout" when running in K8s

### ISSUE THREAD

**Issue by chvvkumar** [NetApp/harvest#347]
**Describe the bug**
We have multiple pollers running in k8s. One of them is working fine on local laptops under docker but in K8s throws 408 errors.

**Environment**
Provide accurate information about the environment to help us reproduce the issue.

- Harvest version: 21.05.3-2
- Command line arguments used: See below
- OS: Kubernetes
- Install method: docker
- ONTAP Version: 9.3P4

**To Reproduce**

**Deployment:**
```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: CLUSTER_NAME 
  namespace: netapp-metrics
  labels:
    app: CLUSTER_NAME 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: CLUSTER_NAME 
  template:
    metadata:
      labels:
        app: CLUSTER_NAME 
    spec:
      nodeSelector:
        topology.kubernetes.io/zone: ZONE_NAME
      volumes:
        - name: zapi-default-config
          configMap:
            name: zapi-default-config

        - name: harvest-poller-config
          secret:
            secretName: harvest-poller-config

      containers:
      - name: CLUSTER_NAME 
        image: REGISTRY/harvest:21.05.3-2
        args:
        - "--config"
        - "/harvest.yml"
        - "--poller"
        - "CLUSTER_NAME "
        resources:
          limits:
            memory: 2G
            cpu: 1000m
          requests:
            memory: 1G
            cpu: 500m
        ports:
        - name: http
          containerPort: 12990
        volumeMounts:
          - name: zapi-default-config
            mountPath: /opt/harvest/conf/zapi/default.yaml
            subPath: default.yaml
          - name: harvest-poller-config
            mountPath: /harvest.yml
            subPath: harvest.yml
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: CLUSTER_NAME 
  name: CLUSTER_NAME 
  namespace: netapp-metrics
spec:
  ports:
  - port: 12990
    targetPort: 12990
    name: metrics
  selector:
    app: CLUSTER_NAME 
  type: ClusterIP
---
kind: ServiceMonitor
apiVersion: monitoring.coreos.com/v1
metadata:
  name: CLUSTER_NAME 
  namespace: netapp-metrics
  labels:
    prometheus: netapp
    prometheusEnv: prd
spec:
  selector:
    matchLabels:
      app: CLUSTER_NAME 
  endpoints:
  - port: metrics
    interval: 1m
    path: /metrics
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: CLUSTER_NAME -perf
  namespace: netapp-metrics
  labels:
    app: CLUSTER_NAME -perf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: CLUSTER_NAME -perf
  template:
    metadata:
      labels:
        app: CLUSTER_NAME -perf
    spec:
      nodeSelector:
        topology.kubernetes.io/zone: ZONE_NAME
      volumes:
        - name: zapi-default-config
          configMap:
            name: zapi-default-config

        - name: harvest-poller-config
          secret:
            secretName: harvest-poller-config

      containers:
      - name: CLUSTER_NAME -perf
        image: REGISTRY/harvest:21.05.3-2
        args:
        - "--config"
        - "/harvest.yml"
        - "--poller"
        - "CLUSTER_NAME -perf"
        resources:
          limits:
            memory: 2G
            cpu: 1000m
          requests:
            memory: 1G
            cpu: 500m
        ports:
        - name: http
          containerPort: 12990
        volumeMounts:
          - name: zapi-default-config
            mountPath: /opt/harvest/conf/zapi/default.yaml
            subPath: default.yaml
          - name: harvest-poller-config
            mountPath: /harvest.yml
            subPath: harvest.yml
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: CLUSTER_NAME -perf
  name: CLUSTER_NAME -perf
  namespace: netapp-metrics
spec:
  ports:
  - port: 12990
    targetPort: 12990
    name: metrics
  selector:
    app: CLUSTER_NAME -perf
  type: ClusterIP
---
kind: ServiceMonitor
apiVersion: monitoring.coreos.com/v1
metadata:
  name: CLUSTER_NAME -perf
  namespace: netapp-metrics
  labels:
    prometheus: netapp
    prometheusEnv: prd
spec:
  selector:
    matchLabels:
      app: CLUSTER_NAME -perf
  endpoints:
  - port: metrics
    interval: 1m
    path: /metrics

```

**Poller Config:**

netapp-harvest/docker/harvest.yml

```
---
Pollers:
  dc1ntap1:
    datacenter: DATACENTER_NAME
    collectors:
      - Zapi
    addr: CLUSTER_NAME
    exporters:
      - promethues
  dc1ntap1-perf:
    datacenter: DATACENTER_NAME
    collectors:
      - Zapiperf
    addr: CLUSTER_NAME
    exporters:
      - promethues

```

default.yaml:

netapp-harvest/docker/default.yaml

```
---
collector:          Zapi

# Order here matters!
schedule:
  - instance: 300s
  - data: 50s

client_timeout: 40

objects:
  Node:             node.yaml
  Aggregate:        aggr.yaml
  Volume:           volume.yaml
  SnapMirror:       snapmirror.yaml
  Disk:             disk.yaml
  Shelf:            shelf.yaml
  Status:           status.yaml
  Subsystem:        subsystem.yaml
  Lun:              lun.yaml

```
**Expected behavior**
Poller should collect metrics

**Actual behavior**
```
5:50PM ERR goharvest2/cmd/poller/collector/collector.go:303 >  error="error reading api response => 408 Request Timeout" Poller=dc1ntap1 collector=Zapi:Aggregate stack=[{"func":"New","line":"35","source":"errors.go"},{"func":"(*Client).invoke","line":"369","source":"client.go"},{"func":"(*Client).InvokeBatchWithTimers","line":"281","source":"client.go"},{"func":"(*Zapi).PollData","line":"350","source":"zapi.go"},{"func":"(*task).Run","line":"60","source":"schedule.go"},{"func":"(*AbstractCollector).Start","line":"269","source":"collector.go"},{"func":"goexit","line":"1371","source":"asm_amd64.s"}]
**Possible solution, workaround, fix**
Tell us if there is a workaround or fix
```

**Additional context**
Add any other context about the problem here. Share logs, error output, etc.

**Comment by cgrinds** [comment]
hi @chvvkumar looks like the poller is timing out trying to connect to your cluster. can you confirm that the hostname or ip of the cluster is reachable from the poller?

**Comment by chvvkumar** [comment]
I can confirm the cluster is reachable from the poller. We do get some intermittent data and the fact that it is not a 404 error leads me to believe cluster reachability is not the cause.

**Comment by chvvkumar** [comment]
Connectivity test: 
![image](https://user-images.githubusercontent.com/16548147/126828343-7b82a0f7-5d65-4e88-8411-b49a1085e4f8.png)

**Comment by cgrinds** [comment]
thanks and I see you've already [increased](https://github.com/NetApp/harvest/wiki/Troubleshooting-Harvest#workaround) the `client_timeout` too. 408 Request Timeout implies a timeout issue. You could try increasing the `client_timeout` higher still to better rule that out.

You also mentioned the poller works on your laptop but fails in k8. In both causes, are you polling the same cluster? Did you need to increase the `client_timeout` on your laptop?

Any other connection related messages or problems in the logs besides the ERR?

**Comment by chvvkumar** [comment]
@cgrinds thanks for the resonse.

Both instances are polling the same cluster with the same config parameters (i.e. same default.yaml). As far as I can tell I did not see any API limit messages or any mgwd related messages on the Cluster's event logs and I am not sure if there are any rate limits on ontapi.

I can try increasing client_timeout further but at the same time don't want to lose resolution from increasing it.

**Comment by cgrinds** [comment]
Yeah, understood on the resolution - at this point, we're mostly trying to rule things out.

Since the laptop is working, this probably is just a mistyping, but figured we should double-check, the `harvest.yml` above has `Zapiperf` misspelled. It should be `ZapiPerf`

Does `./bin/harvest doctor` or `./bin/harvest --config /path/to/harvest.custom.yml doctor` print anything? It would tell you if your ZapiPerf was misspelled? If it prints nothing, no problems found.

We could also try increasing the logging or dump the actual zapi that's failing. 

What was your thinking when you separated the Zapi and ZapiPerf collectors by poller instead of using a list of collectors?

Instead of `#original`, can you try `#combined` below? But again, if you're using exactly the same `harvest.yml` on both machines that doesn't explain why it works on one and not the other.

```
# original
Pollers:
  CLUSTER_NAME:
    datacenter: DATACENTER_NAME
    collectors:
      - Zapi
    addr: CLUSTER_NAME
    exporters:
      - promethues
  CLUSTER_NAME-perf:
    datacenter: DATACENTER_NAME
    collectors:
      - Zapiperf
    addr: CLUSTER_NAME
    exporters:
      - promethues
```

```
# combined
Pollers:
  CLUSTER_NAME:
    datacenter: DATACENTER_NAME
    collectors:
      - Zapi
      - ZapiPerf
    addr: CLUSTER_NAME
    exporters:
      - promethues
```
