### ISSUE TITLE
Harvest EMS Events label plugin

### ISSUE THREAD

**Issue by gaur-piyush** [NetApp/harvest#3490]
**Is your feature request related to a problem? Please describe.**

EMS Events metric uses different labels for different kinds of events. For our observability stack, we required fixed labels which can be used to filter the metrics easily. 

**Describe the solution you'd like**

Referring to the below metric model, events exports variable number of labels based on the event.name. The solution we're looking for it is to converting the parameters for the event into a generic label as key/value pair. 

```
exports:
  - message.name                            => message
  - node.name                               => node
  - node.uuid                               => node_uuid
  - message.severity                        => severity
  - index                                   => index

events:
  - name: LUN.destroy
    exports:
      - parameters.lun_path    => lun_path
      - parameters.object_type => object_type
      - parameters.object_uuid => object_uuid
      - parameters.volume_dsid => volume_ds_id
      - parameters.volume_name => volume

```

Below is the metric model we're looking for. 

```
exports:
  - message.name                            => message
  - node.name                               => node
  - node.uuid                               => node_uuid
  - message.severity                        => severity
  - index                                   => index
  - name => event.name
  - parameters => lun_path:value, object_type:value, object_uuid:value, volume_dsid:value, volume_name:value
```
**Describe alternatives you've considered**
N/A

**Additional context**
