### ISSUE TITLE
Need metrics related to Root aggregates

### ISSUE THREAD

**Issue by gaur-piyush** [NetApp/harvest#3516]
**Is your feature request related to a problem? Please describe.**
Root aggregates are not exposed currently via Harvest for metric collection. 

https://github.com/NetApp/harvest/blob/c1c643619ff249cc22255b25b5c3cef25a0a7140/conf/zapi/cdot/9.8.0/aggr.yaml#L25

**Describe the solution you'd like**
Need metrics related to Root aggrs. 

**Describe alternatives you've considered**

**Additional context**

**Comment by cgrinds** [comment]
hi @gaur-piyush are you using Rest or ZAPI? By default, root aggregates are excluded from the ZAPI template to match what REST provides, but you can change that default by commenting out or removing the `exclude_equals` label agent plugin at lines 66-67. Can you comment out those lines and see if that works for you?

Keep in mind that ONTAP's REST API does not include root aggregates.

<img width="437" alt="Image" src="https://github.com/user-attachments/assets/c5151649-4154-4660-bf75-0c4a71133fe8" />

**Comment by gaur-piyush** [comment]
> hi [@gaur-piyush](https://github.com/gaur-piyush) are you using Rest or ZAPI? By default, root aggregates are excluded from the ZAPI template to match what REST provides, but you can change that default by commenting out or removing the `exclude_equals` label agent plugin at lines 66-67. Can you comment out those lines and see if that works for you?
> 
> Keep in mind that ONTAP's REST API does not include root aggregates.
> 
> <img alt="Image" width="437" src="https://private-user-images.githubusercontent.com/242252/423625509-c5151649-4154-4660-bf75-0c4a71133fe8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDQ3ODc3NzEsIm5iZiI6MTc0NDc4NzQ3MSwicGF0aCI6Ii8yNDIyNTIvNDIzNjI1NTA5LWM1MTUxNjQ5LTQxNTQtNDY2MC1iZjc1LTBjNGE3MTEzM2ZlOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwNDE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDQxNlQwNzExMTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYTFmMmJiZDM4OTEwYzdlYjdiOTk1YjJhZmMwYTI2ZWU1MmZmMGY1NTJiNmVjMzJkMmFjNDc5ODcxOGU4OGU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.eLhBy_7oAESTeD9gTnx9RCCM-hCQZqoGlh8jJ6dEooo">

Sorry for the delay Chris on this. Do I need to add plugins in the template configuration and use the given values?

**Comment by cgrinds** [comment]
Are you using Rest or ZAPI?

**Comment by gaur-piyush** [comment]
We're using REST right now.

**Comment by cgrinds** [comment]
ONTAP's REST API does not include root aggregates by design. If you want to collect those via REST, you will need to use a different API, e.g. the private CLI or ask ONTAP to add root aggregate support to the public API. Let us know if you need help creating a new template that uses the private CLI.

**Comment by Hardikl** [comment]
Minor plugin change has been done as part of PR: https://github.com/NetApp/harvest/pull/3569 to support root aggrs in rest. 

You can upgrade to latest [nightly](https://github.com/NetApp/harvest/releases/tag/nightly) build if you want to try out and use this below template which supports root aggregates as requested.

```
name:               Aggregate
query:              api/private/cli/aggr
object:             aggr

counters:
  - ^^aggregate                                                    => aggr
  - ^encrypt_with_aggr_key                                         => is_encrypted
  - ^node
  - ^raidtype                                                      => raid_type
  - ^root                                                          => root_aggr
  - ^state
  - ^storage_type                                                  => type
  - ^uuid
  - availsize                                                      => space_available
  - data_compacted_count                                           => space_data_compacted_count
  - data_compaction_space_saved                                    => space_data_compaction_saved
  - data_compaction_space_saved_percent                            => space_data_compaction_saved_percent
  - diskcount                                                      => raid_disk_count
  - files_total                                                    => inode_files_total
  - files_used                                                     => inode_files_used
  - fs_files_private_used                                          => inode_files_private_used
  - fs_inodefile_private_capacity                                  => inode_inodefile_private_capacity
  - fs_inodefile_public_capacity                                   => inode_inodefile_public_capacity
  - fs_maxfiles_available                                          => inode_maxfiles_available
  - fs_maxfiles_possible                                           => inode_maxfiles_possible
  - fs_maxfiles_used                                               => inode_maxfiles_used
  - fs_percent_inode_used_capacity                                 => inode_used_percent
  - hybrid_cache_size_total                                        => hybrid_cache_size_total
  - maxraidsize                                                    => raid_size
  - physical_used                                                  => space_physical_used
  - physical_used_percent                                          => space_physical_used_percent
  - plexes                                                         => raid_plex_count
  - sis_shared_count                                               => space_sis_shared_count
  - sis_space_saved                                                => space_sis_saved
  - sis_space_saved_percent                                        => space_sis_saved_percent
  - size                                                           => space_total
  - snap_files_total                                               => snapshot_files_total
  - snap_files_used                                                => snapshot_files_used
  - snap_maxfiles_available                                        => snapshot_maxfiles_available
  - snap_maxfiles_used                                             => snapshot_maxfiles_used
  - snap_size_available                                            => snapshot_size_available
  - snap_size_used                                                 => snapshot_size_used
  - usedsize                                                       => space_used
  - volcount                                                       => volume_count

endpoints:
  - query: api/private/cli/aggr/object-store
    counters:
      - ^^aggregate                                                => aggr
      - ^object_store_name                                         => cloud_stores
      - used_space                                                 => space_capacity_tier_used
  - query: api/private/cli/aggr/show-space
    counters:
      - ^^aggregate                                                => aggr
      - percent_snapshot_space                                     => snapshot_reserve_percent
      - performance_tier_inactive_user_data                        => space_performance_tier_inactive_user_data
      - performance_tier_inactive_user_data_percent                => performance_tier_inactive_user_data_percent
      - snap_size_total                                            => snapshot_size_total
      - volume_footprints                                          => space_performance_tier_used
      - volume_footprints_percent                                  => space_performance_tier_used_percent
      - filter:
          - bin_num=0
  - query: api/private/cli/aggr/show-efficiency
    counters:
      - ^^aggregate                                                => aggr
      - total_data_reduction_logical_used_wo_snapshots             => logical_used_wo_snapshots
      - total_data_reduction_logical_used_wo_snapshots_flexclones  => logical_used_wo_snapshots_flexclones
      - total_data_reduction_physical_used_wo_snapshots            => physical_used_wo_snapshots
      - total_data_reduction_physical_used_wo_snapshots_flexclones => physical_used_wo_snapshots_flexclones
      - total_logical_used                                         => total_logical_used
      - total_physical_used                                        => total_physical_used

plugins:
  - Aggregate
  - LabelAgent:
      value_to_num:
        - new_status state online online `0`
  - MetricAgent:
      compute_metric:
        - snapshot_maxfiles_possible ADD snap_maxfiles_available snap_maxfiles_used
        - space_used_percent PERCENT usedsize size
        - snapshot_used_percent PERCENT snapshot_size_used snapshot_size_total
        - efficiency_savings SUBTRACT total_logical_used total_physical_used
        - efficiency_savings_wo_snapshots SUBTRACT total_data_reduction_logical_used_wo_snapshots total_data_reduction_physical_used_wo_snapshots
        - efficiency_savings_wo_snapshots_flexclones SUBTRACT total_data_reduction_logical_used_wo_snapshots_flexclones total_data_reduction_physical_used_wo_snapshots_flexclones

export_options:
  instance_keys:
    - aggr
    - node
  instance_labels:
    - cloud_stores
    - is_encrypted
    - state
    - type
```
