### ISSUE TITLE
Harvest panics when port_range is used in the Prometheus exporter

### ISSUE THREAD

**Issue by vgratian** [NetApp/harvest#357]
**Describe the bug**
When you configure a Prometheus exporter with the `port_range` parameter, Harvest will panic. Additionally, if the exporter is added in the Defaults (rather than the Pollers) section, no free port is allocated to the exporter. See details below.

**To Reproduce**
Define a Prometheus exporter in your harvest.yml and add to your unix poller:

```yaml
Exporters:
  prom:
    exporter: Prometheus
    port_range: 5555-5559
    global_prefix: netapp
Pollers:
  unix:
    addr: localhost
    collectors:
      - Unix
     exporters:
      - prom
```

Try to start the poller:

```bash
$ ./bin/harvest start unix -ft --config harvest_.yml 

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x728efb]

goroutine 1 [running]:
goharvest2/pkg/conf.loadPrometheusExporterPortRangeMapping()
	goharvest2/pkg/conf/conf.go:328 +0x21b
goharvest2/pkg/conf.GetPrometheusExporterPorts(0xc0001aba58, 0x4, 0x4, 0xc0001aba58, 0x4)
	goharvest2/pkg/conf/conf.go:254 +0x8b4
main.getPollerPrometheusPort(0xc000155440, 0xcdb0e0, 0x4)
	command-line-arguments/harvest.go:544 +0x77
main.doManageCmd(0xc000183900, 0xc00017c6c0, 0x1, 0x4)
	command-line-arguments/harvest.go:161 +0x6ff
github.com/spf13/cobra.(*Command).execute(0xc000183900, 0xc00017c680, 0x4, 0x4, 0xc000183900, 0xc00017c680)
	github.com/spf13/cobra@v1.2.1/command.go:860 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0xcdf9c0, 0x0, 0xc943d8, 0xc00008e058)
	github.com/spf13/cobra@v1.2.1/command.go:974 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.2.1/command.go:902
main.main()
	command-line-arguments/harvest.go:661 +0x34

```
A workaround is to add the `addr` parameter to the exporter (which is not a parameter defined in [documentation](https://github.com/NetApp/harvest/tree/main/cmd/exporters/prometheus#parameters)):

```yaml
Exporters:
  prom:
    exporter: Prometheus
    port_range: 5555-5559
    global_prefix: netapp
    addr: localhost
```
However, even with this workaround, if you add the exporter in the Defaults section, no port is allocated to the exporter:

```yaml
Exporters:
  prom:
    exporter: Prometheus
    port_range: 5555-5559
    global_prefix: netapp
    addr: localhost

Defaults:
  exporters:
    - prom

Pollers:
  unix:
    addr: localhost
    collectors:
      - Unix
```

```bash
$ ./bin/harvest start unix -f --config harvest_.yml 

starting in foreground, enter CTRL+C or close terminal to stop poller
1:31PM INF command-line-arguments/poller.go:153 > log level used: info Poller=unix
1:31PM INF command-line-arguments/poller.go:154 > options config: harvest_.yml Poller=unix
1:31PM INF command-line-arguments/poller.go:179 > started in foreground [pid=45334] Poller=unix
1:31PM ERR goharvest2/cmd/exporters/prometheus/prometheus.go:164 > Issue while reading prometheus port Poller=unix exporter=prom
1:31PM ERR command-line-arguments/poller.go:686 > init exporter (prom): missing parameter => port Poller=unix
1:31PM WRN command-line-arguments/poller.go:563 > exporter (prom) requested by (Unix:poller) not available Poller=unix
1:31PM WRN command-line-arguments/poller.go:266 > no exporters initialized, continuing without exporters Poller=unix
1:31PM INF command-line-arguments/poller.go:285 > poller start-up complete Poller=unix

```

**Additional context**
I will open a PR with explanation about what's wrong in our code and to solve the issue.
