### ISSUE TITLE
Port indicated as option if port_range specified. But it isn't

### ISSUE THREAD

**Issue by ybizeul** [NetApp/harvest#369]
If no port is specified :
```
Exporters:
  nabox-prometheus:
    addr: 0.0.0.0
    exporter: Prometheus
    master: true
    port_range: 2000-2030
```
```
nabox-harvest2        | 1:48PM ERR command-line-arguments/poller.go:686 > init exporter (nabox-prometheus): missing ```
parameter => port Poller=cluster1
```

With port specified the poller starts :

```
Exporters:
  nabox-prometheus:
    addr: 0.0.0.0
    exporter: Prometheus
    master: true
    port: 2031
    port_range: 2000-2030
```
