### ISSUE TITLE
Harvest should collect environment sensor info

### ISSUE THREAD

**Issue by hashi825** [NetApp/harvest#384]
Harvest doesnt collect any chassis sensor info

**Describe the solution you'd like**
Harvest doesnt collect any chassis sensor info, there are a few important scenarios where having this information is really useful, especially NVMEM battery status which when failed causes a shutdown of a cluster in 24hrs.

**Describe alternatives you've considered**
N/A

**Additional context**
This information is available from the environment-sensors-get-iter api, should be fairly easy to map values.

Example data

```critical-high-threshold : 1320
critical-low-threshold  : 1086
node-name               : node
sensor-name             : PVDDQ DDR4 AB
sensor-type             : voltage
threshold-sensor-state  : normal
threshold-sensor-value  : 1228
value-units             : mV
warning-high-threshold  : 1299
warning-low-threshold   : 1100
```

**Comment by vgratian** [comment]
Hi, you should be able to do this on your own. It is our mistake that we have not documented very well how to do this, but the core idea of harvest is that you can add your own templates to collect whatever you want. See steps below:

Step1. Create a new template file for the Zapi collector. E.g. create `conf/zapi/cdot/9.8.0/sensor.yaml` with the following content:

```yaml

name:                      Sensor
query:                      environment-sensors-get-iter
object:                     sensor

counters:
  environment-sensors-info:
    - critical-high-threshold                 => critical_high
    - critical-low-threshold                  => critical_low
    - ^discrete-sensor-state               => discrete_state
    - ^discrete-sensor-value              => discrete_value
    - ^^node-name                            => node
    - ^^sensor-name                        => sensor
    - ^sensor-type                             => type
    - ^threshold-sensor-state           => threshold_state
    - threshold-sensor-value            => threshold_value
    - ^value-units                              => unit
    - ^warning-high-threshold           => warning_high
    - ^warning-low-threshold            => warning_low

export_options:
  include_all_labels: true
````
Step2: to activate the new template, create `conf/zapi/custom.yaml` with the following lines:

```yaml
objects:
  Sensor:   sensor.yaml
```
(in the future, if you add new templates, you can add those in the same file).

Step3: Restart your pollers normally. Alternatively start one poller to test the new template with something like this:

```bash
./bin/harvest start poller shopfloor -fv -c Zapi -o Sensor
```
(In your case, the name of the poller will be different).

Step4. If you use the Prometheus exporter, check the metrics on the HTTP endpoint. E.g. in my case I see metrics like these:

```txt
sensor_value{datacenter="WDRF",cluster="shopfloor",critical_high="3664",node="shopfloor-02",sensor="P3.3V STBY",type="voltage",warning_low="3040",critical_low="2960",threshold_state="normal",unit="mV",warning_high="3568"} 3280
sensor_value{datacenter="WDRF",cluster="shopfloor",sensor="P1.2V STBY",type="voltage",threshold_state="normal",warning_high="1299",warning_low="1105",critical_low="1086",node="shopfloor-02",critical_high="1319",unit="mV"} 1193
sensor_value{datacenter="WDRF",cluster="shopfloor",unit="mV",critical_high="15810",critical_low="0",node="shopfloor-02",sensor="P12V STBY",type="voltage",threshold_state="normal"} 11842
sensor_value{datacenter="WDRF",cluster="shopfloor",sensor="P12V STBY Curr",type="current",threshold_state="normal",unit="mA",critical_high="3182",critical_low="0",node="shopfloor-02"} 748
sensor_value{datacenter="WDRF",cluster="shopfloor",critical_low="1470",node="shopfloor-02",sensor="Sysfan2 F2 Speed",type="fan",threshold_state="normal",unit="RPM",warning_low="1560"} 2820
sensor_value{datacenter="WDRF",cluster="shopfloor",sensor="PSU2 Fan1 Speed",type="fan",threshold_state="normal",unit="RPM",warning_low="4600",critical_low="4500",node="shopfloor-01"} 6900
sensor_value{datacenter="WDRF",cluster="shopfloor",sensor="PSU1 InPwr Monitor",type="unknown",threshold_state="normal",unit="mW",node="shopfloor-01"} 132000
sensor_value{datacenter="WDRF",cluster="shopfloor",critical_high="58",type="thermal",unit="C",warning_high="53",critical_low="0",node="shopfloor-01",sensor="Bat Temp",threshold_state="normal",warning_low="5"} 24
sensor_value{datacenter="WDRF",cluster="shopfloor",critical_high="9000",node="shopfloor-01",sensor="Bat Charge Volt",type="voltage",threshold_state="normal",unit="mV",warning_high="8900"} 8200
sensor_value{datacenter="WDRF",cluster="shopfloor",node="shopfloor-02",sensor="PSU1 InPwr Monitor",type="unknown",threshold_state="normal",unit="mW"} 132000
```
