### ISSUE TITLE
Failed to define custom ZapiPerf collector file (other than defaults.yaml)

### ISSUE THREAD

**Issue by albinpopote** [NetApp/harvest#396]
**Describe the bug**
When I try to change the collector configuration file for ZapiPerf like describe at the end of the section (change to not use the default.yaml) : https://github.com/NetApp/harvest/blob/main/cmd/collectors/zapiperf/README.md#harvest-configuration-file
I got the error : "cannot unmarshal !!map into string"

**Environment**
Provide accurate information about the environment to help us reproduce the issue.

- Harvest version: harvest version 21.05.4-1 (commit 8976370) (build date 2021-08-02T11:24:55+0200) linux/amd64
- Command line arguments used: ./bin/harvest start --foreground --verbose--collectors ZapiPerf --objects SystemNode DC-01
- OS: Debian 10.9
- Install method: dpkg install from manual package compilation 
- ONTAP Version: CDOT 9.5

**To Reproduce**

Create a file limited.yaml in folder /opt/harvest/conf/zapiperf/ : 
```
root@XXX:/opt/harvest# ll conf/zapiperf/
total 16
drwxr-xr-x 3 harvest harvest 4096 juil.  1 22:33 7mode
drwxr-xr-x 4 harvest harvest 4096 août   6 16:59 cdot
-rw-r--r-- 1 harvest harvest 1798 août   2 11:24 default.yaml
-rw-r--r-- 1 harvest harvest   95 août   6 15:44 limited.yaml
```

With the following content: 
```
root@XXX:/opt/harvest# cat conf/zapiperf/limited.yaml
objects:
  SystemNode:             system_node.yaml
  HostAdapter:            hostadapter.yaml
```

And change the harvest.yml on the application root folder : 
```
root@XXX:/opt/harvest# cat harvest.yml
...

Defaults:
  collectors:
    - ZapiPerf
  use_insecure_tls: true

Pollers:
  DC-01:
    datacenter: Lab
    addr: 192.168.xxx.xxx
    auth_style: basic_auth
    username: admin
    password: xxxxxxx
    exporters:
      - my_influxdb
    collectors:
      - ZapiPerf:
        - limited.yaml
```

Got the error when a try to launch with command : 
```
root@XXX:/opt/harvest# ./bin/harvest start --foreground --trace --collectors ZapiPerf --objects SystemNode DC-01
error unmarshalling config file=[./harvest.yml] yaml: unmarshal errors:
  line 25: cannot unmarshal !!map into string
config [./harvest.yml]: yaml: unmarshal errors:
  line 25: cannot unmarshal !!map into string

```

Line 25 corresponds to:
```
      - ZapiPerf:
```
