### ISSUE TITLE
Prometheus exporter with port range not used in default section

### ISSUE THREAD

**Issue by Matthias-Beck** [NetApp/harvest#443]
**Describe the bug**
An exporter with the port_range parameter is created and used in the Defaults section for pollers.

**Environment**
Provide accurate information about the environment to help us reproduce the issue.

- Harvest version: harvest version 21.05.4-2 (commit 19f8f25) (build date 2021-07-22T15:41:23+0000) linux/amd64
- OS: RHEL 7.8
- Install method: rhel

**To Reproduce**
The prometheus exporter is defined with the port_range option.
``` prom-prod:
   exporter: Prometheus
   port_range: 2000-2200
   addr: 0.0.0.0
   global_prefix: netapp_
```

In the Defaults section, this exporter is defined:
```
Defaults:
  collectors:
  - Zapi
  - ZapiPerf
  exporters:
  - prom-prod
```

Pollers definition:
```
Pollers:
  cluster-01:
  datacenter: DC01
  addr: cluster-01.domain.local
```

If you check with `bin/harvest status` the column PromPort will be empty

**Expected behavior**
The exporter with the port_range parameter should be usable with the Defaults section

**Actual behavior**
Pollers not started with a port

**Possible solution, workaround, fix**
Define the exporter per poller.
