### ISSUE TITLE
Error connecting to Netapp cluster

### ISSUE THREAD

**Issue by LH8PPL** [NetApp/harvest#453]
**Describe the bug**
K8S Deployment connecting to NetApp getting the following:
    9:39AM INF command-line-arguments/poller.go:153 > log level used: info Poller=netappdev
    9:39AM INF command-line-arguments/poller.go:154 > options config: /opt/harvest.yml Poller=netappdev
    9:39AM INF command-line-arguments/poller.go:179 > started in foreground [pid=1] Poller=netappdev
    9:39AM WRN command-line-arguments/poller.go:532 > init collector-object (Zapi:Node): connection error => api request rejected => Unable to find API: cluster-identity-get Poller=netappdev
    9:39AM WRN command-line-arguments/poller.go:534 > aborting collector (Zapi) Poller=netappdev
    9:39AM WRN command-line-arguments/poller.go:532 > init collector-object (ZapiPerf:SystemNode): connection error => api request rejected => Unable to find API: cluster-identity-get Poller=netappdev
    9:39AM WRN command-line-arguments/poller.go:534 > aborting collector (ZapiPerf) Poller=netappdev
    9:39AM WRN command-line-arguments/poller.go:257 > no collectors initialized, stopping Poller=netappdev
    9:39AM INF command-line-arguments/poller.go:421 > cleaning up and stopping [pid=1] Poller=netappdev

**Environment**
- Harvest version: harvest version 2.0-nightly (commit ) (build date 2021-07-22T15:42:55+0000) linux/amd64
- Command line arguments used: In deployment
- OS: K8S v1.19.12 , Docker version 18.06.1-ce, build e68fc7a
- Install method: K8S deployment
- ONTAP Version: 9.8-p4
- Other:

**To Reproduce**

**Expected behavior**
It should connect to my Netapp storage

**Actual behavior**
got errors:
init collector-object (Zapi:Node): connection error => api request rejected => Unable to find API: cluster-identity-get Poller=netappdev
 
**Possible solution, workaround, fix**
No workaround or fix that i know

**Additional context**
deployment.yaml:
    ```
    
    ---
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: harvest 
      namespace: prometheus-exporter
      labels:
        app: harvest 
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: harvest 
      template:
        metadata:
          labels:
            app: harvest 
        spec:
          volumes:
            - name: zapi-default-config
              configMap:
                name: zapi-default-config
    
            - name: harvest-poller-config
              secret:
                secretName: harvest-poller-config
    
          containers:
          - name: harvest 
            image: artifact.local/rahulguptajss/harvest:21.05.4-2
            args:
            - "--config"
            - "/opt/harvest.yml"
            - "--poller"
            - "netappdev"
            resources:
              limits:
                memory: 2G
                cpu: 1000m
              requests:
                memory: 1G
                cpu: 500m
            ports:
            - name: http
              containerPort: 12990
            volumeMounts:
              - name: zapi-default-config
                mountPath: /opt/harvest/conf/zapi/default.yaml
                subPath: default.yaml
              - name: harvest-poller-config
                mountPath: /opt/harvest.yml
                subPath: harvest.yml
    ---
    apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: harvest 
      name: harvest 
      namespace: prometheus-exporter
    spec:
      ports:
      - port: 12990
        targetPort: 12990
        name: metrics
      selector:
        app: harvest 
      type: ClusterIP
    ---
    kind: ServiceMonitor
    apiVersion: monitoring.coreos.com/v1
    metadata:
      name: harvest 
      namespace: prometheus-exporter
      labels:
        prometheus: netapp
        prometheusEnv: prd
    spec:
      selector:
        matchLabels:
          app: harvest 
      endpoints:
      - port: metrics
        interval: 1m
        path: /metrics
    ---
    apiVersion: v1
    kind: Secret
    metadata:
      name: harvest-poller-config
      namespace: prometheus-exporter
      labels:
        app: harvest
    type: Opaque
    stringData:
      harvest.yml: |
        Exporters:
          prometheus:
            exporter: Prometheus
            local_http_addr: 0.0.0.0
            port: 12990
          prometheus1:
            exporter: Prometheus
            port: 12991
        Defaults:
          collectors:
            - Zapi
            - ZapiPerf
          use_insecure_tls: true   # <====== adjust as needed to enable/disable TLS checks 
          exporters:
            - prometheus1
    
        Pollers:
          # this is a special/optional poller that provides stats about harvest itself
          # to remove this poller, simply delete the section "unix"
          unix:
            datacenter: local
            addr: localhost
            collectors:
              - Unix
            exporters:
              - prometheus
    
          netappdev:                # <====== add your cluster(s) here, they use the exporter defined three lines above
            datacenter: DEV
            addr: 10.10.10.10
            auth_style: basic_auth
            username: "domain\\username"
            password: "password"
            exporters:
              - prometheus1
    ---
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: zapi-default-config
      namespace: prometheus-exporter
      labels:
        app: harvest
    data:
      default.yaml: |
        collector:          Zapi
    
        # Order here matters!
        schedule:
          - instance: 300s
          - data: 50s
    
        client_timeout: 40
    
        objects:
          Node:             node.yaml
          Aggregate:        aggr.yaml
          Volume:           volume.yaml
          SnapMirror:       snapmirror.yaml
          Disk:             disk.yaml
          Shelf:            shelf.yaml
          Status:           status.yaml
          Subsystem:        subsystem.yaml
          Lun:              lun.yaml
```
