### ISSUE TITLE
Template merge functionality

### ISSUE THREAD

**Issue by rahulguptajss** [NetApp/harvest#493]
For this discussion purpose ```default template``` is lun.yaml and ```custom template```  is custom_lun.yaml

Current behaviour of custom template creation is documented at https://github.com/NetApp/harvest/blob/main/cmd/collectors/zapiperf/README.md#creatingediting-subtemplates

This approach requires copying all contents from default and then modify the custom template. This only supports complete overwrite of default templates. There are problems with this approach.

1. Any change in parameters to default templates from release to release will need manual diffing to maintain changes in custom template.
2. This is not good user experience to copy all contents from default template to custom template.

**Proposed Change in Functionality:**
Proposed solution intend to only change when object key defined in default.yaml and custom.yaml are same.
Solution is to overwrite top level parameters defined in custom template. All other params should be taken from default template. 

**Definition of top level parameters:**
name,query,object,counters,plugins,export_options are the top level elements in below example.

**lun.yaml**

```
name:                       Lun
query:                      lun-get-iter
object:                     lun

counters:
  lun-info:
    - ^node
    - ^path
    - ^qtree
    - size
    - size-used
    - ^state
    - ^^uuid
    - ^volume
    - ^vserver => svm

plugins:
  - LabelAgent:
    value_mapping: status state online `1`
    # metric label zapi_value rest_value `default_value`
    value_to_num: new_status state online online `0`
    # path is something like "/vol/vol_georg_fcp401/lun401"
    # we only want lun name, which is 4th element
    split: path `/` ,,,lun

export_options:
  instance_keys:
    - node
    - qtree
    - lun
    - volume
    - svm
  instance_labels:
    - state
```

**custom_lun.yaml**
```
plugins:
  - LabelAgent:
    # my custom status
    value_mapping: custom_status state online `0`
```

**Post merge lun.yaml**

```
name:                       Lun
query:                      lun-get-iter
object:                     lun

counters:
  lun-info:
    - ^node
    - ^path
    - ^qtree
    - size
    - size-used
    - ^state
    - ^^uuid
    - ^volume
    - ^vserver => svm

plugins:
  - LabelAgent:
    # my custom status
    value_mapping: custom_status state online `0`

export_options:
  instance_keys:
    - node
    - qtree
    - lun
    - volume
    - svm
  instance_labels:
    - state
```

From above example plugins (top level param) got overwritten.

**Advantages of this approach:**

1. Better user experience.
2. Easy to compare and overwrite default templates.
3. Compare and merging all child elements inside top level elements may lead to confusion and manual comparision.
