### ISSUE TITLE
InfluxDB exporter: whitespace in parameter values not escaped

### ISSUE THREAD

**Issue by vgratian** [NetApp/harvest#495]
**Describe the bug**
Issue was reported by a custmer. When the `org` parameter has a whitespace is not escaped when composing a Request URL (see example below).

**To Reproduce**
Define an InfluxDB exporter where the organization name has a whitespace. In my example I had:

```yaml
Exporters:
  influx:
    exporter: InfluxDB
    addr: localhost
    port: 8086
    org: harvest 2
    bucket: harvest22
    token: REDACTED
```

When starting a poller you can see the URL has a whitespace and all requests to InfluxDB are rejected:

```sh
$ ./bin/harvest start unix -ft
(...)
4:49PM DBG goharvest2/cmd/exporters/influxdb/influxdb.go:121 > url= [http://localhost:8086/api/v2/write?org=harvest 2&bucket=harvest22&precision=s] Poller=unix exporter=influx
(...)
4:49PM ERR goharvest2/cmd/exporters/influxdb/influxdb.go:157 > (metadata_component.poller) --> %!s(MISSING) error="api request rejected => 400 Bad Request" Poller=unix exporter=influx stack=[{"func":"New","line":"35","source":"errors.go"},{"func":"(*InfluxDB).Emit","line":"205","source":"influxdb.go"},{"func":"(*InfluxDB).Export","line":"156","source":"influxdb.go"},{"func":"(*Poller).Run","line":"462","source":"poller.go"},{"func":"goexit","line":"1371","source":"asm_amd64.s"}]
4:49PM ERR command-line-arguments/poller.go:463 > export component metadata: error="api request rejected => 400 Bad Request" Poller=unix stack=[{"func":"New","line":"35","source":"errors.go"},{"func":"(*InfluxDB).Emit","line":"205","source":"influxdb.go"},{"func":"(*InfluxDB).Export","line":"156","source":"influxdb.go"},{"func":"(*Poller).Run","line":"462","source":"poller.go"},{"func":"goexit","line":"1371","source":"asm_amd64.s"}]

```
**Expected behavior**
The exporter should escape whitespaces in the URL.

**Possible solution, workaround, fix**
Use the `url` parameter. E.g. in my example, the following will work:

```yaml
Exporters:
  influx:
    exporter: InfluxDB
    url: http://localhost:8086/api/v2/write?org=harvest+2&bucket=harvest22&precision=s
    org: harvest 2
    bucket: harvest22
    token: REDACTED
```
