### ISSUE TITLE
Disk serial number and is-failed are missing from cdot query

### ISSUE THREAD

**Issue by cgrinds** [NetApp/harvest#60]
**Describe the bug**
disk serial was in rc2, but isn't in 21.05

**Environment**

- Harvest version: `harvest version 21.05.2512-v21.05.0 (commit fc433fe) (build date 2021-05-25T12:21:55-0400) linux/amd64`
- Command line arguments used: `bin/harvest start`
- OS: RHEL 8
- Install method: native
- ONTAP Version: 9.9
- Other:

See change here
https://github.com/NetApp/harvest/commit/6bb79ec69171d996c3c4e5b20c9f51b90a83aef6#

Workaround
edit `conf/zapi/cdot/9.8.0/disk.yaml` and add `^serial-number          => serial_number` to the `counters/storage-disk-info/disk-inventory-info` section
```
counters:
  storage-disk-info:
    - ^^disk-uid
    - ^^disk-name               => disk
    - disk-inventory-info:
      - bytes-per-sector        => bytes_per_sector
      - capacity-sectors        => sectors
      - ^disk-type              => type
      - ^is-shared              => shared
      - ^model                  => model
      - ^serial-number          => serial_number
```

In the same file export it like so:
```
export_options:
  instance_keys:
    - node
    - disk
  instance_labels:
    - type
    - model
    - outage
    - owner_node
    - shared
    - shelf
    - shelf_bay
    - serial_number
```
