### ISSUE TITLE
feature request: net-port-ifgrp-get-iter

### ISSUE THREAD

**Issue by pilot7777** [NetApp/harvest#691]
we are trying to get ifgroup info with custom zapi template. the only api i can find is "net-port-ifgrp-get". "show attrs" works. but "show data" gives the following error. seems net-port-ifgrp-get-iter is needed but not available.

`harvest zapi -p flc1-sys-ash0-cloudsys show data --api net-port-ifgrp-get
connected to flc1-sys-ash0-cloudsys (NetApp Release 9.8P6: Tue Aug 03 16:21:11 UTC 2021)
2021/11/24 09:25:52 api request rejected => Missing input: ifgrp-name; Missing input: node`

if we specify parameters while using zapi directly, it can get a particular ifgrp on a node. but parameters are not supported in templates. we'd like to collect metrics[net-ifgrp-info] for all ifgrps on a filer. 

Thank you very much!

James

**Comment by mamoep** [comment]
You could use net-port-get-iter instead. The property _ifgrp-port_ of a physical port shows the interface group membership.

```yaml
name:   NetPort
query:  net-port-get-iter
object: net_port

counters:
  net-port-info:
    - ^broadcast-domain => broadcast_domain
    - ^ifgrp-distribution-function => ifgrp_dist_func
    - ^ifgrp-mode => ifgrp_mode
    - ^ifgrp-port => ifgrp_port
    - ^is-administrative-up => admin_up
    - ^link-status => link_status
    - ^^node => node
    - ^operational-duplex => op_duplex
    - ^operational-speed => op_speed
    - ^^port => port
    - ^port-type => port_type
    - ^role => role
    - ^vlan-id => vlan_id
    - ^vlan-node => vlan_node
    - ^vlan-port => vlan_port

collect_only_labels: true

plugins:
  LabelAgent:
    value_to_num: status link_status up up `0`

export_options:
  include_all_labels: true
```
