### ISSUE TITLE
UseInsecureTls should not be overridden when defined

### ISSUE THREAD

**Issue by cgrinds** [NetApp/harvest#701]
Discovered on `21.11`

This config:

```
Defaults:
  use_insecure_tls: true
Pollers:
  umeng_aff300:
    use_insecure_tls: false
```

When merged, becomes:

```
Pollers:
  umeng_aff300:
    use_insecure_tls: true
```
