### ISSUE TITLE
Custom object template - panic if counter list item indent differs

### ISSUE THREAD

**Issue by mamoep** [NetApp/harvest#704]
**Describe the bug**
I tried to create a custom object template via ansible with `{{ item | to_nice_yaml(indent=2) }}`. The generated output is valid yaml, but the list items under `counter:` are not indented as documented for harvest.

Example template (failing):
```yaml
name: NetPort
object: net_port
query: net-port-get-iter
counters:
  net-port-info:
  - ^broadcast-domain => broadcast_domain
  - ^ifgrp-distribution-function => ifgrp_dist_func
  - ^ifgrp-mode => ifgrp_mode
  - ^ifgrp-port => ifgrp_port
  - ^is-administrative-up => admin_up
  - ^link-status => link_status
  - ^^node => node
  - ^operational-duplex => op_duplex
  - ^operational-speed => op_speed
  - ^^port => port
  - ^port-type => port_type
  - ^role => role
  - ^vlan-id => vlan_id
  - ^vlan-node => vlan_node
  - ^vlan-port => vlan_port
collect_only_labels: true
export_options:
  include_all_labels: true
plugins:
  LabelAgent:
    value_to_num: status link_status up up `0`
```

Example template (working):
```yaml
name:   NetPort
query:  net-port-get-iter
object: net_port
counters:
  net-port-info:
    - ^broadcast-domain => broadcast_domain
    - ^ifgrp-distribution-function => ifgrp_dist_func
    - ^ifgrp-mode => ifgrp_mode
    - ^ifgrp-port => ifgrp_port
    - ^is-administrative-up => admin_up
    - ^link-status => link_status
    - ^^node => node
    - ^operational-duplex => op_duplex
    - ^operational-speed => op_speed
    - ^^port => port
    - ^port-type => port_type
    - ^role => role
    - ^vlan-id => vlan_id
    - ^vlan-node => vlan_node
    - ^vlan-port => vlan_port
collect_only_labels: true
plugins:
  LabelAgent:
    value_to_num: status link_status up up `0`
export_options:
  include_all_labels: true
```

**Environment**
Provide accurate information about the environment to help us reproduce the issue.

- Harvest version: harvest version 21.11.0-1 (commit 66c5ce1) (build date 2021-11-08T08:32:01-0500) linux/amd64
- Command line arguments used: `bin/harvest start`
- OS: RHEL 7.9
- Install method: rhel

**To Reproduce**
define custom template as described above

**Expected behavior**
Collect defined custom metrics

**Actual behavior**
Template is not picked up and metrics dont get collected

**Possible solution, workaround, fix**
Indent counter list entries.

**Additional context**
Log output
```
"level":"error","Poller":"clustername","collector":"Zapi:NetPort",
  "stack":[
    {"func":"New","line":"35","source":"errors.go"},
    {"func":"(*AbstractCollector).Start.func1","line":"259","source":"collector.go"},
    {"func":"gopanic","line":"1038","source":"panic.go"},
    {"func":"goPanicIndex","line":"90","source":"panic.go"},
    {"func":"(*Node).SearchChildren.func1","line":"438","source":"node.go"},
    {"func":"(*Node).SearchChildren","line":"452","source":"node.go"},
    {"func":"(*Zapi).PollInstance","line":"268","source":"zapi.go"},
    {"func":"(*task).Run","line":"61","source":"schedule.go"},
    {"func":"(*AbstractCollector).Start","line":"293","source":"collector.go"},
    {"func":"goexit","line":"1581","source":"asm_amd64.s"}
    ],
  "error":"goroutine panic => goroutine 504 [running]:\n
    runtime/debug.Stack()\n\t
    runtime/debug/stack.go:24 +0x65\ngoharvest2/cmd/poller/collector.(*AbstractCollector).Start.func1()\n\t
    goharvest2/cmd/poller/collector/collector.go:259 +0x85\n
    panic({0x98e6c0, 0xc0004be5b8})\n\t
    runtime/panic.go:1038 +0x215\n
    goharvest2/pkg/tree/node.(*Node).SearchChildren.func1(0xc000c79290, {0xe44d78, 0x0, 0x0})\n\t
    goharvest2/pkg/tree/node/node.go:438 +0x485\ngoharvest2/pkg/tree/node.(*Node).SearchChildren(0x9b2240, {0xe44d78, 0x0, 0x0})\n\t
    goharvest2/pkg/tree/node/node.go:452 +0xd9\ngoharvest2/cmd/collectors/zapi/collector.(*Zapi).PollInstance(0xc00012f400)\n\t
    goharvest2/cmd/collectors/zapi/collector/zapi.go:268 +0x4e5\n
    goharvest2/cmd/poller/schedule.(*task).Run(0xc0001f22d0)\n\t
    goharvest2/cmd/poller/schedule/schedule.go:61 +0x4e\n
    goharvest2/cmd/poller/collector.(*AbstractCollector).Start(0xc0000f4b60, 0xe13d50)\n\t
    goharvest2/cmd/poller/collector/collector.go:293 +0x40a\n
    created by main.(*Poller).Start\n\t
    ./poller.go:394 +0x2e5\n",
  "caller":"goharvest2/cmd/poller/collector/collector.go:259",
  "time":"2021-11-26T10:32:23+01:00",
  "message":"Collector panicked runtime error: index out of range [0] with length 0"
```
