### ISSUE TITLE
feature request: expand env vars in configmap from a kube secret

### ISSUE THREAD

**Issue by rdecaneva** [NetApp/harvest#717]
**Is your feature request related to a problem? Please describe.**
We would like to hide the cluster auth credentials in a kube secret resource using env variables. 

**Describe the solution you'd like**
Ideally, Harvest could expand env vars in a configmap that mounts the harvest.yml file using a secret.

Example:

**Deployment**
```
envFrom:
  - secretRef:
       name: harvest-secret
...

volumeMounts:
  - name: harvest-config
     mountPath: /opt/harvest.yml
     subPath: harvest.yml
...

volumes:
  - name: harvest-config
    configMap: 
      name: harvest-config
```
**ConfigMap**
```
apiVersion: v1
data:
  harvest.yml: |-
    # harvest.yml

    Tools:
    autosupport_disabled: true

    Exporters:
      prometheus:
        exporter: Prometheus
        local_http_addr: 0.0.0.0
        port: 12990

    Defaults:
      collectors:
        - Zapi
        - ZapiPerf
      use_insecure_tls: false

    Pollers:
      [CLUSTERNAME]:
        datacenter: [SITE-NAME]
        addr: [IP]
        auth_style: basic_auth
        username: ${USER_NAME}
        password: ${PASSWORD}
        use_insecure_tls: true
        exporters:
          - prometheus
kind: ConfigMap
metadata:
  name: harvest-config
```
**Secret**
```
apiVersion: v1
kind: Secret
metadata:
  name: harvest-secret
type: Opaque
data:
  USER_NAME: [USERNAME]
  PASSWORD: [PASSWORD]
```

**Describe alternatives you've considered**
Considered writing a custom script, but would require rebuilding the project for each update. 
Also looking into cert auth. 

**Additional context**
N/A
