### ISSUE TITLE
include_contains plugin

### ISSUE THREAD

**Issue by rahulguptajss** [NetApp/harvest#730]
As request over slack by Chad Pruden, 
Harvest should support an label agent ```include_contains``` (inverse of ```exclude_contains```)

**Comment by cgrinds** [comment]
Paste of slack
> Is there an option for include_contains which would be inverse of exclude_contains ?
This is what we have now...  Excluding volumes where comments are '' or (empty)

```
plugins:
  LabelAgent:
    split_pairs: comment ` ` `:`
    exclude_equals: comment ``
  Aggregator:
    volume<style=flexgroup>volume node,svm,aggr,style

export_options:
  instance_keys:
    - volume
    - node
    - svm
    - aggr
    - style
    - volume_set_id
    - cloud_cluster
    - cloud_environment
```

> but that does pickup on other volumes which have other comments, not conforming to the instance_keys I care about. would look something like this... where I only include if the comment has one of my key-names.

```
plugins:
  LabelAgent:
    split_pairs: comment ` ` `:`
    include_contains: comment `volume_set_id`
  Aggregator:
    volume<style=flexgroup>volume node,svm,aggr,style

export_options:
  instance_keys:
    - volume
    - node
    - svm
    - aggr
    - style
    - volume_set_id
    - cloud_cluster
    - cloud_environment
```

**Comment by Hardikl** [comment]
Tested on build artifact: harvest-22.02.0-2.x86_64

Before any change in volume.yaml:
```
[root@scspb2569456002 harvest]#  curl -s 'http://localhost:12992/metrics' | grep volume_labels | grep dry
volume_labels{datacenter="DC-01",cluster="ocum-infinity",volume="dry_run_test",node="ocum-infinity-01",svm="test",aggr="aggr1",style="flexvol",state="online",is_sis_volume="true",snapshot_policy="default",type="rw",protectedByStatus="",protectedBy="not_applicable",protectionRole="unprotected",all_sm_healthy=""} 1.0
volume_labels{datacenter="DC-01",cluster="ocum-infinity",volume="dry_run_test1",node="ocum-infinity-01",svm="test",aggr="aggr1",style="flexvol",state="online",is_sis_volume="true",snapshot_policy="default",type="rw",protectedByStatus="",protectedBy="not_applicable",protectionRole="unprotected",all_sm_healthy=""} 1.0
volume_labels{datacenter="DC-01",cluster="ocum-infinity",volume="dry_run_test3",node="ocum-infinity-01",svm="test",aggr="aggr1",style="flexvol",state="online",is_sis_volume="true",snapshot_policy="default",type="rw",protectedByStatus="",protectedBy="not_applicable",protectionRole="unprotected",all_sm_healthy=""} 1.0
volume_labels{datacenter="DC-01",cluster="ocum-infinity",volume="dry_run_test6",node="ocum-infinity-01",svm="test",aggr="aggr1",style="flexvol",state="online",is_sis_volume="true",snapshot_policy="default",type="rw",protectedByStatus="",protectedBy="not_applicable",protectionRole="unprotected",all_sm_healthy=""} 1.0
volume_labels{datacenter="DC-01",cluster="ocum-infinity",volume="dry_run_test5",node="ocum-infinity-01",svm="test",aggr="aggr1",style="flexvol",state="online",is_sis_volume="true",snapshot_policy="default",type="rw",protectedByStatus="",protectedBy="not_applicable",protectionRole="unprotected",all_sm_healthy=""} 1.0
volume_labels{datacenter="DC-01",cluster="ocum-infinity",volume="dry_run_test2",node="ocum-infinity-01",svm="test",aggr="aggr1",style="flexvol",state="online",is_sis_volume="true",snapshot_policy="default",type="rw",protectedByStatus="",protectedBy="not_applicable",protectionRole="unprotected",all_sm_healthy=""} 1.0
volume_labels{datacenter="DC-01",cluster="ocum-infinity",volume="dry_run_test9",node="ocum-infinity-01",svm="test",aggr="aggr1",style="flexvol",state="online",is_sis_volume="true",snapshot_policy="default",type="rw",protectedByStatus="",protectedBy="not_applicable",protectionRole="unprotected",all_sm_healthy=""} 1.0
volume_labels{datacenter="DC-01",cluster="ocum-infinity",volume="dry_run_test7",node="ocum-infinity-01",svm="test",aggr="aggr1",style="flexvol",state="online",is_sis_volume="true",snapshot_policy="default",type="rw",protectedByStatus="",protectedBy="not_applicable",protectionRole="unprotected",all_sm_healthy=""} 1.0
volume_labels{datacenter="DC-01",cluster="ocum-infinity",volume="dryrun_demo",node="ocum-infinity-01",svm="AIOPs_Test",aggr="aggr1",style="flexvol",state="online",is_sis_volume="true",snapshot_policy="default",type="rw",protectedByStatus="",protectedBy="not_applicable",protectionRole="unprotected",all_sm_healthy=""} 1.0
volume_labels{datacenter="DC-01",cluster="ocum-infinity",volume="dry_run_test8",node="ocum-infinity-01",svm="test",aggr="aggr1",style="flexvol",state="online",is_sis_volume="true",snapshot_policy="default",type="rw",protectedByStatus="",protectedBy="not_applicable",protectionRole="unprotected",all_sm_healthy=""} 1.0
volume_labels{datacenter="DC-01",cluster="ocum-infinity",volume="dry_run_test4",node="ocum-infinity-01",svm="test",aggr="aggr1",style="flexvol",state="online",is_sis_volume="true",snapshot_policy="default",type="rw",protectedByStatus="",protectedBy="not_applicable",protectionRole="unprotected",all_sm_healthy=""} 1.0
[root@scspb2569456002 harvest]#  curl -s 'http://localhost:12992/metrics' | grep volume_labels | wc -l
343
[root@scspb2569456002 harvest]#  curl -s 'http://localhost:12992/metrics' | grep volume_labels | grep dry | wc -l
11
```


changes made in volume.yaml:
**include_contains**
```
plugins:
  Volume:
    schedule:
      - data: 900s  # should be multiple of data poll duration
    #batch_size: "50"
  LabelAgent:
    # metric label zapi_value rest_value `default_value`
    value_to_num:
      - new_status state online online `0`
    exclude_equals:
      - style `flexgroup_constituent`
    replace:
      - style style `flexgroup_constituent` `flexgroup`
    include_contains: 
      - volume `dry`
  Aggregator:
    - volume<style=flexgroup>volume node,svm,aggr,style
```

After adding the 'include_contains':
```
[root@scspb2569456002 harvest]#  curl -s 'http://localhost:12992/metrics' | grep volume_labels 
volume_labels{datacenter="DC-01",cluster="ocum-infinity",volume="dry_run_test4",node="ocum-infinity-01",svm="test",aggr="aggr1",style="flexvol",state="online",is_sis_volume="true",snapshot_policy="default",type="rw",protectedByStatus="",protectedBy="not_applicable",protectionRole="unprotected",all_sm_healthy=""} 1.0
volume_labels{datacenter="DC-01",cluster="ocum-infinity",volume="dryrun_demo",node="ocum-infinity-01",svm="AIOPs_Test",aggr="aggr1",style="flexvol",state="online",is_sis_volume="true",snapshot_policy="default",type="rw",protectedByStatus="",protectedBy="not_applicable",protectionRole="unprotected",all_sm_healthy=""} 1.0
volume_labels{datacenter="DC-01",cluster="ocum-infinity",volume="dry_run_test3",node="ocum-infinity-01",svm="test",aggr="aggr1",style="flexvol",state="online",is_sis_volume="true",snapshot_policy="default",type="rw",protectedByStatus="",protectedBy="not_applicable",protectionRole="unprotected",all_sm_healthy=""} 1.0
volume_labels{datacenter="DC-01",cluster="ocum-infinity",volume="dry_run_test9",node="ocum-infinity-01",svm="test",aggr="aggr1",style="flexvol",state="online",is_sis_volume="true",snapshot_policy="default",type="rw",protectedByStatus="",protectedBy="not_applicable",protectionRole="unprotected",all_sm_healthy=""} 1.0
volume_labels{datacenter="DC-01",cluster="ocum-infinity",volume="dry_run_test7",node="ocum-infinity-01",svm="test",aggr="aggr1",style="flexvol",state="online",is_sis_volume="true",snapshot_policy="default",type="rw",protectedByStatus="",protectedBy="not_applicable",protectionRole="unprotected",all_sm_healthy=""} 1.0
volume_labels{datacenter="DC-01",cluster="ocum-infinity",volume="dry_run_test6",node="ocum-infinity-01",svm="test",aggr="aggr1",style="flexvol",state="online",is_sis_volume="true",snapshot_policy="default",type="rw",protectedByStatus="",protectedBy="not_applicable",protectionRole="unprotected",all_sm_healthy=""} 1.0
volume_labels{datacenter="DC-01",cluster="ocum-infinity",volume="dry_run_test2",node="ocum-infinity-01",svm="test",aggr="aggr1",style="flexvol",state="online",is_sis_volume="true",snapshot_policy="default",type="rw",protectedByStatus="",protectedBy="not_applicable",protectionRole="unprotected",all_sm_healthy=""} 1.0
volume_labels{datacenter="DC-01",cluster="ocum-infinity",volume="dry_run_test8",node="ocum-infinity-01",svm="test",aggr="aggr1",style="flexvol",state="online",is_sis_volume="true",snapshot_policy="default",type="rw",protectedByStatus="",protectedBy="not_applicable",protectionRole="unprotected",all_sm_healthy=""} 1.0
volume_labels{datacenter="DC-01",cluster="ocum-infinity",volume="dry_run_test5",node="ocum-infinity-01",svm="test",aggr="aggr1",style="flexvol",state="online",is_sis_volume="true",snapshot_policy="default",type="rw",protectedByStatus="",protectedBy="not_applicable",protectionRole="unprotected",all_sm_healthy=""} 1.0
volume_labels{datacenter="DC-01",cluster="ocum-infinity",volume="dry_run_test",node="ocum-infinity-01",svm="test",aggr="aggr1",style="flexvol",state="online",is_sis_volume="true",snapshot_policy="default",type="rw",protectedByStatus="",protectedBy="not_applicable",protectionRole="unprotected",all_sm_healthy=""} 1.0
volume_labels{datacenter="DC-01",cluster="ocum-infinity",volume="dry_run_test1",node="ocum-infinity-01",svm="test",aggr="aggr1",style="flexvol",state="online",is_sis_volume="true",snapshot_policy="default",type="rw",protectedByStatus="",protectedBy="not_applicable",protectionRole="unprotected",all_sm_healthy=""} 1.0
[root@scspb2569456002 harvest]#  curl -s 'http://localhost:12992/metrics' | grep volume_labels | wc -l
11
```

**include_equals**
```
plugins:
  Volume:
    schedule:
      - data: 900s  # should be multiple of data poll duration
    #batch_size: "50"
  LabelAgent:
    # metric label zapi_value rest_value `default_value`
    value_to_num:
      - new_status state online online `0`
    exclude_equals:
      - style `flexgroup_constituent`
    replace:
      - style style `flexgroup_constituent` `flexgroup`
    include_equals:
      - volume `dryrun_demo`
  Aggregator:
    - volume<style=flexgroup>volume node,svm,aggr,style
```

```
[root@scspb2569456002 harvest]#  curl -s 'http://localhost:12992/metrics' | grep volume_labels
volume_labels{datacenter="DC-01",cluster="ocum-infinity",volume="dryrun_demo",node="ocum-infinity-01",svm="AIOPs_Test",aggr="aggr1",style="flexvol",state="online",is_sis_volume="true",snapshot_policy="default",type="rw",protectedByStatus="",protectedBy="not_applicable",protectionRole="unprotected",all_sm_healthy=""} 1.0
[root@scspb2569456002 harvest]#  curl -s 'http://localhost:12992/metrics' | grep volume_labels | wc -l
1

```

**include_regex**
```
plugins:
  Volume:
    schedule:
      - data: 900s  # should be multiple of data poll duration
    #batch_size: "50"
  LabelAgent:
    # metric label zapi_value rest_value `default_value`
    value_to_num:
      - new_status state online online `0`
    exclude_equals:
      - style `flexgroup_constituent`
    replace:
      - style style `flexgroup_constituent` `flexgroup`
    include_regex:
      - volume `test[0-9].*$`
  Aggregator:
    - volume<style=flexgroup>volume node,svm,aggr,style
```


```
[root@scspb2569456002 harvest]#  curl -s 'http://localhost:12992/metrics' | grep volume_labels 
volume_labels{datacenter="DC-01",cluster="ocum-infinity",volume="test11388",node="ocum-infinity-01",svm="nslm_auto_svm_16045750206341",aggr="aggr1",style="flexvol",state="online",is_sis_volume="true",snapshot_policy="default",type="rw",protectedByStatus="",protectedBy="not_applicable",protectionRole="unprotected",all_sm_healthy=""} 1.0
volume_labels{datacenter="DC-01",cluster="ocum-infinity",volume="dry_run_test3",node="ocum-infinity-01",svm="test",aggr="aggr1",style="flexvol",state="online",is_sis_volume="true",snapshot_policy="default",type="rw",protectedByStatus="",protectedBy="not_applicable",protectionRole="unprotected",all_sm_healthy=""} 1.0
volume_labels{datacenter="DC-01",cluster="ocum-infinity",volume="dry_run_test5",node="ocum-infinity-01",svm="test",aggr="aggr1",style="flexvol",state="online",is_sis_volume="true",snapshot_policy="default",type="rw",protectedByStatus="",protectedBy="not_applicable",protectionRole="unprotected",all_sm_healthy=""} 1.0
volume_labels{datacenter="DC-01",cluster="ocum-infinity",volume="test123",node="ocum-infinity-01",svm="test",aggr="aggr1",style="flexvol",state="online",is_sis_volume="true",snapshot_policy="default",type="rw",protectedByStatus="",protectedBy="snapmirror",protectionRole="protected",all_sm_healthy="true"} 1.0
volume_labels{datacenter="DC-01",cluster="ocum-infinity",volume="dry_run_test7",node="ocum-infinity-01",svm="test",aggr="aggr1",style="flexvol",state="online",is_sis_volume="true",snapshot_policy="default",type="rw",protectedByStatus="",protectedBy="not_applicable",protectionRole="unprotected",all_sm_healthy=""} 1.0
volume_labels{datacenter="DC-01",cluster="ocum-infinity",volume="test003",node="ocum-infinity-01",svm="vs1_nfs_cifs",aggr="aggr2",style="flexvol",state="online",is_sis_volume="true",snapshot_policy="default",type="rw",protectedByStatus="",protectedBy="not_applicable",protectionRole="unprotected",all_sm_healthy=""} 1.0
volume_labels{datacenter="DC-01",cluster="ocum-infinity",volume="test113",node="ocum-infinity-01",svm="nslm_auto_svm_16045750206341",aggr="aggr2",style="flexvol",state="online",is_sis_volume="true",snapshot_policy="default",type="rw",protectedByStatus="",protectedBy="not_applicable",protectionRole="unprotected",all_sm_healthy=""} 1.0
volume_labels{datacenter="DC-01",cluster="ocum-infinity",volume="test11Backup",node="ocum-infinity-01",svm="vs1_nfs_cifs",aggr="aggr1",style="flexvol",state="online",is_sis_volume="true",snapshot_policy="default",type="rw",protectedByStatus="",protectedBy="not_applicable",protectionRole="unprotected",all_sm_healthy=""} 1.0
volume_labels{datacenter="DC-01",cluster="ocum-infinity",volume="test11indus111",node="ocum-infinity-01",svm="nslm_auto_svm_16045750206341",aggr="aggr1",style="flexvol",state="online",is_sis_volume="true",snapshot_policy="default",type="rw",protectedByStatus="",protectedBy="not_applicable",protectionRole="unprotected",all_sm_healthy=""} 1.0
volume_labels{datacenter="DC-01",cluster="ocum-infinity",volume="dry_run_test4",node="ocum-infinity-01",svm="test",aggr="aggr1",style="flexvol",state="online",is_sis_volume="true",snapshot_policy="default",type="rw",protectedByStatus="",protectedBy="not_applicable",protectionRole="unprotected",all_sm_healthy=""} 1.0
volume_labels{datacenter="DC-01",cluster="ocum-infinity",volume="ss2_test_test123_mirror1",node="ocum-infinity-01",svm="testvs",aggr="aggr1",style="flexvol",state="online",is_sis_volume="true",snapshot_policy="none",type="dp",protectedByStatus="",protectedBy="not_applicable",protectionRole="destination",all_sm_healthy=""} 1.0
volume_labels{datacenter="DC-01",cluster="ocum-infinity",volume="test11indus111check",node="ocum-infinity-01",svm="nslm_auto_svm_16045750206341",aggr="aggr2",style="flexvol",state="online",is_sis_volume="true",snapshot_policy="default",type="rw",protectedByStatus="",protectedBy="not_applicable",protectionRole="unprotected",all_sm_healthy=""} 1.0
volume_labels{datacenter="DC-01",cluster="ocum-infinity",volume="dry_run_test6",node="ocum-infinity-01",svm="test",aggr="aggr1",style="flexvol",state="online",is_sis_volume="true",snapshot_policy="default",type="rw",protectedByStatus="",protectedBy="not_applicable",protectionRole="unprotected",all_sm_healthy=""} 1.0
volume_labels{datacenter="DC-01",cluster="ocum-infinity",volume="dry_run_test8",node="ocum-infinity-01",svm="test",aggr="aggr1",style="flexvol",state="online",is_sis_volume="true",snapshot_policy="default",type="rw",protectedByStatus="",protectedBy="not_applicable",protectionRole="unprotected",all_sm_healthy=""} 1.0
volume_labels{datacenter="DC-01",cluster="ocum-infinity",volume="ss1_test_test123_mirror1",node="ocum-infinity-02",svm="testvs",aggr="aggr4",style="flexvol",state="online",is_sis_volume="false",snapshot_policy="none",type="dp",protectedByStatus="",protectedBy="not_applicable",protectionRole="destination",all_sm_healthy=""} 1.0
volume_labels{datacenter="DC-01",cluster="ocum-infinity",volume="test112",node="ocum-infinity-01",svm="vs2_nfs",aggr="aggr2",style="flexvol",state="online",is_sis_volume="true",snapshot_policy="default",type="rw",protectedByStatus="",protectedBy="not_applicable",protectionRole="unprotected",all_sm_healthy=""} 1.0
volume_labels{datacenter="DC-01",cluster="ocum-infinity",volume="test11industestcheck",node="ocum-infinity-01",svm="nslm_auto_svm_16045750206341",aggr="aggr1",style="flexvol",state="online",is_sis_volume="true",snapshot_policy="default",type="rw",protectedByStatus="",protectedBy="not_applicable",protectionRole="unprotected",all_sm_healthy=""} 1.0
volume_labels{datacenter="DC-01",cluster="ocum-infinity",volume="dry_run_test9",node="ocum-infinity-01",svm="test",aggr="aggr1",style="flexvol",state="online",is_sis_volume="true",snapshot_policy="default",type="rw",protectedByStatus="",protectedBy="not_applicable",protectionRole="unprotected",all_sm_healthy=""} 1.0
volume_labels{datacenter="DC-01",cluster="ocum-infinity",volume="dry_run_test2",node="ocum-infinity-01",svm="test",aggr="aggr1",style="flexvol",state="online",is_sis_volume="true",snapshot_policy="default",type="rw",protectedByStatus="",protectedBy="not_applicable",protectionRole="unprotected",all_sm_healthy=""} 1.0
volume_labels{datacenter="DC-01",cluster="ocum-infinity",volume="dry_run_test1",node="ocum-infinity-01",svm="test",aggr="aggr1",style="flexvol",state="online",is_sis_volume="true",snapshot_policy="default",type="rw",protectedByStatus="",protectedBy="not_applicable",protectionRole="unprotected",all_sm_healthy=""} 1.0
volume_labels{datacenter="DC-01",cluster="ocum-infinity",volume="test11industest",node="ocum-infinity-01",svm="nslm_auto_svm_16045750206341",aggr="aggr1",style="flexvol",state="online",is_sis_volume="true",snapshot_policy="default",type="rw",protectedByStatus="",protectedBy="not_applicable",protectionRole="unprotected",all_sm_healthy=""} 1.0
[root@scspb2569456002 harvest]#  curl -s 'http://localhost:12992/metrics' | grep volume_labels   | wc -l
21
```
