### ISSUE TITLE
Fields(client_timeout, schedule, etc.) in child yaml are not taking precedence over default.yaml

### ISSUE THREAD

**Issue by Hardikl** [NetApp/harvest#765]
Example default.yaml

```
collector:          Zapi

client_timeout:           5m

# Order here matters!
schedule:
  - instance: 600s
  - data: 60s

objects:
  Node:             node.yaml
  Aggregate:        aggr.yaml
  Volume:           volume.yaml
  SnapMirror:       snapmirror.yaml
  Lun:              lun.yaml
  Status_7mode:     status_7.yaml
  Sensor:           sensor.yaml
```

Example volume.yaml

```
name:                     Volume
query:                    volume-get-iter
object:                   volume

# increase client timeout for volumes
client_timeout:           1m
schedule:
  - instance: 6000s
  - data: 240s

counters:
  volume-attributes:
    - volume-autosize-attributes:
      - maximum-size
      - grow-threshold-percent

    - volume-id-attributes:
      - ^^instance-uuid             => instance_uuid
      - ^name                       => volume
      - ^node                       => node
      - ^owning-vserver-name        => svm
      - ^containing-aggregate-name  => aggr
      - ^style-extended             => style
      - ^type                       => type

    - volume-inode-attributes:
      - files-used
      - files-total


    - volume-space-attributes:
      - expected-available
      - filesystem-size                       => filesystem_size
      - logical-available
      - logical-used
      - logical-used-by-afs
      - logical-used-by-snapshots

    - volume-state-attributes:
      - ^state
      - ^status

    - volume-snapshot-attributes:
      - ^auto-snapshots-enabled             => auto_snapshots_enabled
      - ^snapshot-policy
      - snapshot-count

plugins:
  LabelAgent:
    # metric label zapi_value rest_value `default_value`
    value_to_num:
      - new_status state online online `0`

export_options:
  instance_keys:
    - volume
    - node
    - svm
    - aggr
    - style
  instance_labels:
    - state
```

Running poller with extra logger in zapi.go as well as in volume plugin to verify the value from default and value from individual yaml and which one takes precedence.

Points:
- default.yaml data collection is 1min
- volume.yaml data collection is 4min 
- As per the poller logs, every one min volume data has been collected by Harvest and run method from volume plugin is invoked.
- Same apply for client_timeout and other fields as well

```
hardikl@hardikl-mac-0 harvest % ./bin/poller --poller cluster-07 --loglevel 2  --promPort 12991   -c Zapi --config harvest.yml
7:47PM INF ./poller.go:179 > log level used: info Poller=cluster-07
7:47PM INF ./poller.go:180 > options config: harvest.yml Poller=cluster-07
7:47PM INF ./poller.go:217 > started in foreground [pid=20719] Poller=cluster-07
7:47PM INF goharvest2/cmd/poller/collector/helpers.go:122 > best-fit template [conf/zapi/cdot/9.8.0/volume.yaml] for [9.10.1] Poller=cluster-07 collector=Zapi:Volume
7:47PM INF goharvest2/cmd/collectors/zapi/collector/zapi.go:110 > Before default: [collector client_timeout schedule objects addr auth_style collectors datacenter exporters password use_insecure_tls username] Poller=cluster-07 collector=Zapi:Volume
7:47PM INF goharvest2/cmd/collectors/zapi/collector/zapi.go:111 > Before schedule default: [600s 60s] Poller=cluster-07 collector=Zapi:Volume
7:47PM INF goharvest2/cmd/collectors/zapi/collector/zapi.go:112 > Before timeout default: 5m Poller=cluster-07 collector=Zapi:Volume
7:47PM INF goharvest2/cmd/collectors/zapi/collector/zapi.go:113 > Before template: [name query object client_timeout schedule counters plugins export_options] Poller=cluster-07 collector=Zapi:Volume
7:47PM INF goharvest2/cmd/collectors/zapi/collector/zapi.go:115 > Before schedule template: [6000s 240s] Poller=cluster-07 collector=Zapi:Volume
7:47PM INF goharvest2/cmd/collectors/zapi/collector/zapi.go:118 > Before timeout template: 1m Poller=cluster-07 collector=Zapi:Volume
7:47PM INF goharvest2/cmd/collectors/zapi/collector/zapi.go:122 > After union: [collector client_timeout schedule objects addr auth_style collectors datacenter exporters password use_insecure_tls username name query object counters plugins export_options] Poller=cluster-07 collector=Zapi:Volume
7:47PM INF goharvest2/cmd/collectors/zapi/collector/zapi.go:123 > After union schedule: [600s 60s] Poller=cluster-07 collector=Zapi:Volume
7:47PM INF goharvest2/cmd/collectors/zapi/collector/zapi.go:124 > After union timeout: 5m Poller=cluster-07 collector=Zapi:Volume
7:47PM INF goharvest2/cmd/collectors/zapi/collector/zapi.go:138 > final client timeout value : 5m Poller=cluster-07 collector=Zapi:Volume
7:47PM INF goharvest2/cmd/collectors/zapi/plugins/volume/volume.go:116 > interval Poller=cluster-07 plugin=900 volume=60
7:47PM INF ./poller.go:341 > Autosupport scheduled. Poller=cluster-07 asupSchedule=24h
7:47PM INF ./poller.go:350 > poller start-up complete Poller=cluster-07
7:47PM INF ./poller.go:497 > updated status, up collectors: 1 (of 1), up exporters: 1 (of 1) Poller=cluster-07
7:48PM INF goharvest2/cmd/collectors/zapi/plugins/volume/volume.go:89 > volume plugin invoked Poller=cluster-07 plugin=Zapi:Volume
7:48PM INF goharvest2/cmd/collectors/zapi/plugins/volume/volume.go:89 > volume plugin invoked Poller=cluster-07 plugin=Zapi:Volume
7:49PM INF goharvest2/cmd/collectors/zapi/plugins/volume/volume.go:89 > volume plugin invoked Poller=cluster-07 plugin=Zapi:Volume
7:50PM INF goharvest2/cmd/collectors/zapi/plugins/volume/volume.go:89 > volume plugin invoked Poller=cluster-07 plugin=Zapi:Volume
7:51PM INF goharvest2/cmd/collectors/zapi/plugins/volume/volume.go:89 > volume plugin invoked Poller=cluster-07 plugin=Zapi:Volume
7:52PM INF goharvest2/cmd/collectors/zapi/plugins/volume/volume.go:89 > volume plugin invoked Poller=cluster-07 plugin=Zapi:Volume
7:54PM INF goharvest2/cmd/collectors/zapi/plugins/volume/volume.go:89 > volume plugin invoked Poller=cluster-07 plugin=Zapi:Volume
7:55PM INF goharvest2/cmd/collectors/zapi/plugins/volume/volume.go:89 > volume plugin invoked Poller=cluster-07 plugin=Zapi:Volume
7:56PM INF goharvest2/cmd/collectors/zapi/plugins/volume/volume.go:89 > volume plugin invoked Poller=cluster-07 plugin=Zapi:Volume
7:57PM INF goharvest2/cmd/collectors/zapi/plugins/volume/volume.go:89 > volume plugin invoked Poller=cluster-07 plugin=Zapi:Volume
7:57PM WRN goharvest2/cmd/poller/collector/collector.go:421 > lagging behind schedule 6.25939664s Poller=cluster-07 collector=Zapi:Volume
7:58PM INF goharvest2/cmd/collectors/zapi/plugins/volume/volume.go:89 > volume plugin invoked Poller=cluster-07 plugin=Zapi:Volume
7:59PM INF goharvest2/cmd/collectors/zapi/plugins/volume/volume.go:89 > volume plugin invoked Poller=cluster-07 plugin=Zapi:Volume
8:00PM INF goharvest2/cmd/collectors/zapi/plugins/volume/volume.go:89 > volume plugin invoked Poller=cluster-07 plugin=Zapi:Volume
```
