### ISSUE TITLE
bin/harvest status incorrectly says poller is not running when using influx exporter

### ISSUE THREAD

**Issue by cgrinds** [NetApp/harvest#835]
**Describe the bug**
bin/harvest status incorrectly says poller is not running when using influx exporter

**Environment**
de7cdd7

**To Reproduce**
1. a cluster to `harvest.yml` and connect that poller to an `exporter: InfluxDB`
2. start poller
```
bin/harvest start v-72
  Datacenter | Poller | PID | PromPort |   Status     
-------------+--------+-----+----------+--------------
  dc-1       | v-72   |     |          | not running  
```

It is running, but the status is wrong.
```
ps aux | grep poller
cgrinds         73706   1.1  0.0 34890608  14556   ??  S     8:40AM   0:00.23 bin/poller --poller v-72 --loglevel 2 --config ./harvest.yml --daemon
```

**Expected behavior**
Status should correctly that it's running and show pid

**Comment by cgrinds** [comment]
Verified on `release/22.02.0` 727e0b5

```
Exporters:
  influx1:
    exporter: InfluxDB
    addr: localhost
    bucket: harvest
    org: harvest
    token: foo

Pollers:
  v-72: 
    datacenter: dc-1
    exporters:
      - influx1
```  

```
bin/harvest start v-72
  Datacenter | Poller |  PID  | PromPort | Status   
-------------+--------+-------+----------+----------
  dc-1       | v-72   | 15541 |          | running  


bin/harvest status v-72
  Datacenter | Poller |  PID  | PromPort | Status   
-------------+--------+-------+----------+----------
  dc-1       | v-72   | 15541 |          | running  
```
