### ISSUE TITLE
Poller with multiple influxdb exporters forward only to the latest influxdb exporter from list

### ISSUE THREAD

**Issue by dudy-duce** [NetApp/harvest#849]
Hello community,

We installed harvest-21.11.1-1.x86_64 on Red Hat Enterprise Linux release 8.4 (Ootpa).
We configured 4 influxdb exporters and poller is only sending data to the latest influxdb exporter from list.
Example /opt/harvest/harvest.yml :

```
Tools:
#  grafana_api_token: 'aaa-bbb-ccc-ddd'
#  autosupport_disabled: true

Exporters:
  influx_vdr1:
    exporter: InfluxDB
    addr: 10.114.176.27
    bucket: netapp
    org: socle
    token: XYXY
  influx_vdr2:
    exporter: InfluxDB
    addr: 10.114.176.28
    bucket: netapp
    org: socle
    token: XYXY
  influx_aub1:
    exporter: InfluxDB
    addr: 10.114.138.173
    bucket: netapp
    org: socle
    token: XYXY
  influx_aub2:
    exporter: InfluxDB
    addr: 10.114.138.174
    bucket: netapp
    org: socle
    token: XYXY

Defaults:
  collectors:
    - Zapi
    - ZapiPerf
  use_insecure_tls: false

Pollers:
  # this is a special/optional poller that provides stats about harvest itself
  # to remove this poller, simply delete the section "unix"
  unix:
    datacenter: local
    addr: localhost
    collectors:
      - Unix
    exporters:
      - influx_vdr1
      - influx_vdr2
      - influx_aub1
      - influx_aub2
  # add your Cdot / 7Mode pollers below, example:
  cluster-vdr:
    datacenter: XXXXXXX
    addr: 10.109.Y.X
    auth_style: basic_auth
    username: harvest
    password: XYXY
    use_insecure_tls: true   # since we don't use certificate authentication
    exporters:
      - influx_vdr1
      - influx_vdr2
      - influx_aub1
      - influx_aub2
```
Extract from /var/log/harvest/poller_unix.log :
```
{"level":"info","Poller":"unix","caller":"./poller.go:349","time":"2022-02-11T15:32:08+01:00","message":"poller start-up complete"}
{"level":"info","Poller":"unix","caller":"./poller.go:496","time":"2022-02-11T15:32:08+01:00","message":"updated status, up collectors: 1 (of 1), up exporters: 1 (of 1)"}
```
Extract from /var/log/harvest/poller_cluster-vdr.log
```
{"level":"info","Poller":"cluster-vdr","caller":"./poller.go:496","time":"2022-02-11T15:53:09+01:00","message":"updated status, up collectors: 32 (of 46), up exporters: 1 (of 1)"}
```

Harvest is only sending data to influx_aub2 for both pollers.

Regards, Kevin
