### ISSUE TITLE
add counter up_time to lif

### ISSUE THREAD

**Issue by adamallmer** [NetApp/harvest#954]
**Describe the bug**
trying to add counter up_time to lif.yaml but harvest doesn't collect it.
I tried to add other counters from same object which worked as expected. It's seems it's just up_time I can't add.

::*> statistics catalog counter show -object lif

Object: lif
    Counter                     Description
    --------------------------- ----------------------------------------------
    current_port                Physical port hosting this LIF
    instance_name               Name of the logical interface (LIF) instance
    instance_uuid               UUID for the logical interface (LIF) instance
    node_name                   System node name
    node_uuid                   System node id
    process_name                Ontap process that provided this instance
    recv_data                   Number of bytes received per second
    recv_errors                 Number of received Errors per second
    recv_packet                 Number of packets received per second
    sent_data                   Number of bytes sent per second
    sent_errors                 Number of sent errors per second
    sent_packet                 Number of packets sent per second
    total_data                  Number of bytes received and sent per second
    total_packet                Number of packets received and sent per second
    up_time                     Interface up time
    vserver_id                  ID of the Vserver
    vserver_name                Name of the Vserver

# cat lif.yaml 

name:                     LIF
query:                    lif
object:                   lif

counters:
  - instance_uuid
  - instance_name
  - node_name                => node
  - vserver_name             => svm
  - current_port             => port
  - recv_data
  - recv_packet
  - sent_data
  - sent_packet
  - sent_errors
  - up_time

export_options:
  instance_keys:
    - lif
    - node
    - svm
    - port

**Environment**

- Harvest version: [arvest version 21.11.1-1 (commit 41d7780) (build date 2021-12-10T11:01:52-0500) linux/amd64]
- OS: RHEL 7.9
- Install method: yum
- ONTAP Version: 9.8P7
- Other:

**Comment by cgrinds** [comment]
hi @adamallmer I think that's because `up_time` is being returned as a string instead of a number and metrics can only be numbers.

Can you say a bit more about how you want to use up_time? You can add `up_time` as a label like shown below. If you want to add it as a separate metric, we'll need to create a simple plugin that converts the string to a number.

File: `conf/zapiperf/cdot/9.8.0/lif.yaml`
```yaml

name:                     LIF
query:                    lif
object:                   lif

counters:
  - instance_uuid
  - instance_name
  - node_name                => node
  - vserver_name             => svm
  - current_port             => port
  - recv_data
  - recv_packet
  - recv_errors
  - sent_data
  - sent_packet
  - sent_errors
  - up_time

export_options:
  instance_keys:
    - lif
    - node
    - svm
    - port
  instance_labels:
    - up_time

```


Example output
```
lif_labels{cluster="umeng-aff300-05-06",datacenter="dc-1",lif="vs_test4_admin_lif1",node="umeng-aff300-05",port="e0d",svm="vs_test4",up_time="894529276"} 1.0
lif_labels{cluster="umeng-aff300-05-06",datacenter="dc-1",lif="vs_test4_cifs_lif1",node="umeng-aff300-05",port="e0d",svm="vs_test4",up_time="894529325"} 1.0
```

**Comment by adamallmer** [comment]
Hi,

I want to measure the uptime and do an availability feature. If I add it as an label I guess it wont be visible if it's down?

**Comment by adamallmer** [comment]
But I think using the ontap REST instead of ZAPI will solve it :)

**Comment by cgrinds** [comment]
hi @adamallmer - that's right, if the interface is down the perf zapi won't return statistic for it. 

Maybe you want to use the `net-interface-get-iter` ZAPI which includes an `operational-status` of up/down. That corresponds to the REST endpoint `networking/network_ip_interfaces_get` attribute `state`.

Let us know if that's something you'd like help with

**Comment by adamallmer** [comment]
Hi, 
Ok so something like this not sure if the object is correct? 

name:                    LIF-OP
query:                    net-interface-get-iter
object:                   lif

counters:  
  net-interface-info:
    - operational-status

export_options:
  instance_keys:
    - lif

  instance_labels:
    - operational-status

**Comment by cgrinds** [comment]
Does this template do what you want @adamallmer?

```yaml

name:                       LifOperational
query:                      net-interface-get-iter
object:                     lif_operational

counters:
  net-interface-info:
    - ^operational-status   => operational_status
    - ^vserver              => svm
    - ^interface-name       => interface_name
    - ^^lif-uuid            => lif_uuid
    
collect_only_labels: true

export_options:
  instance_labels:
    - operational_status
    - svm
    - interface_name
  instance_keys:
    - lif_uuid
```
