### ISSUE TITLE
Prometheus exporter can not work with harvest-21.08.0

### ISSUE THREAD

**Issue by finalha** [NetApp/harvest#966]
My netapp cluster is in 10.100.33.7 and I want to create the harvest in 10.100.98.14 and use prometheus to get the metrics.
The versions of the software:
prometheus: 2.11.0
harvest:  21.08.0
netapp: Release 9.7P4: Sat May 23 00:43:42 UTC 2020

harvest.yml is below and I am sure that the user has the permission:
```
Tools:
#  grafana_api_token: 'aaa-bbb-ccc-ddd'
#  autosupport_disabled: true

Exporters:
  prometheus:
    exporter: Prometheus
    #local_http_addr: 10.100.98.14
    local_http_addr: 0.0.0.0
    port: 12990
  prometheus1:
    exporter: Prometheus
    port: 12991

Defaults:
  collectors:
    - Zapi
    - ZapiPerf
  use_insecure_tls: true

Pollers:
  # this is a special/optional poller that provides stats about harvest itself
  # to remove this poller, simply delete the section "unix"
  #unix:
  #  datacenter: local
  #  addr: localhost
  #  collectors:
  #    - Unix
  #  exporters:
  #    - prometheus
  
  cluster-01:
     datacenter: y_2720
     addr: 10.100.33.7
     auth_style: basic_auth
     username: '${username}'
     password: '${password}'
     use_insecure_tls: true  # Disable TLS verification when connecting to ONTAP cluster
     exporters:
       - prometheus
  
  cluster-02:
     datacenter: y_2720
     addr: 10.100.33.7
     auth_style: basic_auth
     username: '${username}'
     password: '${password}'
     use_insecure_tls: true  # Disable TLS verification when connecting to ONTAP cluster
     exporters:
       - prometheus1
```

The content of prometheus configration:

      - job_name: 'harvest.test'
        scrape_interval: 60s 
        metrics_path: /metrics
        scheme: http
        bearer_token: bearer_token
        static_configs:
          - targets:
            - '10.100.98.14:12990'
            - '10.100.98.14:12991'

When I run "bin/harvest start", the poller is running
  Datacenter |   Poller   |  PID   | PromPort | Status   
-------------+------------+--------+----------+----------
  y_2720     | cluster-01 | 192833 |    12990 | running  
  y_2720     | cluster-02 | 192847 |    12991 | running 

But I found the issue in prometheus: 
Get http://10.100.98.14:12990/metrics: dial tcp 10.100.98.14:12990: connect: connection refused
Get http://10.100.98.14:12991/metrics: dial tcp 10.100.98.14:12991: connect: connection refused
And I found the exporter is not working according to the log
{"level":"warn","Poller":"cluster-01","caller":"./poller.go:269","time":"2022-04-14T17:00:18+08:00","message":"no exporters initialized, continuing without exporters"}
{"level":"info","Poller":"cluster-01","caller":"./poller.go:472","time":"2022-04-14T17:00:18+08:00","message":"updated status, up collectors: 44 (of 44), up exporters: 0 (of 0)"}
{"level":"info","Poller":"cluster-01","caller":"./poller.go:472","time":"2022-04-14T17:01:18+08:00","message":"updated status, up collectors: 43 (of 44), up exporters: 0 (of 0)"}
{"level":"info","Poller":"cluster-01","caller":"./poller.go:472","time":"2022-04-14T17:11:18+08:00","message":"updated status, up collectors: 26 (of 44), up exporters: 0 (of 0)"}

{"level":"warn","Poller":"cluster-02","caller":"./poller.go:269","time":"2022-04-14T17:00:22+08:00","message":"no exporters initialized, continuing without exporters"}
{"level":"info","Poller":"cluster-02","caller":"./poller.go:472","time":"2022-04-14T17:00:22+08:00","message":"updated status, up collectors: 44 (of 44), up exporters: 0 (of 0)"}
{"level":"info","Poller":"cluster-02","caller":"./poller.go:472","time":"2022-04-14T17:01:22+08:00","message":"updated status, up collectors: 43 (of 44), up exporters: 0 (of 0)"}
{"level":"info","Poller":"cluster-02","caller":"./poller.go:472","time":"2022-04-14T17:11:22+08:00","message":"updated status, up collectors: 29 (of 44), up exporters: 0 (of 0)"}

How to debug it?
